version: 2
sources:
- name: cocoon
  tables:
  - project_data
  - project_task_data
  - section_data
  - story_data
  - tag_data
  - task_data
  - task_follower_data
  - task_section_data
  - task_tag_data
  - team_data
  - user_data
