version: 2
sources:
- name: cocoon
  tables:
  - facebook_ads_account_history_data
  - facebook_ads_ad_history_data
  - facebook_ads_ad_set_history_data
  - facebook_ads_basic_ad_data
  - facebook_ads_campaign_history_data
  - facebook_ads_creative_history_data
