version: 2
sources:
- name: cocoon
  tables:
  - care_site
  - condition_occurrence
  - cost
  - death
  - device
  - drug_exposure
  - location
  - measurement
  - observation
  - payer_plan_period
  - person
  - procedure_occurrence
  - provider
  - specimen
  - visit_occurrence
