version: 2
sources:
- name: cocoon
  database: memory
  schema: main
  tables:
  - name: care_site
  - name: condition_occurrence
  - name: cost
  - name: death
  - name: device
  - name: drug_exposure
  - name: location
  - name: measurement
  - name: observation
  - name: payer_plan_period
  - name: person
  - name: procedure_occurrence
  - name: provider
  - name: specimen
  - name: visit_detail
  - name: visit_occurrence
