version: 2
models:
- name: SalesforceObjectSharingConfiguration
  description: These tables store sharing rules for Salesforce objects. They cover
    customer interactions, marketing activities, and data management. Each partition
    represents a specific object or feature. The tables likely contain user or group
    IDs, access levels, and other sharing details.
  columns:
  - name: ID
    description: Unique identifier for the sharing rule
    tests:
    - not_null
  - name: PARENT_ID
    description: ID of the parent record
    tests:
    - not_null
  - name: USER_OR_GROUP_ID
    description: ID of the user or group granted access
    tests:
    - not_null
  - name: ACCESS_LEVEL
    description: Specifies the level of access granted
    tests:
    - not_null
  - name: ROW_CAUSE
    description: Reason for the sharing rule's creation
    tests:
    - not_null
  - name: LAST_MODIFIED_DATE
    description: Date and time of the last modification
    tests:
    - not_null
  - name: LAST_MODIFIED_BY_ID
    description: ID of the user who last modified the record
    tests:
    - not_null
  - name: IS_DELETED
    description: Indicates if the record is deleted
    tests:
    - not_null
  - name: _FIVETRAN_DELETED
    description: Fivetran's deletion flag
    tests:
    - not_null
  - name: _FIVETRAN_SYNCED
    description: Timestamp of Fivetran's last synchronization
    tests:
    - not_null
  tests: []
cocoon_meta:
  partitions:
  - ACTION_CADENCE_SHARE
  - ACTION_CADENCE_TRACKER_SHARE
  - ALTERNATIVE_PAYMENT_METHOD_SHARE
  - AUTHORIZATION_FORM_CONSENT_SHARE
  - AUTHORIZATION_FORM_DATA_USE_SHARE
  - AUTHORIZATION_FORM_SHARE
  - BUSINESS_BRAND_SHARE
  - CALCULATED_INSIGHT_RANGE_BOUND_SHARE
  - CALENDAR_VIEW_SHARE
  - CALL_TEMPLATE_SHARE
  - COMM_SUBSCRIPTION_CHANNEL_TYPE_SHARE
  - COMM_SUBSCRIPTION_CONSENT_SHARE
  - COMM_SUBSCRIPTION_SHARE
  - CONTACT_POINT_ADDRESS_SHARE
  - CONTACT_POINT_CONSENT_SHARE
  - CONTACT_POINT_EMAIL_SHARE
  - CONTACT_POINT_PHONE_SHARE
  - CONTACT_POINT_TYPE_CONSENT_SHARE
  - CONTACT_REQUEST_SHARE
  - CUSTOMER_SHARE
  - DATA_ACTION_TARGET_SHARE
  - DATA_KIT_DEPLOYMENT_LOG_SHARE
  - DATA_LAKE_OBJECT_INSTANCE_SHARE
  - DATA_SOURCE_BUNDLE_SHARE
  - DATA_STREAM_SHARE
  - DATA_USE_LEGAL_BASIS_SHARE
  - DATA_USE_PURPOSE_SHARE
  - ENGAGEMENT_CHANNEL_TYPE_SHARE
  - EXTERNAL_EVENT_MAPPING_SHARE
  - EXT_DATA_SHARE_TARGET_SHARE
  - FLOW_INTERVIEW_LOG_SHARE
  - FLOW_INTERVIEW_SHARE
  - FLOW_RECORD_SHARE
  - FLOW_TEST_RESULT_SHARE
  - GOAL_ASSIGNMENT_RECOMMENDATION_SHARE
  - GOAL_ASSIGNMENT_SHARE
  - GOAL_DEFINITION_SHARE
  - IMAGE_SHARE
  - KNOWLEDGE_SHARE
  - LIST_EMAIL_SHARE
  - MERCHANT_ACCOUNT_SHARE
  - MKT_DATA_TRANSFORM_SHARE
  - MKT_MLMODEL_SHARE
  - OBJECT_DATA_IMPORT_SHARE
  - OPERATING_HOURS_SHARE
  - PARTY_CONSENT_SHARE
  - PROMPT_ACTION_SHARE
  - PROMPT_ERROR_SHARE
  - QUICK_TEXT_SHARE
  - QUICK_TEXT_USAGE_SHARE
  - SELLER_SHARE
  - TABLEAU_HOST_MAPPING_SHARE
  - TODAY_GOAL_SHARE
  - USER_APP_MENU_CUSTOMIZATION_SHARE
  - USER_DEFINED_LABEL_ASSIGNMENT_SHARE
  - USER_DEFINED_LABEL_SHARE
  - USER_EMAIL_PREFERRED_PERSON_SHARE
  - USER_PROVISIONING_REQUEST_SHARE
  - USER_WORK_LIST_SHARE
  - VIDEO_CALL_SHARE
