version: 2
sources:
- name: cocoon
  tables:
  - comment
  - component
  - epic
  - field
  - field_option
  - issue
  - issue_field_history
  - issue_link
  - issue_multiselect_history
  - issue_type
  - priority
  - project
  - project_board
  - project_category
  - resolution
  - sprint
  - status
  - status_category
  - user
  - user_group
  - version
