version: 2
sources:
- name: cocoon
  tables:
  - sap_bkpf_data
  - sap_bseg_data
  - sap_faglflexa_data
  - sap_faglflext_data
  - sap_kna1_data
  - sap_lfa1_data
  - sap_mara_data
  - sap_pa0000_data
  - sap_pa0001_data
  - sap_pa0007_data
  - sap_pa0008_data
  - sap_pa0031_data
  - sap_ska1_data
  - sap_t001_data
  - sap_t503_data
  - sap_t880_data
