version: 2
sources:
- name: cocoon
  tables:
  - app
  - app_store_platform_version_source_type
  - app_store_source_type_device
  - app_store_territory_source_type
  - crashes_app_version
  - crashes_platform_version
  - downloads_platform_version_source_type
  - downloads_source_type_device
  - downloads_territory_source_type
  - sales_account
  - sales_subscription_events
  - sales_subscription_summary
  - usage_app_version_source_type
  - usage_platform_version_source_type
  - usage_source_type_device
  - usage_territory_source_type
