version: 2
sources:
- name: cocoon
  database: memory
  schema: main
  tables:
  - name: advertised_product_report_data
  - name: ad_group_history_data
  - name: ad_group_level_report_data
  - name: campaign_history_data
  - name: campaign_level_report_data
  - name: keyword_history_data
  - name: portfolio_history_data
  - name: product_ad_history_data
  - name: profile_data
  - name: search_term_ad_keyword_report_data
  - name: targeting_keyword_report_data
