version: 2
sources:
- name: cocoon
  tables:
  - ad_group_history_data
  - ad_group_level_report_data
  - advertised_product_report_data
  - campaign_history_data
  - campaign_level_report_data
  - keyword_history_data
  - portfolio_history_data
  - product_ad_history_data
  - profile_data
  - search_term_ad_keyword_report_data
  - targeting_keyword_report_data
