name: 'hubspot'
version: '0.17.2'
profile: 'integration_tests' 
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
vars:
  hubspot:
    contact: "{{ ref('stg_hubspot__contact') }}"
    contact_merge_audit: "{{ ref('stg_hubspot__contact_merge_audit') }}"
    contact_list: "{{ ref('stg_hubspot__contact_list') }}"
    contact_list_member: "{{ ref('stg_hubspot__contact_list_member') }}"
    contact_property_history: "{{ ref('stg_hubspot__contact_property_history') }}"
    company: "{{ ref('stg_hubspot__company') }}"
    company_property_history: "{{ ref('stg_hubspot__company_property_history') }}"
    deal: "{{ ref('stg_hubspot__deal') }}"
    merged_deal: "{{ ref('stg_hubspot__merged_deal') }}"
    deal_stage: "{{ ref('stg_hubspot__deal_stage') }}"
    deal_company: "{{ ref('stg_hubspot__deal_company') }}"
    deal_pipeline: "{{ ref('stg_hubspot__deal_pipeline') }}"
    deal_pipeline_stage: "{{ ref('stg_hubspot__deal_pipeline_stage') }}"
    deal_property_history: "{{ ref('stg_hubspot__deal_property_history') }}"
    owner: "{{ ref('stg_hubspot__owner') }}"
    email_event_bounce: "{{ ref('stg_hubspot__email_event_bounce') }}"
    email_event_click: "{{ ref('stg_hubspot__email_event_click') }}"
    email_event_deferred: "{{ ref('stg_hubspot__email_event_deferred') }}"
    email_event_delivered: "{{ ref('stg_hubspot__email_event_delivered') }}"
    email_event_dropped: "{{ ref('stg_hubspot__email_event_dropped') }}"
    email_event_forward: "{{ ref('stg_hubspot__email_event_forward') }}"
    email_event_open: "{{ ref('stg_hubspot__email_event_open') }}"
    email_event_print: "{{ ref('stg_hubspot__email_event_print') }}"
    email_event_sent: "{{ ref('stg_hubspot__email_event_sent') }}"
    email_event_spam_report: "{{ ref('stg_hubspot__email_event_spam_report') }}"
    email_event_status_change: "{{ ref('stg_hubspot__email_event_status_change') }}"
    email_event: "{{ ref('stg_hubspot__email_event') }}"
    engagement: "{{ ref('stg_hubspot__engagement') }}"
    engagement_call: "{{ ref('stg_hubspot__engagement_call') }}"
    engagement_company: "{{ ref('stg_hubspot__engagement_company') }}"
    engagement_contact: "{{ ref('stg_hubspot__engagement_contact') }}"
    engagement_deal: "{{ ref('stg_hubspot__engagement_deal') }}"
    engagement_email_cc: "{{ ref('stg_hubspot__engagement_email_cc') }}"
    engagement_email_to: "{{ ref('stg_hubspot__engagement_email_to') }}"
    engagement_email: "{{ ref('stg_hubspot__engagement_email') }}"
    engagement_meeting: "{{ ref('stg_hubspot__engagement_meeting') }}"
    engagement_note: "{{ ref('stg_hubspot__engagement_note') }}"
    engagement_task: "{{ ref('stg_hubspot__engagement_task') }}"
    
    ticket_company: "{{ ref('stg_hubspot__ticket_company') }}"
    ticket_contact: "{{ ref('stg_hubspot__ticket_contact') }}"
    ticket_deal: "{{ ref('stg_hubspot__ticket_deal') }}"
    ticket_engagement: "{{ ref('stg_hubspot__ticket_engagement') }}"
    ticket_pipeline: "{{ ref('stg_hubspot__ticket_pipeline') }}"
    ticket_pipeline_stage: "{{ ref('stg_hubspot__ticket_pipeline_stage') }}"
    ticket_property_history: "{{ ref('stg_hubspot__ticket_property_history') }}"
    ticket: "{{ ref('stg_hubspot__ticket') }}"
    
    hubspot_contact_merge_audit_enabled: false
models:
  hubspot:
    +materialized: table
    +schema: hubspot
    marketing:
      intermediate:
        +materialized: ephemeral
        int_hubspot__contact_merge_adjust:
          +materialized: table
    sales:
      intermediate:
        +materialized: ephemeral
