version: 2
sources:
- name: cocoon
  tables:
  - account_data
  - balance_transaction_data
  - card_data
  - charge_data
  - credit_note_data
  - credit_note_line_item_data
  - customer_data
  - dispute_data
  - fee_data
  - invoice_data
  - invoice_line_item_data
  - payment_intent_data
  - payment_method_card_data
  - payment_method_data
  - payout_data
  - plan_data
  - price_data
  - refund_data
  - subscription_data
  - subscription_history_data
  - transfer_data
