version: 2
sources:
- name: cocoon
  database: memory
  schema: main
  tables:
  - name: ACCEPTED_EVENT_RELATION
  - name: ACCOUNT
  - name: ACCOUNT_CONTACT_ROLE
  - name: ACCOUNT_PARTNER
  - name: ACCOUNT_SHARE
  - name: ACCOUNT_TAG
  - name: ACTION_CADENCE
  - name: ACTION_CADENCE_RULE
  - name: ACTION_CADENCE_RULE_CONDITION
  - name: ACTION_CADENCE_SHARE
  - name: ACTION_CADENCE_STEP
  - name: ACTION_CADENCE_STEP_TRACKER
  - name: ACTION_CADENCE_TRACKER
  - name: ACTION_CADENCE_TRACKER_SHARE
  - name: ACTION_LINK_GROUP_TEMPLATE
  - name: ACTION_LINK_TEMPLATE
  - name: ACTIVITY_USR_CONNECTION_STATUS
  - name: ADDITIONAL_NUMBER
  - name: ALTERNATIVE_PAYMENT_METHOD
  - name: ALTERNATIVE_PAYMENT_METHOD_SHARE
  - name: APEX_COMPONENT
  - name: APEX_LOG
  - name: APEX_PAGE
  - name: APEX_PAGE_INFO
  - name: APP_ANALYTICS_QUERY_REQUEST
  - name: APP_DEFINITION
  - name: APP_MENU_ITEM
  - name: ASSET
  - name: ASSET_RELATIONSHIP
  - name: ASSET_SHARE
  - name: ASSET_TAG
  - name: ASSIGNMENT_RULE
  - name: ATTACHMENT
  - name: AURA_DEFINITION
  - name: AURA_DEFINITION_BUNDLE
  - name: AURA_DEFINITION_BUNDLE_INFO
  - name: AURA_DEFINITION_INFO
  - name: AUTHORIZATION_FORM
  - name: AUTHORIZATION_FORM_CONSENT
  - name: AUTHORIZATION_FORM_CONSENT_SHARE
  - name: AUTHORIZATION_FORM_DATA_USE
  - name: AUTHORIZATION_FORM_DATA_USE_SHARE
  - name: AUTHORIZATION_FORM_SHARE
  - name: AUTHORIZATION_FORM_TEXT
  - name: AUTH_CONFIG
  - name: AUTH_CONFIG_PROVIDERS
  - name: AUTH_PROVIDER
  - name: AUTH_SESSION
  - name: BACKGROUND_OPERATION
  - name: BRANDING_SET
  - name: BRANDING_SET_PROPERTY
  - name: BRAND_TEMPLATE
  - name: BRIEFCASE_ASSIGNMENT
  - name: BRIEFCASE_DEFINITION
  - name: BRIEFCASE_RULE
  - name: BRIEFCASE_RULE_FILTER
  - name: BUSINESS_BRAND
  - name: BUSINESS_BRAND_SHARE
  - name: BUSINESS_HOURS
  - name: BUSINESS_PROCESS
  - name: CALCULATED_INSIGHT_RANGE_BOUND
  - name: CALCULATED_INSIGHT_RANGE_BOUND_SHARE
  - name: CALENDAR
  - name: CALENDAR_VIEW
  - name: CALENDAR_VIEW_SHARE
  - name: CALL_CENTER
  - name: CALL_COACHING_MEDIA_PROVIDER
  - name: CALL_DISPOSITION
  - name: CALL_DISPOSITION_CATEGORY
  - name: CALL_TEMPLATE
  - name: CALL_TEMPLATE_SHARE
  - name: CAMPAIGN
  - name: CAMPAIGN_MEMBER
  - name: CAMPAIGN_MEMBER_STATUS
  - name: CAMPAIGN_SHARE
  - name: CAMPAIGN_TAG
  - name: CARD_PAYMENT_METHOD
  - name: CASE
  - name: CASE_ARTICLE
  - name: CASE_COMMENT
  - name: CASE_CONTACT_ROLE
  - name: CASE_EXTERNAL_DOCUMENT
  - name: CASE_SHARE
  - name: CASE_STATUS
  - name: CASE_TAG
  - name: CATEGORY_NODE
  - name: CLIENT_BROWSER
  - name: COMM_SUBSCRIPTION
  - name: COMM_SUBSCRIPTION_CHANNEL_TYPE
  - name: COMM_SUBSCRIPTION_CHANNEL_TYPE_SHARE
  - name: COMM_SUBSCRIPTION_CONSENT
  - name: COMM_SUBSCRIPTION_CONSENT_SHARE
  - name: COMM_SUBSCRIPTION_SHARE
  - name: COMM_SUBSCRIPTION_TIMING
  - name: CONFERENCE_NUMBER
  - name: CONNECTED_APPLICATION
  - name: CONTACT
  - name: CONTACT_POINT_ADDRESS
  - name: CONTACT_POINT_ADDRESS_IDENTITY_LINK_DLM
  - name: CONTACT_POINT_ADDRESS_SHARE
  - name: CONTACT_POINT_CONSENT
  - name: CONTACT_POINT_CONSENT_SHARE
  - name: CONTACT_POINT_EMAIL
  - name: CONTACT_POINT_EMAIL_IDENTITY_LINK_DLM
  - name: CONTACT_POINT_EMAIL_SHARE
  - name: CONTACT_POINT_PHONE
  - name: CONTACT_POINT_PHONE_IDENTITY_LINK_DLM
  - name: CONTACT_POINT_PHONE_SHARE
  - name: CONTACT_POINT_TYPE_CONSENT
  - name: CONTACT_POINT_TYPE_CONSENT_SHARE
  - name: CONTACT_REQUEST
  - name: CONTACT_REQUEST_SHARE
  - name: CONTACT_SHARE
  - name: CONTACT_TAG
  - name: CONTENT_ASSET
  - name: CONTENT_DISTRIBUTION
  - name: CONTENT_DISTRIBUTION_VIEW
  - name: CONTENT_DOCUMENT
  - name: CONTENT_DOCUMENT_SUBSCRIPTION
  - name: CONTENT_FOLDER
  - name: CONTENT_FOLDER_LINK
  - name: CONTENT_NOTE
  - name: CONTENT_NOTIFICATION
  - name: CONTENT_TAG_SUBSCRIPTION
  - name: CONTENT_USER_SUBSCRIPTION
  - name: CONTENT_VERSION
  - name: CONTENT_VERSION_COMMENT
  - name: CONTENT_VERSION_RATING
  - name: CONTENT_WORKSPACE
  - name: CONTENT_WORKSPACE_DOC
  - name: CONTENT_WORKSPACE_MEMBER
  - name: CONTENT_WORKSPACE_PERMISSION
  - name: CONTENT_WORKSPACE_SUBSCRIPTION
  - name: CORS_WHITELIST_ENTRY
  - name: CSP_TRUSTED_SITE
  - name: CUSTOMER
  - name: CUSTOMER_SHARE
  - name: CUSTOM_BRAND
  - name: CUSTOM_BRAND_ASSET
  - name: CUSTOM_HELP_MENU_ITEM
  - name: CUSTOM_HELP_MENU_SECTION
  - name: CUSTOM_HTTP_HEADER
  - name: CUSTOM_NOTIFICATION_TYPE
  - name: CUSTOM_PERMISSION
  - name: CUSTOM_PERMISSION_DEPENDENCY
  - name: DASHBOARD
  - name: DASHBOARD_COMPONENT
  - name: DASHBOARD_TAG
  - name: DATA_ACTION
  - name: DATA_ACTION_TARGET
  - name: DATA_ACTION_TARGET_SHARE
  - name: DATA_GRAPH
  - name: DATA_KIT_DEPLOYMENT_LOG
  - name: DATA_KIT_DEPLOYMENT_LOG_SHARE
  - name: DATA_LAKE_OBJECT_INSTANCE
  - name: DATA_LAKE_OBJECT_INSTANCE_SHARE
  - name: DATA_MULTI_ORG_CONNECTION
  - name: DATA_MULTI_ORG_OBJECT_REF
  - name: DATA_MULTI_ORG_SYNC_STATUS
  - name: DATA_QUERY_WORKSPACE
  - name: DATA_QUERY_WORKSPACE_TAB
  - name: DATA_REMOTE_ORG_DATA_SPACE_MAP
  - name: DATA_SEMANTIC_SEARCH
  - name: DATA_SOURCE_BUNDLE
  - name: DATA_SOURCE_BUNDLE_SHARE
  - name: DATA_SPACE
  - name: DATA_SPACE_FILTER_CONDITION
  - name: DATA_SPACE_FILTER_CRITERIA
  - name: DATA_SPACE_INTERNAL_ORG
  - name: DATA_STREAM
  - name: DATA_STREAM_SHARE
  - name: DATA_USE_LEGAL_BASIS
  - name: DATA_USE_LEGAL_BASIS_SHARE
  - name: DATA_USE_PURPOSE
  - name: DATA_USE_PURPOSE_SHARE
  - name: DATA_WEAVE_RESOURCE
  - name: DECLINED_EVENT_RELATION
  - name: DELETE_EVENT
  - name: DIGITAL_WALLET
  - name: DOCUMENT
  - name: DOCUMENT_ATTACHMENT_MAP
  - name: DOCUMENT_TAG
  - name: DOMAIN
  - name: DOMAIN_SITE
  - name: DUPLICATE_RECORD_ITEM
  - name: DUPLICATE_RECORD_SET
  - name: DUPLICATE_RULE
  - name: EMAIL_CAPTURE
  - name: EMAIL_CONTENT
  - name: EMAIL_DOMAIN_FILTER
  - name: EMAIL_DOMAIN_KEY
  - name: EMAIL_MESSAGE
  - name: EMAIL_MESSAGE_RELATION
  - name: EMAIL_RELAY
  - name: EMAIL_ROUTING_ADDRESS
  - name: EMAIL_SERVICES_ADDRESS
  - name: EMAIL_SERVICES_FUNCTION
  - name: EMAIL_TEMPLATE
  - name: EMBEDDED_SERVICE_DETAIL
  - name: EMBEDDED_SERVICE_LABEL
  - name: ENGAGEMENT_CHANNEL_TYPE
  - name: ENGAGEMENT_CHANNEL_TYPE_SHARE
  - name: ENGMT_CHANNEL_TYPE_SETTINGS
  - name: EVENT
  - name: EVENT_BUS_SUBSCRIBER
  - name: EVENT_RELATION
  - name: EVENT_RELAY_CONFIG
  - name: EVENT_RELAY_FEEDBACK
  - name: EVENT_TAG
  - name: EVENT_WHO_RELATION
  - name: EXPRESSION_SET_VIEW
  - name: EXTERNAL_DATA_SOURCE
  - name: EXTERNAL_DATA_SRC_DESCRIPTOR
  - name: EXTERNAL_DATA_USER_AUTH
  - name: EXTERNAL_EVENT
  - name: EXTERNAL_EVENT_MAPPING
  - name: EXTERNAL_EVENT_MAPPING_SHARE
  - name: EXTERNAL_STRING
  - name: EXT_DATA_SHARE
  - name: EXT_DATA_SHARE_TARGET
  - name: EXT_DATA_SHARE_TARGET_SHARE
  - name: FLOW_DEFINITION_VIEW
  - name: FLOW_INTERVIEW
  - name: FLOW_INTERVIEW_LOG
  - name: FLOW_INTERVIEW_LOG_ENTRY
  - name: FLOW_INTERVIEW_LOG_SHARE
  - name: FLOW_INTERVIEW_SHARE
  - name: FLOW_RECORD
  - name: FLOW_RECORD_ELEMENT
  - name: FLOW_RECORD_RELATION
  - name: FLOW_RECORD_SHARE
  - name: FLOW_RECORD_VERSION
  - name: FLOW_RECORD_VERSION_OCCURRENCE
  - name: FLOW_STAGE_RELATION
  - name: FLOW_TEST_RESULT
  - name: FLOW_TEST_RESULT_SHARE
  - name: FOLDER
  - name: FORMULA_FUNCTION
  - name: FORMULA_FUNCTION_ALLOWED_TYPE
  - name: FORMULA_FUNCTION_CATEGORY
  - name: GOAL_ASSIGNMENT
  - name: GOAL_ASSIGNMENT_RECOMMENDATION
  - name: GOAL_ASSIGNMENT_RECOMMENDATION_SHARE
  - name: GOAL_ASSIGNMENT_SHARE
  - name: GOAL_DEFINITION
  - name: GOAL_DEFINITION_SHARE
  - name: GRANTED_BY_LICENSE
  - name: GROUP
  - name: GROUP_MEMBER
  - name: GTWY_PROV_PAYMENT_METHOD_TYPE
  - name: HOLIDAY
  - name: IDENTITY_RESOLUTION
  - name: IDP_EVENT_LOG
  - name: IFRAME_WHITE_LIST_URL
  - name: IMAGE
  - name: IMAGE_SHARE
  - name: INDIVIDUAL
  - name: INDIVIDUAL_IDENTITY_LINK_DLM
  - name: INDIVIDUAL_SHARE
  - name: INSTALLED_MOBILE_APP
  - name: IPADDRESS_RANGE
  - name: KNOWLEDGE_ARTICLE
  - name: KNOWLEDGE_ARTICLE_VERSION
  - name: KNOWLEDGE_DATA_CATEGORY_SELECTION
  - name: KNOWLEDGE_KA
  - name: KNOWLEDGE_KAV
  - name: KNOWLEDGE_SHARE
  - name: LEAD
  - name: LEAD_STATUS
  - name: LEAD_TAG
  - name: LIGHTNING_EXPERIENCE_THEME
  - name: LIGHTNING_ONBOARDING_CONFIG
  - name: LINKED_ARTICLE
  - name: LIST_EMAIL
  - name: LIST_EMAIL_INDIVIDUAL_RECIPIENT
  - name: LIST_EMAIL_RECIPIENT_SOURCE
  - name: LIST_EMAIL_SHARE
  - name: LIST_VIEW
  - name: LIST_VIEW_CHART
  - name: LOGIN_GEO
  - name: LOGIN_IP
  - name: MAILMERGE_TEMPLATE
  - name: MANAGED_CONTENT
  - name: MANAGED_CONTENT_CHANNEL
  - name: MANAGED_CONTENT_SPACE
  - name: MANAGED_CONTENT_VARIANT
  - name: MARKET_SEGMENT
  - name: MARKET_SEGMENT_DEF_MAPPING
  - name: MATCHING_INFORMATION
  - name: MATCHING_RULE
  - name: MATCHING_RULE_ITEM
  - name: MERCHANT_ACCOUNT
  - name: MERCHANT_ACCOUNT_SHARE
  - name: MERCH_ACC_PAYMENT_METHOD_SET
  - name: MERCH_ACC_PAYMENT_METHOD_TYPE
  - name: MKT_CALCULATED_INSIGHT
  - name: MKT_DATA_LAKE_MAPPING
  - name: MKT_DATA_TRANSFORM
  - name: MKT_DATA_TRANSFORM_SHARE
  - name: MKT_MLMODEL
  - name: MKT_MLMODEL_SHARE
  - name: MKT_MLPREDICTION_JOB
  - name: MKT_SGMT_DEF_CALC_INSIGHT_FLD
  - name: MKT_SGMT_DEF_DATA_MDL_OBJ_FLD
  - name: MOBILE_APPLICATION_DETAIL
  - name: MUTING_PERMISSION_SET
  - name: MY_DOMAIN_DISCOVERABLE_LOGIN
  - name: NAMED_CREDENTIAL
  - name: NOTE
  - name: NOTE_TAG
  - name: OAUTH_CUSTOM_SCOPE
  - name: OAUTH_CUSTOM_SCOPE_APP
  - name: OAUTH_TOKEN
  - name: OAUTH_TOKEN_EXCHANGE_HANDLER
  - name: OAUTH_TOKEN_EXCH_HANDLER_APP
  - name: OBJECT_DATA_IMPORT
  - name: OBJECT_DATA_IMPORT_REFERENCE
  - name: OBJECT_DATA_IMPORT_SHARE
  - name: OBJECT_PERMISSIONS
  - name: OPERATING_HOURS
  - name: OPERATING_HOURS_HOLIDAY
  - name: OPERATING_HOURS_SHARE
  - name: OPPORTUNITY
  - name: OPPORTUNITY_COMPETITOR
  - name: OPPORTUNITY_CONTACT_ROLE
  - name: OPPORTUNITY_LINE_ITEM
  - name: OPPORTUNITY_PARTNER
  - name: OPPORTUNITY_RELATED_DELETE_LOG
  - name: OPPORTUNITY_SHARE
  - name: OPPORTUNITY_STAGE
  - name: OPPORTUNITY_TAG
  - name: ORGANIZATION
  - name: ORG_EMAIL_ADDRESS_SECURITY
  - name: ORG_WIDE_EMAIL_ADDRESS
  - name: PACKAGE_LICENSE
  - name: PARTNER
  - name: PARTNER_ROLE
  - name: PARTY_CONSENT
  - name: PARTY_CONSENT_SHARE
  - name: PAYMENT
  - name: PAYMENT_AUTHORIZATION
  - name: PAYMENT_AUTH_ADJUSTMENT
  - name: PAYMENT_GATEWAY
  - name: PAYMENT_GATEWAY_LOG
  - name: PAYMENT_GATEWAY_PROVIDER
  - name: PAYMENT_GROUP
  - name: PAYMENT_METHOD
  - name: PERIOD
  - name: PERMISSION_SET
  - name: PERMISSION_SET_ASSIGNMENT
  - name: PERMISSION_SET_GROUP
  - name: PERMISSION_SET_GROUP_COMPONENT
  - name: PERMISSION_SET_LICENSE
  - name: PERMISSION_SET_LICENSE_ASSIGN
  - name: PERMISSION_SET_TAB_SETTING
  - name: PRICEBOOK_2
  - name: PRICEBOOK_ENTRY
  - name: PROCESS_DEFINITION
  - name: PROCESS_FLOW_MIGRATION
  - name: PROCESS_INSTANCE
  - name: PROCESS_INSTANCE_NODE
  - name: PROCESS_INSTANCE_STEP
  - name: PROCESS_INSTANCE_WORKITEM
  - name: PROCESS_NODE
  - name: PRODUCT_2
  - name: PROFILE
  - name: PROFILE_CALL_LOG_QUICK_ACTION
  - name: PROMPT
  - name: PROMPT_ACTION
  - name: PROMPT_ACTION_SHARE
  - name: PROMPT_ERROR
  - name: PROMPT_ERROR_SHARE
  - name: PROMPT_VERSION
  - name: QUEUE_SOBJECT
  - name: QUICK_TEXT
  - name: QUICK_TEXT_SHARE
  - name: QUICK_TEXT_USAGE
  - name: QUICK_TEXT_USAGE_SHARE
  - name: RECENTLY_VIEWED
  - name: RECORD_ACTION
  - name: RECORD_TYPE
  - name: REDIRECT_WHITELIST_URL
  - name: REFUND
  - name: REFUND_LINE_PAYMENT
  - name: REPORT
  - name: REPORT_TAG
  - name: SALES_WORK_QUEUE_SETTINGS
  - name: SAML_SSO_CONFIG
  - name: SCONTROL
  - name: SEARCH_ACTIVITY
  - name: SEARCH_PROMOTION_RULE
  - name: SECURITY_CUSTOM_BASELINE
  - name: SELLER
  - name: SELLER_SHARE
  - name: SERVICE_SETUP_PROVISIONING
  - name: SESSION_PERM_SET_ACTIVATION
  - name: SETUP_ASSISTANT_STEP
  - name: SETUP_AUDIT_TRAIL
  - name: SETUP_ENTITY_ACCESS
  - name: SITE
  - name: SITE_IFRAME_WHITE_LIST_URL
  - name: SITE_REDIRECT_MAPPING
  - name: SPSAML_ATTRIBUTES
  - name: SSOT_ACCOUNT_CONTACT_DLM
  - name: SSOT_ACCOUNT_DLM
  - name: SSOT_CONTACT_POINT_ADDRESS_DLM
  - name: SSOT_CONTACT_POINT_EMAIL_DLM
  - name: SSOT_CONTACT_POINT_PHONE_DLM
  - name: SSOT_DIGITAL_CONTENT_DLM
  - name: SSOT_INDIVIDUAL_DLM
  - name: SSOT_LEAD_DLM
  - name: SSOT_MARKET_SEGMENT_DLM
  - name: STAMP
  - name: STAMP_ASSIGNMENT
  - name: STANDARD_INVOCABLE_ACTION_TYPE
  - name: STATIC_RESOURCE
  - name: TABLEAU_HOST_MAPPING
  - name: TABLEAU_HOST_MAPPING_SHARE
  - name: TAB_DEFINITION
  - name: TAG_DEFINITION
  - name: TASK
  - name: TASK_PRIORITY
  - name: TASK_RELATION
  - name: TASK_STATUS
  - name: TASK_TAG
  - name: TASK_WHO_RELATION
  - name: TENANT_USAGE_ENTITLEMENT
  - name: THIRD_PARTY_ACCOUNT_LINK
  - name: TIME_SLOT
  - name: TODAY_GOAL
  - name: TODAY_GOAL_SHARE
  - name: TRANSLATION
  - name: UI_FORMULA_CRITERION
  - name: UI_FORMULA_RULE
  - name: UNDECIDED_EVENT_RELATION
  - name: UNIFIED_CONTACT_POINT_ADDRESS_DLM
  - name: UNIFIED_CONTACT_POINT_EMAIL_DLM
  - name: UNIFIED_CONTACT_POINT_PHONE_DLM
  - name: UNIFIED_INDIVIDUAL_DLM
  - name: USER
  - name: USER_APP_INFO
  - name: USER_APP_MENU_CUSTOMIZATION
  - name: USER_APP_MENU_CUSTOMIZATION_SHARE
  - name: USER_APP_MENU_ITEM
  - name: USER_DEFINED_LABEL
  - name: USER_DEFINED_LABEL_ASSIGNMENT
  - name: USER_DEFINED_LABEL_ASSIGNMENT_SHARE
  - name: USER_DEFINED_LABEL_SHARE
  - name: USER_EMAIL_PREFERRED_PERSON
  - name: USER_EMAIL_PREFERRED_PERSON_SHARE
  - name: USER_LICENSE
  - name: USER_LIST_VIEW
  - name: USER_LIST_VIEW_CRITERION
  - name: USER_LOGIN
  - name: USER_PACKAGE_LICENSE
  - name: USER_PERMISSION_ACCESS
  - name: USER_PREFERENCE
  - name: USER_PROVISIONING_CONFIG
  - name: USER_PROVISIONING_LOG
  - name: USER_PROVISIONING_REQUEST
  - name: USER_PROVISIONING_REQUEST_SHARE
  - name: USER_PROV_ACCOUNT
  - name: USER_PROV_ACCOUNT_STAGING
  - name: USER_PROV_MOCK_TARGET
  - name: USER_ROLE
  - name: USER_SETUP_ENTITY_ACCESS
  - name: USER_SHARE
  - name: USER_WORK_LIST
  - name: USER_WORK_LIST_ITEM
  - name: USER_WORK_LIST_SHARE
  - name: VIDEO_CALL
  - name: VIDEO_CALL_PARTICIPANT
  - name: VIDEO_CALL_RECORDING
  - name: VIDEO_CALL_SHARE
  - name: VIDEO_VENDOR_ADMIN_CONSENT
  - name: VOICE_ORG_SETTING
  - name: WEB_LINK
