config-version: 2

name: 'amplitude_integration_tests'
version: '0.4.0'
config-version: 2
profile: 'integration_tests'

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

vars:
  amplitude_source:
    amplitude_event_identifier: "amplitude_event_data"
    amplitude_event_type_identifier: "amplitude_event_type_data"
    amplitude_schema: amplitude_integration_tests_5

seeds:
  amplitude_integration_tests:
    +column_types:
      _fivetran_synced: timestamp
    amplitude_event_data:
      +column_types:
        id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        app: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        amplitude_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        event_type_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        project_name: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        schema: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        session_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        user_id: "{{ 'varchar(100)' if target.name in ('redshift', 'postgres') else 'string' }}"
    amplitude_event_type_data:
      +column_types:
        id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        project_name: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"