version: 2
sources:
- name: cocoon
  tables:
  - brand_data
  - daylight_time_data
  - domain_name_data
  - group_data
  - organization_data
  - organization_tag_data
  - schedule_data
  - schedule_holiday_data
  - ticket_comment_data
  - ticket_data
  - ticket_field_history_data
  - ticket_form_history_data
  - ticket_schedule_data
  - ticket_tag_data
  - time_zone_data
  - user_data
  - user_tag_data
