version: 2
sources:
- name: cocoon
  tables:
  - block
  - block_question
  - contact_mailing_list_membership
  - core_contact
  - core_mailing_list
  - directory
  - directory_contact
  - directory_mailing_list
  - distribution
  - distribution_contact
  - question
  - question_option
  - question_response
  - sub_question
  - survey
  - survey_embedded_data
  - survey_response
  - survey_version
  - user
