version: 2
sources:
- name: cocoon
  tables:
  - CRM_Call_Center_Logs
  - CRM_Events
  - CRM_Reviews
  - LuxuryLoanPortfolio
  - completedacct
  - completedcard
  - completedclient
  - completeddisposition
  - completeddistrict
  - completedloan
  - completedorder
  - completedtrans
