version: 2
sources:
- name: cocoon
  tables:
  - sf_account_data
  - sf_account_history_data
  - sf_contact_data
  - sf_contact_history_data
  - sf_event_data
  - sf_lead_data
  - sf_opportunity_data
  - sf_opportunity_history_data
  - sf_opportunity_line_item_data
  - sf_order_data
  - sf_product_2_data
  - sf_task_data
  - sf_user_data
  - sf_user_role_data
