version: 2
sources:
- name: cocoon
  tables:
  - twilio_account_history_data
  - twilio_address_data
  - twilio_call_data
  - twilio_incoming_phone_number_data
  - twilio_message_data
  - twilio_messaging_service_data
  - twilio_outgoing_caller_id_data
  - twilio_usage_record_data
