-- COCOON BLOCK START: PLEASE DO NOT MODIFY THIS BLOCK FOR SELF-MAINTENANCE
-- Generated at 2024-07-07 01:45:14.871448+00:00
WITH 
"flights_renamed" AS (
    -- Rename: Renaming columns
    -- tuple_id -> flight_id
    -- src -> airline_code
    -- flight -> flight_code
    -- sched_dep_time -> scheduled_departure_time
    -- act_dep_time -> actual_departure_time
    -- sched_arr_time -> scheduled_arrival_time
    -- act_arr_time -> actual_arrival_time
    SELECT 
        "tuple_id" AS "flight_id",
        "src" AS "airline_code",
        "flight" AS "flight_code",
        "sched_dep_time" AS "scheduled_departure_time",
        "act_dep_time" AS "actual_departure_time",
        "sched_arr_time" AS "scheduled_arrival_time",
        "act_arr_time" AS "actual_arrival_time"
    FROM "memory"."main"."flights"
),

"flights_renamed_cleaned" AS (
    -- Clean unusual string values: 
    -- airline_code: The problem is that the airline_code column contains a mix of airline codes, airport codes, website names, and other irrelevant information. The correct values should be actual airline codes in uppercase. Website names and other irrelevant information should be mapped to an empty string. Airport codes should also be removed as they don't represent airlines. 
    -- scheduled_departure_time: The problem is inconsistent time formatting and unnecessary information. The correct values should follow the format "h:mm a.m." or "h:mm p.m.", with hours not padded with zeros. Times without AM/PM indicators or with additional date information should be standardized. Values that cannot be interpreted should be mapped to "Not Available". 
    -- actual_departure_time: The problem is inconsistent time formats and some non-time entries. The correct values should be in the format 'h:mm a.m.' or 'h:mm p.m.' (12-hour clock with lowercase 'a.m.' or 'p.m.'). Entries like 'Not Available' and 'Contact Airline' are not valid time formats and should be mapped to an empty string to indicate missing data. 
    -- scheduled_arrival_time: The problem is inconsistent time formats and unnecessary date information. The correct values should be in the format "h:mm a.m." or "h:mm p.m." with no leading zeros for hours. All date information should be removed as it's redundant and inconsistent. The "Not Available" value should be mapped to an empty string. 
    -- actual_arrival_time: The problem is that the actual_arrival_time column has inconsistent time formats and some unusual notations. The majority of the values follow the format 'H:MM a.m.' or 'H:MM p.m.' (with periods after a.m. and p.m.), which appears to be the correct format. There are no unusual values in the provided list that need correction. The 'Not Available' value should be kept as is, as it likely represents missing data. 
    SELECT
        "flight_id",
        CASE
            WHEN "airline_code" = 'airtravelcenter' THEN NULL
            WHEN "airline_code" = 'allegiantair' THEN 'G4'
            WHEN "airline_code" = 'boston' THEN NULL
            WHEN "airline_code" = 'businesstravellogue' THEN NULL
            WHEN "airline_code" = 'flights' THEN NULL
            WHEN "airline_code" = 'flightview' THEN NULL
            WHEN "airline_code" = 'flylouisville' THEN NULL
            WHEN "airline_code" = 'flytecomm' THEN NULL
            WHEN "airline_code" = 'foxbusiness' THEN NULL
            WHEN "airline_code" = 'gofox' THEN NULL
            WHEN "airline_code" = 'helloflight' THEN NULL
            WHEN "airline_code" = 'myrateplan' THEN NULL
            WHEN "airline_code" = 'panynj' THEN NULL
            WHEN "airline_code" = 'orbitz' THEN NULL
            WHEN "airline_code" = 'flightstats' THEN NULL
            WHEN "airline_code" = 'quicktrip' THEN NULL
            WHEN "airline_code" = 'weather' THEN NULL
            WHEN "airline_code" = 'travelocity' THEN NULL
            WHEN "airline_code" = 'flightaware' THEN NULL
            WHEN "airline_code" = 'wunderground' THEN NULL
            WHEN "airline_code" = 'flightexplorer' THEN NULL
            WHEN "airline_code" = 'flightarrival' THEN NULL
            WHEN "airline_code" = 'world-flight-tracker' THEN NULL
            WHEN "airline_code" = 'usatoday' THEN NULL
            WHEN "airline_code" = 'aa' THEN 'AA'
            WHEN "airline_code" = 'mytripandmore' THEN NULL
            WHEN "airline_code" = 'ifly' THEN NULL
            WHEN "airline_code" = 'ua' THEN 'UA'
            WHEN "airline_code" = 'ord' THEN NULL
            WHEN "airline_code" = 'flightwise' THEN NULL
            WHEN "airline_code" = 'mco' THEN NULL
            WHEN "airline_code" = 'sfo' THEN NULL
            WHEN "airline_code" = 'den' THEN NULL
            WHEN "airline_code" = 'dfw' THEN NULL
            WHEN "airline_code" = 'mia' THEN NULL
            WHEN "airline_code" = 'phl' THEN NULL
            WHEN "airline_code" = 'iad' THEN NULL
            ELSE "airline_code"
        END AS "airline_code",
        "flight_code",
        CASE
            WHEN "scheduled_departure_time" = '6:00aDec 1' THEN '6:00 a.m.'
            WHEN "scheduled_departure_time" = '11/30 11:08 p.m.' THEN '11:08 p.m.'
            WHEN "scheduled_departure_time" = 'Thu  20:00' THEN '8:00 p.m.'
            WHEN "scheduled_departure_time" = '9:05 a.m. (-00:00)' THEN '9:05 a.m.'
            WHEN "scheduled_departure_time" = '7:10aDec 1' THEN '7:10 a.m.'
            WHEN "scheduled_departure_time" = '8:35aDec 1' THEN '8:35 a.m.'
            WHEN "scheduled_departure_time" = '10:40aDec 1' THEN '10:40 a.m.'
            WHEN "scheduled_departure_time" = '11:25aDec 1' THEN '11:25 a.m.'
            WHEN "scheduled_departure_time" = '10:39aDec 1' THEN '10:39 a.m.'
            WHEN "scheduled_departure_time" = '11:05aDec 1' THEN '11:05 a.m.'
            WHEN "scheduled_departure_time" = '11:40aDec 1' THEN '11:40 a.m.'
            WHEN "scheduled_departure_time" = '11:45aDec 1' THEN '11:45 a.m.'
            WHEN "scheduled_departure_time" = '12:00noon' THEN '12:00 p.m.'
            WHEN "scheduled_departure_time" = '12:30aDec 1' THEN '12:30 a.m.'
            WHEN "scheduled_departure_time" = '6:45aDec 1' THEN '6:45 a.m.'
            WHEN "scheduled_departure_time" = '6:59aDec 1' THEN '6:59 a.m.'
            WHEN "scheduled_departure_time" = '7:00aDec 1' THEN '7:00 a.m.'
            WHEN "scheduled_departure_time" = '7:05aDec 1' THEN '7:05 a.m.'
            WHEN "scheduled_departure_time" = '7:15aDec 1' THEN '7:15 a.m.'
            WHEN "scheduled_departure_time" = '7:25aDec 1' THEN '7:25 a.m.'
            WHEN "scheduled_departure_time" = '7:30aDec 1' THEN '7:30 a.m.'
            WHEN "scheduled_departure_time" = '7:35aDec 1' THEN '7:35 a.m.'
            WHEN "scheduled_departure_time" = '11/30 11:25 a.m.' THEN '11:25a'
            WHEN "scheduled_departure_time" = '11/30 11:55 p.m.' THEN '11:55p'
            WHEN "scheduled_departure_time" = '11/30 12:57 p.m.' THEN '12:57p'
            WHEN "scheduled_departure_time" = '11/30 1:55 p.m.' THEN '1:55p'
            WHEN "scheduled_departure_time" = '11/30 4:00 p.m.' THEN '4:00p'
            WHEN "scheduled_departure_time" = '11/30 4:16 p.m.' THEN '4:16p'
            WHEN "scheduled_departure_time" = '11/30 6:45 p.m.' THEN '6:45p'
            WHEN "scheduled_departure_time" = '11/30 7:45 p.m.' THEN '7:45p'
            WHEN "scheduled_departure_time" = '11/30 8:00 p.m.' THEN '8:00p'
            WHEN "scheduled_departure_time" = '12:00 a.m.' THEN '12:00a'
            WHEN "scheduled_departure_time" = '12:30' THEN '12:30p'
            WHEN "scheduled_departure_time" = '1:09 p.m.' THEN '1:09p'
            WHEN "scheduled_departure_time" = '2:22 p.m.' THEN '2:22p'
            WHEN "scheduled_departure_time" = '2:46 p.m.' THEN '2:46p'
            WHEN "scheduled_departure_time" = '8:41aDec 1' THEN '8:41a'
            WHEN "scheduled_departure_time" = '9:05aDec 1' THEN '9:05a'
            WHEN "scheduled_departure_time" = '9:45aDec 1' THEN '9:45a'
            WHEN "scheduled_departure_time" = '10:00aDec 1' THEN '10:00a'
            WHEN "scheduled_departure_time" = '10:15aDec 1' THEN '10:15a'
            WHEN "scheduled_departure_time" = '10:25aDec 1' THEN '10:25a'
            WHEN "scheduled_departure_time" = '10:45aDec 1' THEN '10:45a'
            WHEN "scheduled_departure_time" = '11:15aDec 1' THEN '11:15a'
            WHEN "scheduled_departure_time" = '11:35aDec 1' THEN '11:35a'
            WHEN "scheduled_departure_time" = '11:50aDec 1' THEN '11:50a'
            WHEN "scheduled_departure_time" = '11:55aDec 1' THEN '11:55a'
            WHEN "scheduled_departure_time" = '6:14aDec 1' THEN '6:14a'
            WHEN "scheduled_departure_time" = '6:40aDec 1' THEN '6:40a'
            WHEN "scheduled_departure_time" = '7:53aDec 1' THEN '7:53a'
            WHEN "scheduled_departure_time" = '7:55aDec 1' THEN '7:55a'
            WHEN "scheduled_departure_time" = '8:05aDec 1' THEN '8:05a'
            WHEN "scheduled_departure_time" = '8:15aDec 1' THEN '8:15a'
            WHEN "scheduled_departure_time" = '8:19aDec 1' THEN '8:19a'
            WHEN "scheduled_departure_time" = '8:40aDec 1' THEN '8:40a'
            WHEN "scheduled_departure_time" = '8:55aDec 1' THEN '8:55a'
            WHEN "scheduled_departure_time" = '9:15aDec 1' THEN '9:15a'
            ELSE "scheduled_departure_time"
        END AS "scheduled_departure_time",
        CASE
            WHEN "actual_departure_time" = '7:10aDec 1' THEN '7:10 a.m.'
            WHEN "actual_departure_time" = '12:41aDec 1' THEN '12:41 p.m.'
            WHEN "actual_departure_time" = 'Not Available' THEN NULL
            WHEN "actual_departure_time" = 'Contact Airline' THEN NULL
            WHEN "actual_departure_time" = '4:28 p.m. (Estimated runway)' THEN '4:28 p.m.'
            WHEN "actual_departure_time" = '7:15 p.m. (Estimated)' THEN '7:15 p.m.'
            WHEN "actual_departure_time" = '12:10 a.m. (Estimated runway)' THEN '12:10 a.m.'
            WHEN "actual_departure_time" = '1:50 p.m. (+8:00)' THEN '1:50 p.m.'
            WHEN "actual_departure_time" = '8:29 p.m. (Estimated runway)' THEN '8:29 p.m.'
            WHEN "actual_departure_time" = '9:06 p.m. (Estimated runway)' THEN '9:06 p.m.'
            WHEN "actual_departure_time" = '11:29 p.m. (Estimated runway)' THEN '11:29 p.m.'
            WHEN "actual_departure_time" = '6:47 p.m. (Estimated runway)' THEN '6:47 p.m.'
            WHEN "actual_departure_time" = '10:19aDec 1' THEN '10:19 a.m.'
            WHEN "actual_departure_time" = '11:20aDec 1' THEN '11:20 a.m.'
            WHEN "actual_departure_time" = '11:30aDec 1' THEN '11:30 a.m.'
            WHEN "actual_departure_time" = '11:47aDec 1' THEN '11:47 a.m.'
            WHEN "actual_departure_time" = '11:51aDec 1' THEN '11:51 a.m.'
            WHEN "actual_departure_time" = '11:54aDec 1' THEN '11:54 a.m.'
            WHEN "actual_departure_time" = '11:56aDec 1' THEN '11:56 a.m.'
            WHEN "actual_departure_time" = '5:30 p.m. (Estimated)' THEN '5:30 p.m.'
            WHEN "actual_departure_time" = '5:58aDec 1' THEN '5:58 a.m.'
            WHEN "actual_departure_time" = '5:59aDec 1' THEN '5:59 a.m.'
            WHEN "actual_departure_time" = '6:41aDec 1' THEN '6:41 a.m.'
            WHEN "actual_departure_time" = '6:56aDec 1' THEN '6:56 a.m.'
            WHEN "actual_departure_time" = '7:04aDec 1' THEN '7:04 a.m.'
            WHEN "actual_departure_time" = '7:07aDec 1' THEN '7:07 a.m.'
            WHEN "actual_departure_time" = '7:14aDec 1' THEN '7:14 a.m.'
            WHEN "actual_departure_time" = '7:22aDec 1' THEN '7:22 a.m.'
            WHEN "actual_departure_time" = '7:28aDec 1' THEN '7:28 a.m.'
            WHEN "actual_departure_time" = '8:31aDec 1' THEN '8:31 a.m.'
            WHEN "actual_departure_time" = '8:32aDec 1' THEN '8:32 a.m.'
            WHEN "actual_departure_time" = '8:52aDec 1' THEN '8:52 a.m.'
            WHEN "actual_departure_time" = '10:10aDec 1' THEN '10:10 a.m.'
            WHEN "actual_departure_time" = '10:20aDec 1' THEN '10:20 a.m.'
            WHEN "actual_departure_time" = '10:35aDec 1' THEN '10:35 a.m.'
            WHEN "actual_departure_time" = '10:42aDec 1' THEN '10:42 a.m.'
            WHEN "actual_departure_time" = '10:46aDec 1' THEN '10:46 a.m.'
            WHEN "actual_departure_time" = '10:47aDec 1' THEN '10:47 a.m.'
            WHEN "actual_departure_time" = '11/30/2011 11:34 p.m.' THEN '11:34 p.m.'
            WHEN "actual_departure_time" = '11:08 p.m.            On Time' THEN '11:08 p.m.'
            WHEN "actual_departure_time" = '11:15aDec 1' THEN '11:15 a.m.'
            WHEN "actual_departure_time" = '11:33aDec 1' THEN '11:33 a.m.'
            WHEN "actual_departure_time" = '11:37aDec 1' THEN '11:37 a.m.'
            WHEN "actual_departure_time" = '11:43aDec 1' THEN '11:43 a.m.'
            WHEN "actual_departure_time" = '12:30' THEN '12:30 p.m.'
            WHEN "actual_departure_time" = '12:35 p.m.            Delayed' THEN '12:35 p.m.'
            WHEN "actual_departure_time" = '1:32 p.m.            Delayed' THEN '1:32 p.m.'
            WHEN "actual_departure_time" = '1:41 p.m. (Estimated runway)' THEN '1:41 p.m.'
            WHEN "actual_departure_time" = '1:48 p.m.            Delayed' THEN '1:48 p.m.'
            WHEN "actual_departure_time" = '4:28 p.m.            Delayed' THEN '4:28 p.m.'
            WHEN "actual_departure_time" = '5:56aDec 1' THEN '5:56 a.m.'
            WHEN "actual_departure_time" = '6:02aDec 1' THEN '6:02 a.m.'
            WHEN "actual_departure_time" = '6:09aDec 1' THEN '6:09 a.m.'
            WHEN "actual_departure_time" = '6:40aDec 1' THEN '6:40 a.m.'
            WHEN "actual_departure_time" = '7:02aDec 1' THEN '7:02 a.m.'
            WHEN "actual_departure_time" = '7:05aDec 1' THEN '7:05 a.m.'
            WHEN "actual_departure_time" = '7:08aDec 1' THEN '7:08 a.m.'
            WHEN "actual_departure_time" = '7:27aDec 1' THEN '7:27 a.m.'
            WHEN "actual_departure_time" = '7:49aDec 1' THEN '7:49 a.m.'
            WHEN "actual_departure_time" = '7:51aDec 1' THEN '7:51 a.m.'
            WHEN "actual_departure_time" = '8:00aDec 1' THEN '8:00 a.m.'
            WHEN "actual_departure_time" = '8:12aDec 1' THEN '8:12 a.m.'
            WHEN "actual_departure_time" = '8:40aDec 1' THEN '8:40 a.m.'
            WHEN "actual_departure_time" = '8:48aDec 1' THEN '8:48 a.m.'
            WHEN "actual_departure_time" = '9:14aDec 1' THEN '9:14 a.m.'
            WHEN "actual_departure_time" = '9:16 a.m.            Delayed' THEN '9:16 a.m.'
            WHEN "actual_departure_time" = '9:16aDec 1' THEN '9:16 a.m.'
            WHEN "actual_departure_time" = '9:59aDec 1' THEN '9:59 a.m.'
            ELSE "actual_departure_time"
        END AS "actual_departure_time",
        CASE
            WHEN "scheduled_arrival_time" = 'Not Available' THEN NULL
            WHEN "scheduled_arrival_time" = '10:35a' THEN '10:35 a.m.'
            WHEN "scheduled_arrival_time" = '10:35aDec 1' THEN '10:35 a.m.'
            WHEN "scheduled_arrival_time" = '5:11aDec 2' THEN '5:11 a.m.'
            WHEN "scheduled_arrival_time" = '12/2/2011' THEN NULL
            WHEN "scheduled_arrival_time" = 'Dec 02' THEN NULL
            WHEN "scheduled_arrival_time" = 'Fri 02-Dec-2011' THEN NULL
            WHEN "scheduled_arrival_time" = '12:21 a.m. Dec 02' THEN '12:21 a.m.'
            WHEN "scheduled_arrival_time" = '12:29 a.m. Dec 02' THEN '12:29 a.m.'
            WHEN "scheduled_arrival_time" = '5:11 a.m.Dec 02' THEN '5:11 a.m.'
            WHEN "scheduled_arrival_time" = '12:15 a.m. Dec 02' THEN '12:15 a.m.'
            WHEN "scheduled_arrival_time" = '6:55 a.m. Dec 02' THEN '6:55 a.m.'
            WHEN "scheduled_arrival_time" = '5:50 a.m. Dec 02' THEN '5:50 a.m.'
            WHEN "scheduled_arrival_time" = '12/2/11 12:21 a.m.' THEN '12:21 a.m.'
            WHEN "scheduled_arrival_time" = '12/2/11 5:11 a.m.' THEN '5:11 a.m.'
            WHEN "scheduled_arrival_time" = '12:15 a.m.  Fri 02-Dec-2011' THEN '12:15 a.m.'
            WHEN "scheduled_arrival_time" = '12:21 a.m.  Fri 02-Dec-2011' THEN '12:21 a.m.'
            WHEN "scheduled_arrival_time" = '12:29 a.m.  Fri 02-Dec-2011' THEN '12:29 a.m.'
            WHEN "scheduled_arrival_time" = '5:50 a.m.  Fri 02-Dec-2011' THEN '5:50 a.m.'
            WHEN "scheduled_arrival_time" = '6:55 a.m.  Fri 02-Dec-2011' THEN '6:55 a.m.'
            WHEN "scheduled_arrival_time" = '10:31aDec 1' THEN '10:31 a.m.'
            WHEN "scheduled_arrival_time" = '10:34aDec 1' THEN '10:34 a.m.'
            WHEN "scheduled_arrival_time" = '10:40aDec 1' THEN '10:40 a.m.'
            WHEN "scheduled_arrival_time" = '10:45aDec 1' THEN '10:45 a.m.'
            WHEN "scheduled_arrival_time" = '11:10aDec 1' THEN '11:10 a.m.'
            WHEN "scheduled_arrival_time" = '11:19aDec 1' THEN '11:19 a.m.'
            WHEN "scheduled_arrival_time" = '11:35aDec 1' THEN '11:35 a.m.'
            WHEN "scheduled_arrival_time" = '11:50aDec 1' THEN '11:50 a.m.'
            WHEN "scheduled_arrival_time" = '11:53aDec 1' THEN '11:53 a.m.'
            WHEN "scheduled_arrival_time" = '12:29aDec 2' THEN '12:29 a.m.'
            WHEN "scheduled_arrival_time" = '5:35aDec 1' THEN '5:35 a.m.'
            WHEN "scheduled_arrival_time" = '6:55aDec 2' THEN '6:55 a.m.'
            WHEN "scheduled_arrival_time" = '7:30aDec 1' THEN '7:30 a.m.'
            WHEN "scheduled_arrival_time" = '7:45aDec 1' THEN '7:45 a.m.'
            WHEN "scheduled_arrival_time" = '8:00aDec 1' THEN '8:00 a.m.'
            WHEN "scheduled_arrival_time" = '9:20aDec 1' THEN '9:20 a.m.'
            WHEN "scheduled_arrival_time" = '9:35aDec 1' THEN '9:35 a.m.'
            WHEN "scheduled_arrival_time" = '9:54aDec 1' THEN '9:54 a.m.'
            WHEN "scheduled_arrival_time" = '9:55aDec 1' THEN '9:55 a.m.'
            WHEN "scheduled_arrival_time" = 'Dec 02 12:15 a.m.' THEN '12:15 a.m.'
            WHEN "scheduled_arrival_time" = '10:06aDec 1' THEN '10:06 a.m.'
            WHEN "scheduled_arrival_time" = '10:20aDec 1' THEN '10:20 a.m.'
            WHEN "scheduled_arrival_time" = '10:34A 12-01-11' THEN '10:34 a.m.'
            WHEN "scheduled_arrival_time" = '10:54aDec 1' THEN '10:54 a.m.'
            WHEN "scheduled_arrival_time" = '11/30 10:30 p.m.' THEN '10:30 p.m.'
            WHEN "scheduled_arrival_time" = '11/30 5:15 p.m.' THEN '5:15 p.m.'
            WHEN "scheduled_arrival_time" = '11/30 5:25 p.m.' THEN '5:25 p.m.'
            WHEN "scheduled_arrival_time" = '11/30 6:40 p.m.' THEN '6:40 p.m.'
            WHEN "scheduled_arrival_time" = '11/30 7:35 p.m.' THEN '7:35 p.m.'
            WHEN "scheduled_arrival_time" = '11/30 7:53 p.m.' THEN '7:53 p.m.'
            WHEN "scheduled_arrival_time" = '11:05aDec 1' THEN '12/01 11:05 a.m.'
            WHEN "scheduled_arrival_time" = '11:10A 12-01-11' THEN '12/01 11:10 a.m.'
            WHEN "scheduled_arrival_time" = '11:55aDec 1' THEN '12/01 11:55 a.m.'
            WHEN "scheduled_arrival_time" = '12/02/2011 12:15 a.m.' THEN '12/02 12:15 a.m.'
            WHEN "scheduled_arrival_time" = '12/02/2011 5:50 a.m.' THEN '12/02 5:50 a.m.'
            WHEN "scheduled_arrival_time" = '12/02/2011 6:55 a.m.' THEN '12/02 6:55 a.m.'
            WHEN "scheduled_arrival_time" = '12/2/2011 12:15 a.m.' THEN '12/02 12:15 a.m.'
            WHEN "scheduled_arrival_time" = '12/2/2011 12:29 a.m.' THEN '12/02 12:29 a.m.'
            WHEN "scheduled_arrival_time" = '12/2/2011 5:50 a.m.' THEN '12/02 5:50 a.m.'
            WHEN "scheduled_arrival_time" = '12/2/2011 6:55 a.m.' THEN '12/02 6:55 a.m.'
            WHEN "scheduled_arrival_time" = '12:15aDec 2' THEN '12/02 12:15 a.m.'
            WHEN "scheduled_arrival_time" = '12:21aDec 2' THEN '12/02 12:21 a.m.'
            WHEN "scheduled_arrival_time" = '2:45P 12-01-11' THEN '12/01 2:45 p.m.'
            WHEN "scheduled_arrival_time" = '5:50 a.m.Dec 02' THEN '12/02 5:50 a.m.'
            WHEN "scheduled_arrival_time" = '5:50aDec 2' THEN '12/02 5:50 a.m.'
            WHEN "scheduled_arrival_time" = '6:40aDec 1' THEN '12/01 6:40 a.m.'
            WHEN "scheduled_arrival_time" = '7:23aDec 1' THEN '12/01 7:23 a.m.'
            WHEN "scheduled_arrival_time" = '7:55P 12-01-11' THEN '12/01 7:55 p.m.'
            WHEN "scheduled_arrival_time" = '8:27aDec 1' THEN '12/01 8:27 a.m.'
            WHEN "scheduled_arrival_time" = '9:20A 12-01-11' THEN '12/01 9:20 a.m.'
            WHEN "scheduled_arrival_time" = '9:21aDec 2' THEN '12/02 9:21 a.m.'
            WHEN "scheduled_arrival_time" = '9:25aDec 1' THEN '12/01 9:25 a.m.'
            WHEN "scheduled_arrival_time" = '9:40aDec 1' THEN '12/01 9:40 a.m.'
            WHEN "scheduled_arrival_time" = '9:43aDec 1' THEN '12/01 9:43 a.m.'
            WHEN "scheduled_arrival_time" = 'Dec 02 12:21 a.m.' THEN '12/02 12:21 a.m.'
            WHEN "scheduled_arrival_time" = 'Dec 02 5:50 a.m.' THEN '12/02 5:50 a.m.'
            WHEN "scheduled_arrival_time" = 'Dec 02 6:55 a.m.' THEN '12/02 6:55 a.m.'
            WHEN "scheduled_arrival_time" = 'Fri Dec 2 12:29 a.m.' THEN '12/02 12:29 a.m.'
            WHEN "scheduled_arrival_time" = 'Fri Dec 2 5:11 a.m.' THEN '12/02 5:11 a.m.'
            WHEN "scheduled_arrival_time" = 'Thu  10:35' THEN '10:35 a.m.'
            WHEN "scheduled_arrival_time" = 'Thu  12:18' THEN '12:18 p.m.'
            WHEN "scheduled_arrival_time" = 'Thu  17:55' THEN '5:55 p.m.'
            WHEN "scheduled_arrival_time" = 'Thu  19:25' THEN '7:25 p.m.'
            WHEN "scheduled_arrival_time" = 'Thu  22:15' THEN '10:15 p.m.'
            WHEN "scheduled_arrival_time" = 'Thu  6:55' THEN '6:55 a.m.'
            WHEN "scheduled_arrival_time" = 'Thu  7:45' THEN '7:45 a.m.'
            ELSE "scheduled_arrival_time"
        END AS "scheduled_arrival_time",
        CASE
            WHEN "actual_arrival_time" = '10:08A' THEN '10:08 a.m.'
            WHEN "actual_arrival_time" = '11:06aDec 1' THEN '11:06 a.m.'
            WHEN "actual_arrival_time" = '10:39 p.m.&nbsp(Estimated)' THEN '10:39 p.m.'
            WHEN "actual_arrival_time" = '3:21PM' THEN '3:21 p.m.'
            WHEN "actual_arrival_time" = '9:14AM' THEN '9:14 a.m.'
            WHEN "actual_arrival_time" = '8:45 AM' THEN '8:45 a.m.'
            WHEN "actual_arrival_time" = '11:32am' THEN '11:32 a.m.'
            WHEN "actual_arrival_time" = '2:10pm' THEN '2:10 p.m.'
            WHEN "actual_arrival_time" = '5:26AM' THEN '5:26 a.m.'
            WHEN "actual_arrival_time" = '12:01 a.m. (Estimated runway)' THEN '12:01 a.m.'
            WHEN "actual_arrival_time" = '12:21 a.m. (Estimated)' THEN '12:21 a.m.'
            WHEN "actual_arrival_time" = '10:30 p.m. (Estimated)' THEN '10:30 p.m.'
            WHEN "actual_arrival_time" = '11:35 p.m. (Estimated runway)' THEN '11:35 p.m.'
            WHEN "actual_arrival_time" = '11:49 p.m. (Estimated runway)' THEN '11:49 p.m.'
            WHEN "actual_arrival_time" = '12/2/11 12:01 a.m.' THEN '12:01 a.m.'
            WHEN "actual_arrival_time" = '12/2/11 6:35 a.m.' THEN '6:35 a.m.'
            WHEN "actual_arrival_time" = '5:42 a.m. (Estimated runway)' THEN '5:42 a.m.'
            WHEN "actual_arrival_time" = '9:19 p.m. (Estimated)' THEN '9:19 p.m.'
            WHEN "actual_arrival_time" = 'Dec 02 Not Available' THEN NULL
            WHEN "actual_arrival_time" = '3:20 p.m. (Runway)' THEN '3:20 p.m.'
            WHEN "actual_arrival_time" = '3:20 p.m. (runway)' THEN '3:20 p.m.'
            WHEN "actual_arrival_time" = '6:35 a.m. (Estimated runway)' THEN '6:35 a.m.'
            WHEN "actual_arrival_time" = '7:25 p.m. (Estimated runway)' THEN '7:25 p.m.'
            WHEN "actual_arrival_time" = '10:04aDec 1' THEN '10:04 a.m.'
            WHEN "actual_arrival_time" = '10:16aDec 1' THEN '10:16 a.m.'
            WHEN "actual_arrival_time" = '10:47aDec 1' THEN '10:47 a.m.'
            WHEN "actual_arrival_time" = '11:12aDec 1' THEN '11:12 a.m.'
            WHEN "actual_arrival_time" = '11:44aDec 1' THEN '11:44 a.m.'
            WHEN "actual_arrival_time" = '5:26aDec 1' THEN '5:26 a.m.'
            WHEN "actual_arrival_time" = '6:40 p.m. (Estimated)' THEN '6:40 p.m.'
            WHEN "actual_arrival_time" = '7:40aDec 1' THEN '7:40 a.m.'
            WHEN "actual_arrival_time" = '7:51aDec 1' THEN '7:51 a.m.'
            WHEN "actual_arrival_time" = '8:06aDec 1' THEN '8:06 a.m.'
            WHEN "actual_arrival_time" = '9:05aDec 1' THEN '9:05 a.m.'
            WHEN "actual_arrival_time" = '9:31aDec 1' THEN '9:31 a.m.'
            WHEN "actual_arrival_time" = '9:45aDec 1' THEN '9:45 a.m.'
            WHEN "actual_arrival_time" = '9:52 p.m. (Estimated)' THEN '9:52 p.m.'
            WHEN "actual_arrival_time" = '10:27aDec 1' THEN '10:27 a.m.'
            WHEN "actual_arrival_time" = '10:30 p.m.*' THEN '10:30 p.m.'
            WHEN "actual_arrival_time" = '10:36aDec 1' THEN '10:36 a.m.'
            WHEN "actual_arrival_time" = '10:56aDec 1' THEN '10:56 a.m.'
            WHEN "actual_arrival_time" = '11:01aDec 1' THEN '11:01 a.m.'
            WHEN "actual_arrival_time" = '11:06A' THEN '11:06 a.m.'
            WHEN "actual_arrival_time" = '11:32aDec 1' THEN '11:32 a.m.'
            WHEN "actual_arrival_time" = '11:56aDec 1' THEN '11:56 a.m.'
            WHEN "actual_arrival_time" = '11:58aDec 1' THEN '11:58 a.m.'
            WHEN "actual_arrival_time" = '2:46P' THEN '2:46 p.m.'
            WHEN "actual_arrival_time" = '3:29 p.m. (Estimated runway)' THEN '3:29 p.m.'
            WHEN "actual_arrival_time" = '6:19aDec 1' THEN '6:19 a.m.'
            WHEN "actual_arrival_time" = '7:17aDec 1' THEN '7:17A'
            WHEN "actual_arrival_time" = '7:39P' THEN '7:39 p.m.'
            WHEN "actual_arrival_time" = '8:02aDec 1' THEN '8:02A'
            WHEN "actual_arrival_time" = '8:45aDec 1' THEN '8:45A'
            WHEN "actual_arrival_time" = '9:04A' THEN '9:04 a.m.'
            WHEN "actual_arrival_time" = '9:19 p.m.*' THEN '9:19 p.m.'
            WHEN "actual_arrival_time" = '9:28aDec 1' THEN '9:28A'
            WHEN "actual_arrival_time" = '9:32aDec 1' THEN '9:32A'
            WHEN "actual_arrival_time" = '9:56aDec 1' THEN '9:56A'
            WHEN "actual_arrival_time" = 'Dec 02 Contact Airline' THEN NULL
            WHEN "actual_arrival_time" = 'Fri Dec 2 12:29 a.m.' THEN '12:29 a.m.'
            WHEN "actual_arrival_time" = 'Fri Dec 2 5:11 a.m.' THEN '5:11 a.m.'
            WHEN "actual_arrival_time" = 'Thu  10:28' THEN '10:28 a.m.'
            WHEN "actual_arrival_time" = 'Thu  17:40' THEN '5:40 p.m.'
            WHEN "actual_arrival_time" = 'Thu  19:33' THEN '7:33 p.m.'
            WHEN "actual_arrival_time" = 'Thu  22:25' THEN '10:25 p.m.'
            WHEN "actual_arrival_time" = 'Thu  6:50' THEN '6:50 a.m.'
            WHEN "actual_arrival_time" = 'Thu  7:31' THEN '7:31 a.m.'
            ELSE "actual_arrival_time"
        END AS "actual_arrival_time"
    FROM "flights_renamed"
),

"flights_renamed_cleaned_fd" AS (
    -- FD: functional dependency
    -- flight_code -> scheduled_departure_time, scheduled_arrival_time
    SELECT
        flight_id,
        airline_code,
        flight_code,
        CASE
            WHEN flight_code = 'AA-518-MIA-JFK' THEN '6:40 a.m.'
            WHEN flight_code = 'AA-4344-ORD-DTW' THEN '11:45 a.m.'
            WHEN flight_code = 'AA-1434-DFW-MCO' THEN '7:15 a.m.'
            WHEN flight_code = 'AA-4277-CVG-JFK' THEN '12:10 p.m.'
            WHEN flight_code = 'AA-415-BOS-ORD' THEN '8:35 a.m.'
            WHEN flight_code = 'AA-222-LAX-BOS' THEN '7:10 a.m.'
            WHEN flight_code = 'AA-3809-PHX-LAX' THEN '6:00 a.m.'
            WHEN flight_code = 'AA-59-JFK-SFO' THEN '7:10 a.m.'
            WHEN flight_code = 'UA-397-JFK-SFO' THEN '8:00 a.m.'
            WHEN flight_code = 'CO-52-IAH-LAX' THEN '7:35 a.m.'
            WHEN flight_code = 'UA-2314-ATL-PHL' THEN '2:55 p.m.'
            WHEN flight_code = 'UA-854-SFO-IAH' THEN '7:53 a.m.'
            WHEN flight_code = 'UA-2945-PHL-CLT' THEN '12:00 p.m.'
            WHEN flight_code = 'UA-3373-IAD-PHL' THEN '8:29 a.m.'
            WHEN flight_code = 'CO-4888-IAH-DAL' THEN '5:30 p.m.'
            WHEN flight_code = 'UA-2704-DTW-PHX' THEN '11:15 a.m.'
            WHEN flight_code = 'AA-3859-IAH-ORD' THEN '7:10 a.m.'
            WHEN flight_code = 'AA-3756-ORD-SLC' THEN '12:15 p.m.'
            WHEN flight_code = 'AA-204-LAX-MCO' THEN '11:25 p.m.'
            WHEN flight_code = 'AA-616-DFW-DTW' THEN '9:05 a.m.'
            WHEN flight_code = 'AA-400-DFW-JFK' THEN '10:40 a.m.'
            WHEN flight_code = 'AA-4198-ORD-CLE' THEN '10:40 a.m.'
            WHEN flight_code = 'AA-1522-SFO-ORD' THEN '11:55 p.m.'
            WHEN flight_code = 'AA-431-MIA-SFO' THEN '8:35 a.m.'
            WHEN flight_code = 'AA-3063-SLC-LAX' THEN '8:20 p.m.'
            WHEN flight_code = 'AA-1544-SAN-ORD' THEN '11:25 a.m.'
            WHEN flight_code = 'AA-3786-IAH-ORD' THEN '4:00 p.m.'
            WHEN flight_code = 'CO-1586-IAH-MCO' THEN '7:00 p.m.'
            WHEN flight_code = 'UA-3925-IAD-ORF' THEN '8:41 a.m.'
            WHEN flight_code = 'UA-2830-MCO-CLT' THEN '3:27 p.m.'
            WHEN flight_code = 'CO-58-DEN-IAH' THEN '11:25 a.m.'
            WHEN flight_code = 'UA-3515-IAD-MSP' THEN '8:15 a.m.'
            WHEN flight_code = 'CO-1561-PHX-IAH' THEN '8:05 a.m.'
            WHEN flight_code = 'UA-3050-PHX-CLT' THEN '11:05 a.m.'
            WHEN flight_code = 'CO-89-IAH-EWR' THEN '6:00 a.m.'
            WHEN flight_code = 'UA-248-PHX-ORD' THEN '12:57 p.m.'
            WHEN flight_code = 'UA-843-LAX-ORD' THEN '1:55 p.m.'
            WHEN flight_code = 'UA-938-DEN-ORD' THEN '4:16 p.m.'
            WHEN flight_code = 'UA-2515-DFW-CLT' THEN '7:05 a.m.'
            WHEN flight_code = 'UA-62-IAH-EWR' THEN '2:30 p.m.'
            WHEN flight_code = 'UA-3099-PHX-PHL' THEN '11:55 a.m.'
            WHEN flight_code = 'AA-1640-MIA-MCO' THEN '6:30 p.m.'
            WHEN flight_code = 'AA-484-DFW-MIA' THEN '4:15 p.m.'
            WHEN flight_code = 'AA-446-DFW-PHL' THEN '11:50 a.m.'
            WHEN flight_code = 'AA-466-IAH-MIA' THEN '6:00 a.m.'
            WHEN flight_code = 'AA-2957-DFW-CVG' THEN '7:55 a.m.'
            WHEN flight_code = 'AA-1664-MIA-ATL' THEN '10:15 a.m.'
            WHEN flight_code = 'AA-1279-DFW-PHX' THEN '1:00 p.m.'
            WHEN flight_code = 'AA-2525-DFW-MIA' THEN '7:25 a.m.'
            WHEN flight_code = 'AA-271-MIA-LAX' THEN '11:35 a.m.'
            WHEN flight_code = 'AA-2050-ORD-MIA' THEN '10:40 a.m.'
            WHEN flight_code = 'AA-4307-ORD-DTW' THEN '6:45 p.m.'
            WHEN flight_code = 'AA-3-JFK-LAX' THEN '12:00 p.m.'
            WHEN flight_code = 'AA-3842-MSP-ORD' THEN '6:00 a.m.'
            WHEN flight_code = 'AA-643-MIA-ORD' THEN '7:10 a.m.'
            WHEN flight_code = 'AA-3823-LAX-DEN' THEN '9:00 p.m.'
            WHEN flight_code = 'AA-2312-DFW-DTW' THEN '8:25 p.m.'
            WHEN flight_code = 'AA-1917-JFK-MCO' THEN '2:55 p.m.'
            WHEN flight_code = 'AA-85-JFK-SFO' THEN '3:05 p.m.'
            WHEN flight_code = 'UA-5487-SFO-MRY' THEN '10:39 a.m.'
            WHEN flight_code = 'UA-414-LAX-SFO' THEN '6:00 a.m.'
            WHEN flight_code = 'UA-2726-FLL-PHL' THEN '4:00 p.m.'
            WHEN flight_code = 'CO-62-IAH-EWR' THEN '2:30 p.m.'
            WHEN flight_code = 'UA-382-IAD-LAX' THEN '12:30 p.m.'
            WHEN flight_code = 'CO-63-EWR-IAH' THEN '5:25 p.m.'
            WHEN flight_code = 'UA-664-ORD-PHL' THEN '1:33 p.m.'
            WHEN flight_code = 'CO-1250-MIA-IAH' THEN '2:53 p.m.'
            WHEN flight_code = 'UA-6273-YYC-SFO' THEN '7:35 a.m.'
            WHEN flight_code = 'UA-858-PVG-SFO' THEN '1:45 p.m.'
            WHEN flight_code = 'UA-37-EDI-EWR' THEN '9:05 a.m.'
            WHEN flight_code = 'CO-50-CLE-EWR' THEN '2:55 p.m.'
            WHEN flight_code = 'AA-1733-ORD-PHX' THEN '7:45 p.m.'
            WHEN flight_code = 'AA-3468-CVG-MIA' THEN '7:00 a.m.'
            WHEN flight_code = 'AA-1886-BOS-MIA' THEN '10:45 a.m.'
            WHEN flight_code = 'AA-3979-CVG-ORD' THEN '7:30 a.m.'
            WHEN flight_code = 'AA-404-MIA-MCO' THEN '6:45 a.m.'
            WHEN flight_code = 'AA-4330-CVG-ORD' THEN '3:35 p.m.'
            WHEN flight_code = 'AA-1007-MIA-PHX' THEN '4:55 p.m.'
            WHEN flight_code = 'AA-1221-MCO-ORD' THEN '8:00 p.m.'
            WHEN flight_code = 'AA-1165-JFK-MIA' THEN '6:59 a.m.'
            WHEN flight_code = 'AA-649-ORD-SNA' THEN '1:30 p.m.'
            WHEN flight_code = 'AA-3804-PHL-ORD' THEN '2:35 p.m.'
            WHEN flight_code = 'AA-2268-PHX-ORD' THEN '7:15 a.m.'
            WHEN flight_code = 'AA-789-ORD-DEN' THEN '1:05 p.m.'
            WHEN flight_code = 'CO-1614-LAX-IAH' THEN '12:30 a.m.'
            WHEN flight_code = 'CO-1090-BOS-IAH' THEN '9:45 a.m.'
            WHEN flight_code = 'CO-1023-IAH-DEN' THEN '11:40 a.m.'
            WHEN flight_code = 'CO-1088-CLE-IAH' THEN '8:40 a.m.'
            WHEN flight_code = 'UA-257-JFK-SFO' THEN '2:30 p.m.'
            WHEN flight_code = 'CO-47-IAH-LAX' THEN '7:10 p.m.'
            WHEN flight_code = 'CO-1193-EWR-MCO' THEN '9:15 a.m.'
            WHEN flight_code = 'UA-2906-PHL-MCO' THEN '3:50 p.m.'
            WHEN flight_code = 'CO-16-LAX-EWR' THEN '10:25 a.m.'
            WHEN flight_code = 'UA-37-EWR-MCO' THEN '1:29 p.m.'
            WHEN flight_code = 'UA-233-LAX-JFK' THEN '4:25 p.m.'
            WHEN flight_code = 'UA-828-SFO-ORD' THEN '11:08 p.m.'
            WHEN flight_code = 'UA-2708-EWR-CLT' THEN '2:55 p.m.'
            WHEN flight_code = 'UA-1500-IAH-GUA' THEN '8:55 a.m.'
            ELSE scheduled_departure_time
        END AS scheduled_departure_time,
        actual_departure_time,
        CASE
            WHEN flight_code = 'AA-1640-MIA-MCO' THEN '7:25 p.m.'
            WHEN flight_code = 'AA-484-DFW-MIA' THEN '7:55 p.m.'
            WHEN flight_code = 'AA-446-DFW-PHL' THEN '3:50 p.m.'
            WHEN flight_code = 'AA-466-IAH-MIA' THEN '9:20 a.m.'
            WHEN flight_code = 'AA-2957-DFW-CVG' THEN '11:05 a.m.'
            WHEN flight_code = 'AA-1664-MIA-ATL' THEN '12:10 p.m.'
            WHEN flight_code = 'AA-1279-DFW-PHX' THEN '2:35 p.m.'
            WHEN flight_code = 'AA-2525-DFW-MIA' THEN '11:10 a.m.'
            WHEN flight_code = 'AA-271-MIA-LAX' THEN '2:25 p.m.'
            WHEN flight_code = 'AA-2050-ORD-MIA' THEN '2:45 p.m.'
            WHEN flight_code = 'AA-4307-ORD-DTW' THEN '9:10 p.m.'
            WHEN flight_code = 'AA-3-JFK-LAX' THEN '3:15 p.m.'
            WHEN flight_code = 'AA-3842-MSP-ORD' THEN '7:30 a.m.'
            WHEN flight_code = 'AA-643-MIA-ORD' THEN '9:35 a.m.'
            WHEN flight_code = 'AA-3823-LAX-DEN' THEN '12:15 a.m.'
            WHEN flight_code = 'AA-2312-DFW-DTW' THEN '11:50 p.m.'
            WHEN flight_code = 'AA-1917-JFK-MCO' THEN '5:55 p.m.'
            WHEN flight_code = 'AA-85-JFK-SFO' THEN '6:30 p.m.'
            WHEN flight_code = 'UA-5487-SFO-MRY' THEN '11:19 a.m.'
            WHEN flight_code = 'UA-414-LAX-SFO' THEN '7:23 a.m.'
            WHEN flight_code = 'UA-2726-FLL-PHL' THEN '6:46 p.m.'
            WHEN flight_code = 'CO-62-IAH-EWR' THEN '7:03 p.m.'
            WHEN flight_code = 'UA-382-IAD-LAX' THEN '3:19 p.m.'
            WHEN flight_code = 'CO-63-EWR-IAH' THEN '8:22 p.m.'
            WHEN flight_code = 'CO-1694-LAX-IAH' THEN '12:21 a.m.'
            WHEN flight_code = 'UA-664-ORD-PHL' THEN '4:31 p.m.'
            WHEN flight_code = 'CO-1250-MIA-IAH' THEN '4:48 p.m.'
            WHEN flight_code = 'UA-6273-YYC-SFO' THEN '9:43 a.m.'
            WHEN flight_code = 'UA-858-PVG-SFO' THEN '8:27 a.m.'
            WHEN flight_code = 'UA-37-EDI-EWR' THEN '11:53 a.m.'
            WHEN flight_code = 'CO-50-CLE-EWR' THEN '4:49 p.m.'
            WHEN flight_code = 'AA-3859-IAH-ORD' THEN '9:40 a.m.'
            WHEN flight_code = 'AA-3756-ORD-SLC' THEN '2:45 p.m.'
            WHEN flight_code = 'AA-204-LAX-MCO' THEN '6:55 a.m.'
            WHEN flight_code = 'AA-616-DFW-DTW' THEN '12:35 p.m.'
            WHEN flight_code = 'AA-400-DFW-JFK' THEN '2:59 p.m.'
            WHEN flight_code = 'AA-4198-ORD-CLE' THEN '12:55 p.m.'
            WHEN flight_code = 'AA-1522-SFO-ORD' THEN '5:50 a.m.'
            WHEN flight_code = 'AA-431-MIA-SFO' THEN '11:50 a.m.'
            WHEN flight_code = 'AA-3063-SLC-LAX' THEN '9:20 p.m.'
            WHEN flight_code = 'AA-1544-SAN-ORD' THEN '5:25 p.m.'
            WHEN flight_code = 'AA-3786-IAH-ORD' THEN '6:40 p.m.'
            WHEN flight_code = 'CO-1586-IAH-MCO' THEN '10:15 p.m.'
            WHEN flight_code = 'UA-3925-IAD-ORF' THEN '9:54 a.m.'
            WHEN flight_code = 'UA-2830-MCO-CLT' THEN '5:05 p.m.'
            WHEN flight_code = 'CO-58-DEN-IAH' THEN '2:50 p.m.'
            WHEN flight_code = 'UA-3515-IAD-MSP' THEN '10:06 a.m.'
            WHEN flight_code = 'CO-1561-PHX-IAH' THEN '11:35 a.m.'
            WHEN flight_code = 'UA-3050-PHX-CLT' THEN '4:57 p.m.'
            WHEN flight_code = 'CO-89-IAH-EWR' THEN '10:20 a.m.'
            WHEN flight_code = 'UA-248-PHX-ORD' THEN '5:15 p.m.'
            WHEN flight_code = 'UA-843-LAX-ORD' THEN '7:53 p.m.'
            WHEN flight_code = 'UA-938-DEN-ORD' THEN '7:35 p.m.'
            WHEN flight_code = 'UA-2515-DFW-CLT' THEN '10:31 a.m.'
            WHEN flight_code = 'UA-62-IAH-EWR' THEN '7:03 p.m.'
            WHEN flight_code = 'UA-3099-PHX-PHL' THEN '6:17 p.m.'
            WHEN flight_code = 'AA-518-MIA-JFK' THEN '9:25 a.m.'
            WHEN flight_code = 'AA-4344-ORD-DTW' THEN '2:00 p.m.'
            WHEN flight_code = 'AA-1434-DFW-MCO' THEN '10:35 a.m.'
            WHEN flight_code = 'AA-4277-CVG-JFK' THEN '2:15 p.m.'
            WHEN flight_code = 'AA-415-BOS-ORD' THEN '10:40 a.m.'
            WHEN flight_code = 'AA-222-LAX-BOS' THEN '3:30 p.m.'
            WHEN flight_code = 'AA-3809-PHX-LAX' THEN '6:40 a.m.'
            WHEN flight_code = 'AA-59-JFK-SFO' THEN '10:45 a.m.'
            WHEN flight_code = 'UA-397-JFK-SFO' THEN '11:55 a.m.'
            WHEN flight_code = 'CO-52-IAH-LAX' THEN '9:21 a.m.'
            WHEN flight_code = 'UA-2314-ATL-PHL' THEN '5:00 p.m.'
            WHEN flight_code = 'UA-854-SFO-IAH' THEN '1:39 p.m.'
            WHEN flight_code = 'UA-2945-PHL-CLT' THEN '1:45 p.m.'
            WHEN flight_code = 'UA-3373-IAD-PHL' THEN '9:24 a.m.'
            WHEN flight_code = 'CO-4888-IAH-DAL' THEN '6:40 p.m.'
            WHEN flight_code = 'UA-2704-DTW-PHX' THEN '1:40 p.m.'
            WHEN flight_code = 'AA-1733-ORD-PHX' THEN '10:30 p.m.'
            WHEN flight_code = 'AA-3468-CVG-MIA' THEN '9:55 a.m.'
            WHEN flight_code = 'AA-1886-BOS-MIA' THEN '2:20 p.m.'
            WHEN flight_code = 'AA-3979-CVG-ORD' THEN '8:00 a.m.'
            WHEN flight_code = 'AA-404-MIA-MCO' THEN '7:45 a.m.'
            WHEN flight_code = 'AA-4330-CVG-ORD' THEN '4:00 p.m.'
            WHEN flight_code = 'AA-1007-MIA-PHX' THEN '8:05 p.m.'
            WHEN flight_code = 'AA-1221-MCO-ORD' THEN '9:45 p.m.'
            WHEN flight_code = 'AA-1165-JFK-MIA' THEN '10:34 a.m.'
            WHEN flight_code = 'AA-649-ORD-SNA' THEN '3:50 p.m.'
            WHEN flight_code = 'AA-3804-PHL-ORD' THEN '4:05 p.m.'
            WHEN flight_code = 'AA-2268-PHX-ORD' THEN '11:35 a.m.'
            WHEN flight_code = 'AA-789-ORD-DEN' THEN '2:35 p.m.'
            WHEN flight_code = 'CO-1614-LAX-IAH' THEN '5:35 a.m.'
            WHEN flight_code = 'CO-1090-BOS-IAH' THEN '1:16 p.m.'
            WHEN flight_code = 'CO-1023-IAH-DEN' THEN '1:17 p.m.'
            WHEN flight_code = 'CO-1088-CLE-IAH' THEN '10:54 a.m.'
            WHEN flight_code = 'UA-257-JFK-SFO' THEN '6:15 p.m.'
            WHEN flight_code = 'CO-47-IAH-LAX' THEN '8:56 p.m.'
            WHEN flight_code = 'CO-1193-EWR-MCO' THEN '12:18 p.m.'
            WHEN flight_code = 'UA-2906-PHL-MCO' THEN '6:23 p.m.'
            WHEN flight_code = 'CO-16-LAX-EWR' THEN '6:44 p.m.'
            WHEN flight_code = 'UA-37-EWR-MCO' THEN '4:17 p.m.'
            WHEN flight_code = 'UA-233-LAX-JFK' THEN '12:29 a.m.'
            WHEN flight_code = 'UA-828-SFO-ORD' THEN '5:11 a.m.'
            WHEN flight_code = 'UA-2708-EWR-CLT' THEN '4:53 p.m.'
            WHEN flight_code = 'UA-1500-IAH-GUA' THEN '11:45 a.m.'
            WHEN flight_code = 'CO-45-EWR-MIA' THEN '7:05 p.m.'
            ELSE scheduled_arrival_time
        END AS scheduled_arrival_time,
        actual_arrival_time
    FROM "flights_renamed_cleaned"
),

"flights_renamed_cleaned_fd_fd" AS (
    -- FD: functional dependency
    -- scheduled_departure_time -> flight_code, scheduled_arrival_time
    SELECT
        flight_id,
        airline_code,
        CASE
            WHEN scheduled_departure_time = '12:00 p.m.' THEN 'AA-3-JFK-LAX'
            WHEN scheduled_departure_time = '4:00 p.m.' THEN 'AA-3786-IAH-ORD'
            WHEN scheduled_departure_time = '10:40 a.m.' THEN 'AA-2050-ORD-MIA'
            WHEN scheduled_departure_time = '8:35 a.m.' THEN 'AA-431-MIA-SFO'
            WHEN scheduled_departure_time = '11:25 a.m.' THEN 'AA-1544-SAN-ORD'
            WHEN scheduled_departure_time = '6:00 a.m.' THEN 'AA-466-IAH-MIA'
            WHEN scheduled_departure_time = '9:05 a.m.' THEN 'AA-616-DFW-DTW'
            WHEN scheduled_departure_time = '7:15 a.m.' THEN 'AA-1434-DFW-MCO'
            WHEN scheduled_departure_time = '7:35 a.m.' THEN 'UA-6273-YYC-SFO'
            WHEN scheduled_departure_time = '7:10 a.m.' THEN 'AA-59-JFK-SFO'
            WHEN scheduled_departure_time = '2:55 p.m.' THEN 'AA-1917-JFK-MCO'
            WHEN scheduled_departure_time = '2:30 p.m.' THEN 'UA-257-JFK-SFO'
            ELSE flight_code
        END AS flight_code,
        scheduled_departure_time,
        actual_departure_time,
        CASE
            WHEN scheduled_departure_time = '6:00 a.m.' THEN '9:20 a.m.'
            WHEN scheduled_departure_time = '9:05 a.m.' THEN '12:35 p.m.'
            WHEN scheduled_departure_time = '7:15 a.m.' THEN '10:35 a.m.'
            WHEN scheduled_departure_time = '7:35 a.m.' THEN '9:43 a.m.'
            WHEN scheduled_departure_time = '10:40 a.m.' THEN '2:45 p.m.'
            WHEN scheduled_departure_time = '8:35 a.m.' THEN '11:50 a.m.'
            WHEN scheduled_departure_time = '11:25 a.m.' THEN '5:25 p.m.'
            WHEN scheduled_departure_time = '12:00 p.m.' THEN '3:15 p.m.'
            WHEN scheduled_departure_time = '4:00 p.m.' THEN '6:40 p.m.'
            WHEN scheduled_departure_time = '7:10 a.m.' THEN '10:45 a.m.'
            WHEN scheduled_departure_time = '2:55 p.m.' THEN '5:55 p.m.'
            WHEN scheduled_departure_time = '2:30 p.m.' THEN '7:03 p.m.'
            ELSE scheduled_arrival_time
        END AS scheduled_arrival_time,
        actual_arrival_time
    FROM "flights_renamed_cleaned_fd"
),

"flights_renamed_cleaned_fd_fd_fd" AS (
    -- FD: functional dependency
    -- actual_departure_time -> airline_code, flight_code, scheduled_departure_time, scheduled_arrival_time
    SELECT
        flight_id,
        CASE
            WHEN actual_departure_time = '7:58 p.m.' THEN 'AA'
            WHEN actual_departure_time = '6:54 a.m.' THEN 'AA'
            WHEN actual_departure_time = '6:08 a.m.' THEN 'AA'
            WHEN actual_departure_time = '8:04 a.m.' THEN 'AA'
            WHEN actual_departure_time = '10:10 a.m.' THEN 'AA'
            WHEN actual_departure_time = '3:36 p.m.' THEN 'AA'
            WHEN actual_departure_time = '8:23 p.m.' THEN 'AA'
            WHEN actual_departure_time = '11:01 a.m.' THEN 'AA'
            WHEN actual_departure_time = '8:39 p.m.' THEN 'AA'
            WHEN actual_departure_time = '1:19 p.m.' THEN 'AA'
            WHEN actual_departure_time = '4:12 p.m.' THEN 'AA'
            WHEN actual_departure_time = '7:59 p.m.' THEN 'G4'
            WHEN actual_departure_time = '10:53 a.m.' THEN 'G4'
            WHEN actual_departure_time = '8:26 a.m.' THEN 'UA'
            WHEN actual_departure_time = '6:09 a.m.' THEN 'G4'
            WHEN actual_departure_time = '11:45 a.m.' THEN 'G4'
            WHEN actual_departure_time = '12:56 p.m.' THEN 'G4'
            WHEN actual_departure_time = '11:06 a.m.' THEN 'G4'
            WHEN actual_departure_time = '6:56 p.m.' THEN 'G4'
            WHEN actual_departure_time = '5:38 p.m.' THEN 'G4'
            WHEN actual_departure_time = '3:38 p.m.' THEN 'G4'
            WHEN actual_departure_time = '11:55 a.m.' THEN 'UA'
            WHEN actual_departure_time = '6:11 a.m.' THEN 'G4'
            WHEN actual_departure_time = '8:49 a.m.' THEN 'G4'
            WHEN actual_departure_time = '12:58 a.m.' THEN 'G4'
            WHEN actual_departure_time = '7:56 a.m.' THEN 'G4'
            WHEN actual_departure_time = '4:30 p.m.' THEN 'G4'
            WHEN actual_departure_time = '8:18 a.m.' THEN 'G4'
            WHEN actual_departure_time = '9:58 a.m.' THEN 'G4'
            WHEN actual_departure_time = '4:46 p.m.' THEN 'G4'
            WHEN actual_departure_time = '2:01 p.m.' THEN 'G4'
            WHEN actual_departure_time = '9:05 a.m.' THEN 'G4'
            WHEN actual_departure_time = '7:14 p.m.' THEN 'CO'
            WHEN actual_departure_time = '8:29 a.m.' THEN 'UA'
            WHEN actual_departure_time = '2:48 p.m.' THEN 'CO'
            WHEN actual_departure_time = '8:40 a.m.' THEN 'CO'
            WHEN actual_departure_time = '8:25 p.m.' THEN 'CO'
            WHEN actual_departure_time = '9:14 a.m.' THEN 'CO'
            WHEN actual_departure_time = '10:20 a.m.' THEN 'CO'
            WHEN actual_departure_time = '2:26 p.m.' THEN 'UA'
            WHEN actual_departure_time = '10:33 a.m.' THEN 'UA'
            WHEN actual_departure_time = '9:16 a.m.' THEN 'UA'
            WHEN actual_departure_time = '7:16 a.m.' THEN 'AA'
            WHEN actual_departure_time = '7:25 a.m.' THEN 'AA'
            WHEN actual_departure_time = '12:12 p.m.' THEN 'AA'
            WHEN actual_departure_time = '10:55 a.m.' THEN 'G4'
            WHEN actual_departure_time = '12:13 p.m.' THEN 'AA'
            WHEN actual_departure_time = '6:57 a.m.' THEN 'AA'
            WHEN actual_departure_time = '11:52 a.m.' THEN 'AA'
            WHEN actual_departure_time = '11:05 a.m.' THEN 'AA'
            WHEN actual_departure_time = '12:11 p.m.' THEN 'AA'
            WHEN actual_departure_time = '6:56 a.m.' THEN 'AA'
            WHEN actual_departure_time = '5:08 p.m.' THEN 'AA'
            WHEN actual_departure_time = '2:44 p.m.' THEN 'AA'
            WHEN actual_departure_time = '11:40 a.m.' THEN 'AA'
            WHEN actual_departure_time = '6:10 a.m.' THEN 'AA'
            WHEN actual_departure_time = '3:50 p.m.' THEN 'G4'
            WHEN actual_departure_time = '11:41 a.m.' THEN 'G4'
            WHEN actual_departure_time = '12:14 p.m.' THEN 'G4'
            WHEN actual_departure_time = '2:43 p.m.' THEN 'G4'
            WHEN actual_departure_time = '5:09 p.m.' THEN 'G4'
            WHEN actual_departure_time = '12:42 p.m.' THEN 'G4'
            WHEN actual_departure_time = '4:28 p.m.' THEN 'UA'
            WHEN actual_departure_time = '8:52 a.m.' THEN 'UA'
            WHEN actual_departure_time = '3:28 p.m.' THEN 'G4'
            WHEN actual_departure_time = '1:20 p.m.' THEN 'G4'
            WHEN actual_departure_time = '10:35 a.m.' THEN 'G4'
            WHEN actual_departure_time = '2:59 p.m.' THEN 'G4'
            WHEN actual_departure_time = '6:17 a.m.' THEN 'G4'
            WHEN actual_departure_time = '12:08 p.m.' THEN 'G4'
            WHEN actual_departure_time = '2:38 p.m.' THEN 'G4'
            WHEN actual_departure_time = '10:37 a.m.' THEN 'G4'
            WHEN actual_departure_time = '9:43 a.m.' THEN 'G4'
            WHEN actual_departure_time = '5:56 a.m.' THEN 'UA'
            WHEN actual_departure_time = '3:58 p.m.' THEN 'CO'
            WHEN actual_departure_time = '8:12 a.m.' THEN 'UA'
            WHEN actual_departure_time = '1:32 p.m.' THEN 'UA'
            WHEN actual_departure_time = '7:15 p.m.' THEN 'CO'
            WHEN actual_departure_time = '5:30 p.m.' THEN 'CO'
            WHEN actual_departure_time = '3:31 p.m.' THEN 'CO'
            WHEN actual_departure_time = '7:27 a.m.' THEN 'UA'
            WHEN actual_departure_time = '7:05 a.m.' THEN 'UA'
            WHEN actual_departure_time = '12:41 p.m.' THEN 'AA'
            WHEN actual_departure_time = '10:18 a.m.' THEN 'AA'
            WHEN actual_departure_time = '7:39 a.m.' THEN 'AA'
            WHEN actual_departure_time = '7:21 a.m.' THEN 'AA'
            WHEN actual_departure_time = '10:54 a.m.' THEN 'AA'
            WHEN actual_departure_time = '8:51 a.m.' THEN 'AA'
            WHEN actual_departure_time = '3:27 p.m.' THEN 'AA'
            WHEN actual_departure_time = '4:10 p.m.' THEN 'G4'
            WHEN actual_departure_time = '10:11 a.m.' THEN 'G4'
            WHEN actual_departure_time = '11:02 a.m.' THEN 'G4'
            WHEN actual_departure_time = '1:48 p.m.' THEN 'UA'
            WHEN actual_departure_time = '7:23 a.m.' THEN 'G4'
            WHEN actual_departure_time = '8:37 a.m.' THEN 'G4'
            WHEN actual_departure_time = '11:47 a.m.' THEN 'G4'
            WHEN actual_departure_time = '6:58 a.m.' THEN 'G4'
            WHEN actual_departure_time = '7:32 a.m.' THEN 'G4'
            WHEN actual_departure_time = '8:36 p.m.' THEN 'G4'
            WHEN actual_departure_time = '3:17 p.m.' THEN 'G4'
            WHEN actual_departure_time = '8:05 a.m.' THEN 'G4'
            WHEN actual_departure_time = '4:02 p.m.' THEN 'G4'
            WHEN actual_departure_time = '1:45 p.m.' THEN 'G4'
            WHEN actual_departure_time = '7:29 a.m.' THEN 'CO'
            WHEN actual_departure_time = '11:56 a.m.' THEN 'CO'
            WHEN actual_departure_time = '12:35 p.m.' THEN 'UA'
            WHEN actual_departure_time = '8:00 a.m.' THEN 'CO'
            WHEN actual_departure_time = '2:10 p.m.' THEN 'UA'
            WHEN actual_departure_time = '1:31 p.m.' THEN 'UA'
            WHEN actual_departure_time = '3:01 p.m.' THEN 'CO'
            WHEN actual_departure_time = '4:29 p.m.' THEN 'AA'
            WHEN actual_departure_time = '2:04 p.m.' THEN 'AA'
            WHEN actual_departure_time = '6:55 p.m.' THEN 'AA'
            WHEN actual_departure_time = '7:30 a.m.' THEN 'AA'
            WHEN actual_departure_time = '7:22 a.m.' THEN 'AA'
            WHEN actual_departure_time = '12:10 p.m.' THEN 'AA'
            WHEN actual_departure_time = '8:56 a.m.' THEN 'AA'
            WHEN actual_departure_time = '7:31 a.m.' THEN 'G4'
            WHEN actual_departure_time = '3:04 p.m.' THEN 'G4'
            WHEN actual_departure_time = '10:19 a.m.' THEN 'CO'
            WHEN actual_departure_time = '8:07 a.m.' THEN 'G4'
            WHEN actual_departure_time = '1:43 p.m.' THEN 'G4'
            WHEN actual_departure_time = '4:37 p.m.' THEN 'G4'
            WHEN actual_departure_time = '7:41 a.m.' THEN 'G4'
            WHEN actual_departure_time = '8:40 p.m.' THEN 'G4'
            WHEN actual_departure_time = '7:40 a.m.' THEN 'G4'
            WHEN actual_departure_time = '7:42 p.m.' THEN 'G4'
            WHEN actual_departure_time = '9:01 a.m.' THEN 'G4'
            WHEN actual_departure_time = '12:37 p.m.' THEN 'G4'
            WHEN actual_departure_time = '12:06 p.m.' THEN 'G4'
            WHEN actual_departure_time = '4:15 p.m.' THEN 'UA'
            WHEN actual_departure_time = '8:42 a.m.' THEN 'UA'
            WHEN actual_departure_time = '11:32 a.m.' THEN 'CO'
            WHEN actual_departure_time = '12:41 a.m.' THEN 'CO'
            WHEN actual_departure_time = '5:22 p.m.' THEN 'CO'
            WHEN actual_departure_time = '11:30 a.m.' THEN 'UA'
            WHEN actual_departure_time = '6:02 a.m.' THEN 'CO'
            WHEN actual_departure_time = '11:15 a.m.' THEN 'UA'
            WHEN actual_departure_time = '7:49 a.m.' THEN 'UA'
            ELSE airline_code
        END AS airline_code,
        CASE
            WHEN actual_departure_time = '12:41 p.m.' THEN 'AA-3756-ORD-SLC'
            WHEN actual_departure_time = '7:39 a.m.' THEN 'AA-2525-DFW-MIA'
            WHEN actual_departure_time = '10:54 a.m.' THEN 'AA-2050-ORD-MIA'
            WHEN actual_departure_time = '8:51 a.m.' THEN 'AA-431-MIA-SFO'
            WHEN actual_departure_time = '3:27 p.m.' THEN 'AA-1917-JFK-MCO'
            WHEN actual_departure_time = '1:48 p.m.' THEN 'UA-664-ORD-PHL'
            WHEN actual_departure_time = '7:23 a.m.' THEN 'AA-1165-JFK-MIA'
            WHEN actual_departure_time = '11:47 a.m.' THEN 'UA-2704-DTW-PHX'
            WHEN actual_departure_time = '4:35 p.m.' THEN 'UA-233-LAX-JFK'
            WHEN actual_departure_time = '11:54 a.m.' THEN 'AA-3-JFK-LAX'
            WHEN actual_departure_time = '12:12 p.m.' THEN 'AA-3-JFK-LAX'
            WHEN actual_departure_time = '10:55 a.m.' THEN 'AA-2050-ORD-MIA'
            WHEN actual_departure_time = '12:13 p.m.' THEN 'AA-446-DFW-PHL'
            WHEN actual_departure_time = '6:57 a.m.' THEN 'AA-404-MIA-MCO'
            WHEN actual_departure_time = '12:11 p.m.' THEN 'AA-4277-CVG-JFK'
            WHEN actual_departure_time = '6:56 a.m.' THEN 'AA-466-IAH-MIA'
            WHEN actual_departure_time = '4:28 p.m.' THEN 'UA-233-LAX-JFK'
            WHEN actual_departure_time = '8:52 a.m.' THEN 'AA-431-MIA-SFO'
            WHEN actual_departure_time = '3:28 p.m.' THEN 'AA-1917-JFK-MCO'
            WHEN actual_departure_time = '10:35 a.m.' THEN 'CO-1090-BOS-IAH'
            WHEN actual_departure_time = '1:32 p.m.' THEN 'UA-248-PHX-ORD'
            WHEN actual_departure_time = '7:05 a.m.' THEN 'AA-59-JFK-SFO'
            WHEN actual_departure_time = '8:04 a.m.' THEN 'AA-3979-CVG-ORD'
            WHEN actual_departure_time = '10:10 a.m.' THEN 'AA-616-DFW-DTW'
            WHEN actual_departure_time = '3:36 p.m.' THEN 'AA-4330-CVG-ORD'
            WHEN actual_departure_time = '8:26 a.m.' THEN 'UA-3515-IAD-MSP'
            WHEN actual_departure_time = '6:56 p.m.' THEN 'AA-4307-ORD-DTW'
            WHEN actual_departure_time = '5:38 p.m.' THEN 'CO-63-EWR-IAH'
            WHEN actual_departure_time = '4:30 p.m.' THEN 'AA-484-DFW-MIA'
            WHEN actual_departure_time = '2:04 p.m.' THEN 'AA-1279-DFW-PHX'
            WHEN actual_departure_time = '7:30 a.m.' THEN 'AA-59-JFK-SFO'
            WHEN actual_departure_time = '7:22 a.m.' THEN 'AA-1434-DFW-MCO'
            WHEN actual_departure_time = '12:10 p.m.' THEN 'AA-4277-CVG-JFK'
            WHEN actual_departure_time = '7:31 a.m.' THEN 'AA-59-JFK-SFO'
            WHEN actual_departure_time = '10:19 a.m.' THEN 'AA-1664-MIA-ATL'
            WHEN actual_departure_time = '7:40 a.m.' THEN 'AA-59-JFK-SFO'
            WHEN actual_departure_time = '9:01 a.m.' THEN 'UA-3925-IAD-ORF'
            WHEN actual_departure_time = '4:15 p.m.' THEN 'UA-938-DEN-ORD'
            WHEN actual_departure_time = '7:10 a.m.' THEN 'AA-59-JFK-SFO'
            ELSE flight_code
        END AS flight_code,
        CASE
            WHEN actual_departure_time = '12:12 p.m.' THEN '12:00 p.m.'
            WHEN actual_departure_time = '10:55 a.m.' THEN '10:40 a.m.'
            WHEN actual_departure_time = '12:13 p.m.' THEN '11:50 a.m.'
            WHEN actual_departure_time = '6:57 a.m.' THEN '6:45 a.m.'
            WHEN actual_departure_time = '12:11 p.m.' THEN '12:10 p.m.'
            WHEN actual_departure_time = '6:56 a.m.' THEN '6:00 a.m.'
            WHEN actual_departure_time = '4:28 p.m.' THEN '4:25 p.m.'
            WHEN actual_departure_time = '8:52 a.m.' THEN '8:35 a.m.'
            WHEN actual_departure_time = '3:28 p.m.' THEN '2:55 p.m.'
            WHEN actual_departure_time = '10:35 a.m.' THEN '9:45 a.m.'
            WHEN actual_departure_time = '1:32 p.m.' THEN '12:57 p.m.'
            WHEN actual_departure_time = '7:05 a.m.' THEN '7:10 a.m.'
            WHEN actual_departure_time = '12:41 p.m.' THEN '12:15 p.m.'
            WHEN actual_departure_time = '7:39 a.m.' THEN '7:25 a.m.'
            WHEN actual_departure_time = '10:54 a.m.' THEN '10:40 a.m.'
            WHEN actual_departure_time = '8:51 a.m.' THEN '8:35 a.m.'
            WHEN actual_departure_time = '3:27 p.m.' THEN '2:55 p.m.'
            WHEN actual_departure_time = '1:48 p.m.' THEN '1:33 p.m.'
            WHEN actual_departure_time = '7:23 a.m.' THEN '6:59 a.m.'
            WHEN actual_departure_time = '11:47 a.m.' THEN '11:15 a.m.'
            WHEN actual_departure_time = '4:35 p.m.' THEN '4:25 p.m.'
            WHEN actual_departure_time = '11:54 a.m.' THEN '12:00 p.m.'
            WHEN actual_departure_time = '8:04 a.m.' THEN '7:30 a.m.'
            WHEN actual_departure_time = '10:10 a.m.' THEN '9:05 a.m.'
            WHEN actual_departure_time = '3:36 p.m.' THEN '3:35 p.m.'
            WHEN actual_departure_time = '8:26 a.m.' THEN '8:15 a.m.'
            WHEN actual_departure_time = '6:56 p.m.' THEN '6:45 p.m.'
            WHEN actual_departure_time = '5:38 p.m.' THEN '5:25 p.m.'
            WHEN actual_departure_time = '4:30 p.m.' THEN '4:15 p.m.'
            WHEN actual_departure_time = '2:04 p.m.' THEN '1:00 p.m.'
            WHEN actual_departure_time = '7:30 a.m.' THEN '7:10 a.m.'
            WHEN actual_departure_time = '7:22 a.m.' THEN '7:15 a.m.'
            WHEN actual_departure_time = '12:10 p.m.' THEN '12:10 p.m.'
            WHEN actual_departure_time = '7:31 a.m.' THEN '7:10 a.m.'
            WHEN actual_departure_time = '10:19 a.m.' THEN '10:15 a.m.'
            WHEN actual_departure_time = '7:40 a.m.' THEN '7:10 a.m.'
            WHEN actual_departure_time = '9:01 a.m.' THEN '8:41 a.m.'
            WHEN actual_departure_time = '4:15 p.m.' THEN '4:16 p.m.'
            WHEN actual_departure_time = '7:10 a.m.' THEN '7:10 a.m.'
            ELSE scheduled_departure_time
        END AS scheduled_departure_time,
        actual_departure_time,
        CASE
            WHEN actual_departure_time = '12:41 p.m.' THEN '2:45 p.m.'
            WHEN actual_departure_time = '7:39 a.m.' THEN '11:10 a.m.'
            WHEN actual_departure_time = '10:54 a.m.' THEN '2:45 p.m.'
            WHEN actual_departure_time = '8:51 a.m.' THEN '11:50 a.m.'
            WHEN actual_departure_time = '3:27 p.m.' THEN '5:55 p.m.'
            WHEN actual_departure_time = '1:48 p.m.' THEN '4:31 p.m.'
            WHEN actual_departure_time = '7:23 a.m.' THEN '10:34 a.m.'
            WHEN actual_departure_time = '11:47 a.m.' THEN '1:40 p.m.'
            WHEN actual_departure_time = '4:35 p.m.' THEN '12:29 a.m.'
            WHEN actual_departure_time = '11:54 a.m.' THEN '3:15 p.m.'
            WHEN actual_departure_time = '12:12 p.m.' THEN '3:15 p.m.'
            WHEN actual_departure_time = '10:55 a.m.' THEN '2:45 p.m.'
            WHEN actual_departure_time = '12:13 p.m.' THEN '3:50 p.m.'
            WHEN actual_departure_time = '6:57 a.m.' THEN '7:45 a.m.'
            WHEN actual_departure_time = '12:11 p.m.' THEN '2:15 p.m.'
            WHEN actual_departure_time = '6:56 a.m.' THEN '9:20 a.m.'
            WHEN actual_departure_time = '4:28 p.m.' THEN '12:29 a.m.'
            WHEN actual_departure_time = '8:52 a.m.' THEN '11:50 a.m.'
            WHEN actual_departure_time = '3:28 p.m.' THEN '5:55 p.m.'
            WHEN actual_departure_time = '10:35 a.m.' THEN '1:16 p.m.'
            WHEN actual_departure_time = '1:32 p.m.' THEN '5:15 p.m.'
            WHEN actual_departure_time = '7:05 a.m.' THEN '10:45 a.m.'
            WHEN actual_departure_time = '8:04 a.m.' THEN '8:00 a.m.'
            WHEN actual_departure_time = '10:10 a.m.' THEN '12:35 p.m.'
            WHEN actual_departure_time = '3:36 p.m.' THEN '4:00 p.m.'
            WHEN actual_departure_time = '8:26 a.m.' THEN '10:06 a.m.'
            WHEN actual_departure_time = '6:56 p.m.' THEN '9:10 p.m.'
            WHEN actual_departure_time = '5:38 p.m.' THEN '8:22 p.m.'
            WHEN actual_departure_time = '4:30 p.m.' THEN '7:55 p.m.'
            WHEN actual_departure_time = '2:04 p.m.' THEN '2:35 p.m.'
            WHEN actual_departure_time = '7:30 a.m.' THEN '10:45 a.m.'
            WHEN actual_departure_time = '7:22 a.m.' THEN '10:35 a.m.'
            WHEN actual_departure_time = '12:10 p.m.' THEN '2:15 p.m.'
            WHEN actual_departure_time = '7:31 a.m.' THEN '10:45 a.m.'
            WHEN actual_departure_time = '10:19 a.m.' THEN '12:10 p.m.'
            WHEN actual_departure_time = '7:40 a.m.' THEN '10:45 a.m.'
            WHEN actual_departure_time = '9:01 a.m.' THEN '9:54 a.m.'
            WHEN actual_departure_time = '4:15 p.m.' THEN '7:35 p.m.'
            WHEN actual_departure_time = '7:10 a.m.' THEN '10:45 a.m.'
            ELSE scheduled_arrival_time
        END AS scheduled_arrival_time,
        actual_arrival_time
    FROM "flights_renamed_cleaned_fd_fd"
),

"flights_renamed_cleaned_fd_fd_fd_fd" AS (
    -- FD: functional dependency
    -- scheduled_arrival_time -> airline_code, flight_code, scheduled_departure_time
    SELECT
        flight_id,
        CASE
            WHEN scheduled_arrival_time = '2:45 p.m.' THEN 'G4'
            WHEN scheduled_arrival_time = '6:55 a.m.' THEN 'AA'
            WHEN scheduled_arrival_time = '8:05 p.m.' THEN 'G4'
            WHEN scheduled_arrival_time = '5:50 a.m.' THEN 'AA'
            WHEN scheduled_arrival_time = '11:50 a.m.' THEN 'AA'
            WHEN scheduled_arrival_time = '10:15 p.m.' THEN 'G4'
            WHEN scheduled_arrival_time = '11:55 a.m.' THEN 'G4'
            WHEN scheduled_arrival_time = '11:35 a.m.' THEN 'CO'
            WHEN scheduled_arrival_time = '1:17 p.m.' THEN 'G4'
            WHEN scheduled_arrival_time = '2:00 p.m.' THEN 'G4'
            WHEN scheduled_arrival_time = '12:21 a.m.' THEN 'CO'
            WHEN scheduled_arrival_time = '4:31 p.m.' THEN 'UA'
            WHEN scheduled_arrival_time = '12:29 a.m.' THEN 'UA'
            WHEN scheduled_arrival_time = '11:45 a.m.' THEN 'G4'
            WHEN scheduled_arrival_time = '7:53 p.m.' THEN 'G4'
            WHEN scheduled_arrival_time = '10:45 a.m.' THEN 'G4'
            WHEN scheduled_arrival_time = '7:55 p.m.' THEN 'AA'
            WHEN scheduled_arrival_time = '3:15 p.m.' THEN 'AA'
            WHEN scheduled_arrival_time = '8:00 a.m.' THEN 'AA'
            WHEN scheduled_arrival_time = '2:35 p.m.' THEN 'AA'
            WHEN scheduled_arrival_time = '12:35 p.m.' THEN 'G4'
            WHEN scheduled_arrival_time = '12:15 a.m.' THEN 'AA'
            WHEN scheduled_arrival_time = '11:50 p.m.' THEN 'AA'
            WHEN scheduled_arrival_time = '6:40 p.m.' THEN 'AA'
            WHEN scheduled_arrival_time = '5:05 p.m.' THEN 'G4'
            WHEN scheduled_arrival_time = '10:06 a.m.' THEN 'UA'
            WHEN scheduled_arrival_time = '10:54 a.m.' THEN 'CO'
            WHEN scheduled_arrival_time = '9:25 a.m.' THEN 'AA'
            WHEN scheduled_arrival_time = '12:10 p.m.' THEN 'CO'
            WHEN scheduled_arrival_time = '11:10 a.m.' THEN 'AA'
            WHEN scheduled_arrival_time = '7:45 a.m.' THEN 'AA'
            WHEN scheduled_arrival_time = '2:15 p.m.' THEN 'AA'
            WHEN scheduled_arrival_time = '9:20 p.m.' THEN 'G4'
            WHEN scheduled_arrival_time = '4:05 p.m.' THEN 'AA'
            WHEN scheduled_arrival_time = '5:25 p.m.' THEN 'G4'
            WHEN scheduled_arrival_time = '5:35 a.m.' THEN 'CO'
            WHEN scheduled_arrival_time = '4:57 p.m.' THEN 'G4'
            WHEN scheduled_arrival_time = '1:39 p.m.' THEN 'G4'
            WHEN scheduled_arrival_time = '6:23 p.m.' THEN 'G4'
            WHEN scheduled_arrival_time = '4:17 p.m.' THEN 'G4'
            WHEN scheduled_arrival_time = '10:34 a.m.' THEN 'G4'
            WHEN scheduled_arrival_time = '8:27 a.m.' THEN 'G4'
            WHEN scheduled_arrival_time = '1:40 p.m.' THEN 'G4'
            WHEN scheduled_arrival_time = '10:30 p.m.' THEN 'G4'
            WHEN scheduled_arrival_time = '7:25 p.m.' THEN 'AA'
            WHEN scheduled_arrival_time = '9:55 a.m.' THEN 'AA'
            WHEN scheduled_arrival_time = '9:20 a.m.' THEN 'AA'
            WHEN scheduled_arrival_time = '3:50 p.m.' THEN 'AA'
            WHEN scheduled_arrival_time = '2:25 p.m.' THEN 'AA'
            WHEN scheduled_arrival_time = '4:00 p.m.' THEN 'AA'
            WHEN scheduled_arrival_time = '10:35 a.m.' THEN 'AA'
            WHEN scheduled_arrival_time = '9:10 p.m.' THEN 'G4'
            WHEN scheduled_arrival_time = '9:45 p.m.' THEN 'AA'
            WHEN scheduled_arrival_time = '5:55 p.m.' THEN 'G4'
            WHEN scheduled_arrival_time = '9:54 a.m.' THEN 'G4'
            WHEN scheduled_arrival_time = '11:19 a.m.' THEN 'G4'
            WHEN scheduled_arrival_time = '9:43 a.m.' THEN 'G4'
            WHEN scheduled_arrival_time = '1:16 p.m.' THEN 'G4'
            WHEN scheduled_arrival_time = '7:03 p.m.' THEN 'G4'
            WHEN scheduled_arrival_time = '3:19 p.m.' THEN 'G4'
            WHEN scheduled_arrival_time = '8:22 p.m.' THEN 'G4'
            WHEN scheduled_arrival_time = '8:56 p.m.' THEN 'CO'
            WHEN scheduled_arrival_time = '5:15 p.m.' THEN 'UA'
            WHEN scheduled_arrival_time = '12:18 p.m.' THEN 'CO'
            WHEN scheduled_arrival_time = '7:35 p.m.' THEN 'UA'
            WHEN scheduled_arrival_time = '6:44 p.m.' THEN 'CO'
            WHEN scheduled_arrival_time = '9:24 a.m.' THEN 'G4'
            WHEN scheduled_arrival_time = '4:48 p.m.' THEN 'CO'
            WHEN scheduled_arrival_time = '5:11 a.m.' THEN 'UA'
            WHEN scheduled_arrival_time = '6:30 p.m.' THEN 'G4'
            WHEN scheduled_arrival_time = '6:17 p.m.' THEN 'UA'
            WHEN scheduled_arrival_time = '11:05 a.m.' THEN 'G4'
            ELSE airline_code
        END AS airline_code,
        CASE
            WHEN scheduled_arrival_time = '3:50 p.m.' THEN 'AA-446-DFW-PHL'
            WHEN scheduled_arrival_time = '2:45 p.m.' THEN 'AA-2050-ORD-MIA'
            WHEN scheduled_arrival_time = '2:35 p.m.' THEN 'AA-789-ORD-DEN'
            WHEN scheduled_arrival_time = '6:40 p.m.' THEN 'AA-3786-IAH-ORD'
            ELSE flight_code
        END AS flight_code,
        CASE
            WHEN scheduled_arrival_time = '2:45 p.m.' THEN '10:40 a.m.'
            WHEN scheduled_arrival_time = '3:50 p.m.' THEN '11:50 a.m.'
            WHEN scheduled_arrival_time = '2:35 p.m.' THEN '1:05 p.m.'
            WHEN scheduled_arrival_time = '6:40 p.m.' THEN '4:00 p.m.'
            ELSE scheduled_departure_time
        END AS scheduled_departure_time,
        actual_departure_time,
        scheduled_arrival_time,
        actual_arrival_time
    FROM "flights_renamed_cleaned_fd_fd_fd"
),

"flights_renamed_cleaned_fd_fd_fd_fd_casted" AS (
    -- Column Type Casting: 
    -- scheduled_departure_time: from VARCHAR to TIME
    -- actual_departure_time: from VARCHAR to TIME
    -- scheduled_arrival_time: from VARCHAR to TIME
    -- actual_arrival_time: from VARCHAR to TIME
    SELECT
        "flight_id",
        "airline_code",
        "flight_code",
        "scheduled_departure_time" AS "scheduled_departure_time",
        "actual_departure_time" AS "actual_departure_time",
        "scheduled_arrival_time" AS "scheduled_arrival_time",
        "actual_arrival_time" AS "actual_arrival_time"
    FROM "flights_renamed_cleaned_fd_fd_fd_fd"
)
-- COCOON BLOCK END
select * from "flights_renamed_cleaned_fd_fd_fd_fd_casted"