-- COCOON BLOCK START: PLEASE DO NOT MODIFY THIS BLOCK FOR SELF-MAINTENANCE
-- Generated at 2024-07-07 01:26:59.543080+00:00
WITH 
"beers_renamed" AS (
    -- Rename: Renaming columns
    -- index -> row_number
    -- id -> beer_id
    -- style -> beer_style
    -- ounces -> volume_oz
    -- abv -> alcohol_content
    -- ibu -> bitterness
    -- city -> brewery_city
    -- state -> brewery_state
    SELECT 
        "index" AS "row_number",
        "id" AS "beer_id",
        "beer_name",
        "style" AS "beer_style",
        "ounces" AS "volume_oz",
        "abv" AS "alcohol_content",
        "ibu" AS "bitterness",
        "brewery_id",
        "brewery_name",
        "city" AS "brewery_city",
        "state" AS "brewery_state"
    FROM "memory"."main"."beers"
),

"beers_renamed_cleaned" AS (
    -- Clean unusual string values: 
    -- beer_name: 'Czich' in 'Blonde Czich' may be a typo. '312 Urban Wheat Ale' appears twice. Some beers have year variations listed inconsistently.
    -- volume_oz: The problem is inconsistent formatting and unnecessary additional information. The volume should be consistently represented in ounces with a decimal point, followed by 'oz.' The variations 'oz', 'ounce', and 'OZ.' should be standardized. Additional information like 'Alumi-Tek' and 'Silo Can' is not relevant to the volume and should be removed. The correct values should follow the pattern of 'XX.X oz.' where X represents digits. 
    -- alcohol_content: The problem is inconsistent formatting and precision in the alcohol content column. Some values have a '%' sign while others don't. There are also values with excessive decimal places (e.g., '0.055999999999999994%'). The correct values should be consistent in format (without '%' sign) and have a maximum of 3 decimal places for precision. 
    -- brewery_name: The problem is inconsistent naming conventions and truncated names. The main issues are: 1. Inconsistent use of 'Brewing Company' vs 'Brewery' 2. Some names are truncated (e.g., 'Southern Prohibition Brewing Com...') 3. Inconsistent capitalization (e.g., 'Burn 'Em Brewing' vs 'Burn ''Em Brewing Company') 4. Inconsistent use of 'Craft' in names The correct values should use a consistent format, preferably 'Brewing Company' for full names, and correct any truncations or capitalization issues. 
    -- brewery_city: The problem is inconsistency in how city names are represented. Some include state abbreviations while others don't. The correct values should be just the city names without state abbreviations for consistency. Additionally, there are some redundant entries like 'Chicago' and 'Chicago IL' which should be consolidated. 
    SELECT
        "row_number",
        "beer_id",
        "beer_name",
        "beer_style",
        CASE
            WHEN "volume_oz" = '12.0 oz' THEN '12.0 oz.'
            WHEN "volume_oz" = '12.0 ounce' THEN '12.0 oz.'
            WHEN "volume_oz" = '16.0 oz' THEN '16.0 oz.'
            WHEN "volume_oz" = '16.0 ounce' THEN '16.0 oz.'
            WHEN "volume_oz" = '12.0 OZ.' THEN '12.0 oz.'
            WHEN "volume_oz" = '12.0 oz. Alumi-Tek' THEN '12.0 oz.'
            WHEN "volume_oz" = '16.0 OZ.' THEN '16.0 oz.'
            WHEN "volume_oz" = '16.0 oz. Alumi-Tek' THEN '16.0 oz.'
            WHEN "volume_oz" = '12.0 oz. Silo Can' THEN '12.0 oz.'
            WHEN "volume_oz" = '24.0 ounce' THEN '24.0 oz.'
            WHEN "volume_oz" = '16.0 oz. Silo Can' THEN '16.0 oz.'
            WHEN "volume_oz" = '19.2 OZ.' THEN '19.2 oz.'
            WHEN "volume_oz" = '19.2 oz' THEN '19.2 oz.'
            WHEN "volume_oz" = '24.0 oz' THEN '24.0 oz.'
            WHEN "volume_oz" = '24.0 oz. Alumi-Tek' THEN '24.0 oz.'
            WHEN "volume_oz" = '16.9 OZ.' THEN '16.9 oz.'
            WHEN "volume_oz" = '19.2 oz. Alumi-Tek' THEN '19.2 oz.'
            WHEN "volume_oz" = '32.0 OZ.' THEN '32.0 oz.'
            WHEN "volume_oz" = '32.0 oz. Alumi-Tek' THEN '32.0 oz.'
            WHEN "volume_oz" = '8.4 ounce' THEN '8.4 oz.'
            ELSE "volume_oz"
        END AS "volume_oz",
        CASE
            WHEN "alcohol_content" = '0.05%' THEN '0.050'
            WHEN "alcohol_content" = '0.055%' THEN '0.055'
            WHEN "alcohol_content" = '0.065%' THEN '0.065'
            WHEN "alcohol_content" = '0.06%' THEN '0.060'
            WHEN "alcohol_content" = '0.07%' THEN '0.070'
            WHEN "alcohol_content" = '0.08%' THEN '0.080'
            WHEN "alcohol_content" = '0.055999999999999994%' THEN '0.056'
            WHEN "alcohol_content" = '0.057999999999999996%' THEN '0.058'
            WHEN "alcohol_content" = '0.052000000000000005%' THEN '0.052'
            WHEN "alcohol_content" = '0.045%' THEN '0.045'
            WHEN "alcohol_content" = '0.049%' THEN '0.049'
            WHEN "alcohol_content" = '0.048%' THEN '0.048'
            WHEN "alcohol_content" = '0.047%' THEN '0.047'
            WHEN "alcohol_content" = '0.051%' THEN '0.051'
            WHEN "alcohol_content" = '0.057%' THEN '0.057'
            WHEN "alcohol_content" = '0.068%' THEN '0.068'
            WHEN "alcohol_content" = '0.054000000000000006%' THEN '0.054'
            WHEN "alcohol_content" = '0.09' THEN '0.090%'
            WHEN "alcohol_content" = '0.071' THEN '0.071%'
            WHEN "alcohol_content" = '0.044' THEN '0.044%'
            WHEN "alcohol_content" = '0.059000000000000004%' THEN '0.059%'
            WHEN "alcohol_content" = '0.066' THEN '0.066%'
            WHEN "alcohol_content" = '0.073' THEN '0.073%'
            WHEN "alcohol_content" = '0.077' THEN '0.077%'
            WHEN "alcohol_content" = '0.092' THEN '0.092%'
            WHEN "alcohol_content" = '0.039' THEN '0.039%'
            WHEN "alcohol_content" = '0.07200000000000001%' THEN '0.072%'
            WHEN "alcohol_content" = '0.043' THEN '0.043%'
            WHEN "alcohol_content" = '0.078' THEN '0.078%'
            WHEN "alcohol_content" = '0.087' THEN '0.087%'
            WHEN "alcohol_content" = '0.083' THEN '0.083%'
            WHEN "alcohol_content" = '0.088' THEN '0.088%'
            WHEN "alcohol_content" = '0.041' THEN '0.041%'
            WHEN "alcohol_content" = '0.079' THEN '0.079%'
            WHEN "alcohol_content" = '0.08199999999999999%' THEN '0.082%'
            WHEN "alcohol_content" = '0.095' THEN '0.095%'
            WHEN "alcohol_content" = '0.035' THEN '0.035%'
            WHEN "alcohol_content" = '0.037' THEN '0.037%'
            WHEN "alcohol_content" = '0.040999999999999995%' THEN '0.041%'
            WHEN "alcohol_content" = '0.074' THEN '0.074%'
            WHEN "alcohol_content" = '0.07400000000000001%' THEN '0.074%'
            WHEN "alcohol_content" = '0.076' THEN '0.076%'
            WHEN "alcohol_content" = '0.081' THEN '0.081%'
            WHEN "alcohol_content" = '0.093' THEN '0.093%'
            WHEN "alcohol_content" = '0.032' THEN '0.032%'
            WHEN "alcohol_content" = '0.038' THEN '0.038%'
            WHEN "alcohol_content" = '0.044000000000000004%' THEN '0.044%'
            WHEN "alcohol_content" = '0.091%' THEN '0.091'
            WHEN "alcohol_content" = '0.027000000000000003%' THEN '0.027'
            WHEN "alcohol_content" = '0.035%' THEN '0.035'
            WHEN "alcohol_content" = '0.077%' THEN '0.077'
            WHEN "alcohol_content" = '0.078%' THEN '0.078'
            WHEN "alcohol_content" = '0.079%' THEN '0.079'
            WHEN "alcohol_content" = '0.083%' THEN '0.083'
            WHEN "alcohol_content" = '0.085%' THEN '0.085'
            WHEN "alcohol_content" = '0.087%' THEN '0.087'
            WHEN "alcohol_content" = '0.092%' THEN '0.092'
            WHEN "alcohol_content" = '0.096%' THEN '0.096'
            WHEN "alcohol_content" = '0.09699999999999999%' THEN '0.097'
            WHEN "alcohol_content" = '0.001%' THEN '0.001'
            WHEN "alcohol_content" = '0.076%' THEN '0.076'
            WHEN "alcohol_content" = '0.086%' THEN '0.086'
            WHEN "alcohol_content" = '0.08900000000000001%' THEN '0.089'
            WHEN "alcohol_content" = '0.09300000000000001%' THEN '0.093'
            WHEN "alcohol_content" = '0.10400000000000001%' THEN '0.104'
            WHEN "alcohol_content" = '0.125%' THEN '0.125'
            WHEN "alcohol_content" = '0.128%' THEN '0.128'
            ELSE "alcohol_content"
        END AS "alcohol_content",
        "bitterness",
        "brewery_id",
        CASE
            WHEN "brewery_name" = 'Oskar Blues Brewery' THEN 'Oskar Blues Brewing Company'
            WHEN "brewery_name" = 'Sixpoint Craft Ales' THEN 'Sixpoint Brewing Company'
            WHEN "brewery_name" = 'Hopworks Urban Brewery' THEN 'Hopworks Urban Brewing Company'
            WHEN "brewery_name" = 'Stevens Point Brewery' THEN 'Stevens Point Brewing Company'
            WHEN "brewery_name" = '21st Amendment Brewery' THEN '21st Amendment Brewing Company'
            WHEN "brewery_name" = 'Great Crescent Brewery' THEN 'Great Crescent Brewing Company'
            WHEN "brewery_name" = 'Great River Brewery' THEN 'Great River Brewing Company'
            WHEN "brewery_name" = 'Golden Road Brewing' THEN 'Golden Road Brewing Company'
            WHEN "brewery_name" = '18th Street Brewery' THEN '18th Street Brewing Company'
            WHEN "brewery_name" = 'Against the Grain Brewery' THEN 'Against the Grain Brewing Company'
            WHEN "brewery_name" = 'Minhas Craft Brewery' THEN 'Minhas Brewing Company'
            WHEN "brewery_name" = 'Fort George Brewery' THEN 'Fort George Brewing Company'
            WHEN "brewery_name" = 'Harpoon Brewery' THEN 'Harpoon Brewing Company'
            WHEN "brewery_name" = 'Burn ''Em Brewing' THEN 'Burn ''Em Brewing Company'
            WHEN "brewery_name" = 'Capital Brewery' THEN 'Capital Brewing Company'
            WHEN "brewery_name" = 'Finch''s Beer Company' THEN 'Finch''s Brewing Company'
            WHEN "brewery_name" = 'Southern Prohibition Brewing Com...' THEN 'Southern Prohibition Brewing Company'
            WHEN "brewery_name" = 'Mikerphone Brewing' THEN 'Mikerphone Brewing Company'
            WHEN "brewery_name" = 'Modern Times Beer' THEN 'Modern Times Beer Company'
            WHEN "brewery_name" = 'Revolution Brewing' THEN 'Revolution Brewing Company'
            WHEN "brewery_name" = 'Rhinegeist Brewery' THEN 'Rhinegeist Brewing Company'
            WHEN "brewery_name" = 'TailGate Beer' THEN 'TailGate Brewing Company'
            WHEN "brewery_name" = 'Blackrocks Brewery' THEN 'Blackrocks Brewing Company'
            WHEN "brewery_name" = 'Cisco Brewers' THEN 'Cisco Brewing Company'
            WHEN "brewery_name" = 'Destihl Brewery' THEN 'Destihl Brewing Company'
            WHEN "brewery_name" = 'Eddyline Brewery & Restaurant' THEN 'Eddyline Brewing Company'
            WHEN "brewery_name" = 'Round Guys Brewing' THEN 'Round Guys Brewing Company'
            WHEN "brewery_name" = 'Atwater Brewery' THEN 'Atwater Brewing Company'
            WHEN "brewery_name" = 'Bell''s Brewery' THEN 'Bell''s Brewing Company'
            WHEN "brewery_name" = 'New Orleans Lager & Ale Brewing ...' THEN 'New Orleans Lager & Ale Brewing Company'
            WHEN "brewery_name" = 'Oskar Blues Brewery (North Carol...' THEN 'Oskar Blues Brewery (North Carolina)'
            WHEN "brewery_name" = 'Mehana Brewing Co.' THEN 'Mehana Brewing Company'
            WHEN "brewery_name" = 'Base Camp Brewing Co.' THEN 'Base Camp Brewing Company'
            WHEN "brewery_name" = 'Brooklyn Brewery' THEN 'Brooklyn Brewing Company'
            WHEN "brewery_name" = 'Cedar Creek Brewery' THEN 'Cedar Creek Brewing Company'
            WHEN "brewery_name" = 'Dolores River Brewery' THEN 'Dolores River Brewing Company'
            WHEN "brewery_name" = 'Evil Czech Brewery' THEN 'Evil Czech Brewing Company'
            WHEN "brewery_name" = 'Natian Brewery' THEN 'Natian Brewing Company'
            WHEN "brewery_name" = 'The Alchemist' THEN 'The Alchemist Brewing Company'
            WHEN "brewery_name" = 'Voodoo Brewery' THEN 'Voodoo Brewing Company'
            WHEN "brewery_name" = 'Austin Beerworks' THEN 'Austin Beerworks Brewing Company'
            WHEN "brewery_name" = 'Big Wood Brewery' THEN 'Big Wood Brewing Company'
            WHEN "brewery_name" = 'Blue Mountain Brewery' THEN 'Blue Mountain Brewing Company'
            WHEN "brewery_name" = 'Bohemian Brewery' THEN 'Bohemian Brewing Company'
            WHEN "brewery_name" = 'Evil Twin Brewing' THEN 'Evil Twin Brewing Company'
            WHEN "brewery_name" = 'Hilliard''s Beer' THEN 'Hilliard''s Brewing Company'
            WHEN "brewery_name" = 'Jack''s Abby Craft Lagers' THEN 'Jack''s Abby Brewing Company'
            WHEN "brewery_name" = 'Jackie O''s Pub & Brewery' THEN 'Jackie O''s Brewing Company'
            WHEN "brewery_name" = 'Morgan Street Brewery' THEN 'Morgan Street Brewing Company'
            WHEN "brewery_name" = 'Hawai''i Nui Brewing Co.' THEN 'Hawai''i Nui Brewing Company'
            WHEN "brewery_name" = 'Red Shedman Farm Brewery and Hop...' THEN 'Red Shedman Farm Brewery and Hopyard'
            WHEN "brewery_name" = 'Center of the Universe Brewing C...' THEN 'Center of the Universe Brewing Company'
            WHEN "brewery_name" = 'Swamp Head Brewery' THEN 'Swamp Head Brewing Company'
            WHEN "brewery_name" = 'Breckenridge Brewery' THEN 'Breckenridge Brewing Company'
            WHEN "brewery_name" = 'Epic Brewing' THEN 'Epic Brewing Company'
            WHEN "brewery_name" = 'Hops & Grain Brewery' THEN 'Hops & Grain Brewing Company'
            WHEN "brewery_name" = 'Chapman''s Brewing' THEN 'Chapman''s Brewing Company'
            WHEN "brewery_name" = 'Devil''s Canyon Brewery' THEN 'Devil''s Canyon Brewing Company'
            WHEN "brewery_name" = 'Liquid Hero Brewery' THEN 'Liquid Hero Brewing Company'
            WHEN "brewery_name" = 'Lost Nation Brewing' THEN 'Lost Nation Brewing Company'
            WHEN "brewery_name" = 'Mission Brewery' THEN 'Mission Brewing Company'
            WHEN "brewery_name" = 'Moab Brewery' THEN 'Moab Brewing Company'
            WHEN "brewery_name" = 'Oakshire Brewing' THEN 'Oakshire Brewing Company'
            WHEN "brewery_name" = 'Petoskey Brewing' THEN 'Petoskey Brewing Company'
            WHEN "brewery_name" = 'Saint Archer Brewery' THEN 'Saint Archer Brewing Company'
            WHEN "brewery_name" = 'Starr Hill Brewery' THEN 'Starr Hill Brewing Company'
            WHEN "brewery_name" = 'Straub Brewery' THEN 'Straub Brewing Company'
            WHEN "brewery_name" = 'Texian Brewing Co.' THEN 'Texian Brewing Company'
            WHEN "brewery_name" = 'Third Street Brewhouse' THEN 'Third Street Brewing Company'
            WHEN "brewery_name" = 'Three Pints Brewing' THEN 'Three Pints Brewing Company'
            WHEN "brewery_name" = 'Union Craft Brewing' THEN 'Union Craft Brewing Company'
            WHEN "brewery_name" = 'West Sixth Brewing' THEN 'West Sixth Brewing Company'
            WHEN "brewery_name" = 'White Birch Brewing' THEN 'White Birch Brewing Company'
            WHEN "brewery_name" = 'Alameda Brewing' THEN 'Alameda Brewing Company'
            WHEN "brewery_name" = 'Big Elm Brewing' THEN 'Big Elm Brewing Company'
            WHEN "brewery_name" = 'Bitter Root Brewing' THEN 'Bitter Root Brewing Company'
            WHEN "brewery_name" = 'Bold City Brewery' THEN 'Bold City Brewing Company'
            WHEN "brewery_name" = 'Carolina Beer & Beverage' THEN 'Carolina Beer and Beverage'
            WHEN "brewery_name" = 'Carolina Brewery' THEN 'Carolina Brewing Company'
            WHEN "brewery_name" = 'Flat 12 Bierwerks' THEN 'Flat 12 Brewing Company'
            WHEN "brewery_name" = 'French Broad Brewery' THEN 'French Broad Brewing Company'
            WHEN "brewery_name" = 'Grapevine Craft Brewery' THEN 'Grapevine Craft Brewing Company'
            WHEN "brewery_name" = 'Hardywood Park Craft Brewery' THEN 'Hardywood Park Craft Brewing Company'
            WHEN "brewery_name" = 'Heavy Seas Beer' THEN 'Heavy Seas Brewing Company'
            WHEN "brewery_name" = 'High Noon Saloon And Brewery' THEN 'High Noon Saloon and Brewing Company'
            WHEN "brewery_name" = 'Horny Goat Brew Pub' THEN 'Horny Goat Brewing Company'
            WHEN "brewery_name" = 'Intuition Ale Works' THEN 'Intuition Ale Works Brewing Company'
            WHEN "brewery_name" = 'Mavericks Beer Company' THEN 'Mavericks Brewing Company'
            WHEN "brewery_name" = 'MillKing It Productions' THEN 'MillKing It Brewing Company'
            WHEN "brewery_name" = 'Monkey Paw Pub & Brewery' THEN 'Monkey Paw Brewing Company'
            WHEN "brewery_name" = 'O''Fallon Brewery' THEN 'O''Fallon Brewing Company'
            WHEN "brewery_name" = 'Redhook Brewery' THEN 'Redhook Brewing Company'
            WHEN "brewery_name" = 'Santa Cruz Mountain Brewing' THEN 'Santa Cruz Mountain Brewing Company'
            WHEN "brewery_name" = 'Schilling & Company' THEN 'Schilling and Company'
            WHEN "brewery_name" = 'Silverton Brewery' THEN 'Silverton Brewing Company'
            WHEN "brewery_name" = 'Stillwater Artisanal Ales' THEN 'Stillwater Artisanal Ales Brewing Company'
            WHEN "brewery_name" = 'Straight to Ale' THEN 'Straight to Ale Brewing Company'
            WHEN "brewery_name" = 'Tapistry Brewing' THEN 'Tapistry Brewing Company'
            WHEN "brewery_name" = 'The Right Brain Brewery' THEN 'The Right Brain Brewing Company'
            WHEN "brewery_name" = 'Three Creeks Brewing' THEN 'Three Creeks Brewing Company'
            WHEN "brewery_name" = 'Big Lake Brewing' THEN 'Big Lake Brewing Company'
            WHEN "brewery_name" = 'Big Muddy Brewing' THEN 'Big Muddy Brewing Company'
            WHEN "brewery_name" = 'Bolero Snort Brewery' THEN 'Bolero Snort Brewing Company'
            WHEN "brewery_name" = 'Cape Cod Beer' THEN 'Cape Cod Beer Company'
            WHEN "brewery_name" = 'Catawba Island Brewing' THEN 'Catawba Island Brewing Company'
            WHEN "brewery_name" = 'Chatham Brewing' THEN 'Chatham Brewing Company'
            WHEN "brewery_name" = 'Ciderboys' THEN 'Ciderboys Cider Company'
            WHEN "brewery_name" = 'Jack''s Hard Cider (Hauser Estate...' THEN 'Jack''s Hard Cider (Hauser Estate Winery)'
            WHEN "brewery_name" = 'Moat Mountain Smoke House & Brew...' THEN 'Moat Mountain Smoke House & Brewing Company'
            WHEN "brewery_name" = 'Dad & Dude''s Breweria' THEN 'Dad & Dude''s Brewing Company'
            WHEN "brewery_name" = 'David''s Ale Works' THEN 'David''s Ale Works Brewing Company'
            WHEN "brewery_name" = 'Everybody''s Brewing' THEN 'Everybody''s Brewing Company'
            WHEN "brewery_name" = 'Fat Head''s Brewery' THEN 'Fat Head''s Brewing Company'
            WHEN "brewery_name" = 'Flying Dog Brewery' THEN 'Flying Dog Brewing Company'
            WHEN "brewery_name" = 'Forgotten Boardwalk' THEN 'Forgotten Boardwalk Brewing Company'
            WHEN "brewery_name" = 'Hale''s Ales' THEN 'Hale''s Ales Brewing Company'
            WHEN "brewery_name" = 'Half Full Brewery' THEN 'Half Full Brewing Company'
            WHEN "brewery_name" = 'Hangar 24 Craft Brewery' THEN 'Hangar 24 Craft Brewing Company'
            WHEN "brewery_name" = 'Mother''s Brewing' THEN 'Mother''s Brewing Company'
            WHEN "brewery_name" = 'Northwoods Brewpub' THEN 'Northwoods Brewing Company'
            WHEN "brewery_name" = 'Orpheus Brewing' THEN 'Orpheus Brewing Company'
            WHEN "brewery_name" = 'Mikkeller' THEN 'Mikkeller Brewing Company'
            WHEN "brewery_name" = 'Pine Street Brewery' THEN 'Pine Street Brewing Company'
            WHEN "brewery_name" = 'Pyramid Breweries' THEN 'Pyramid Brewing Company'
            WHEN "brewery_name" = 'River North Brewery' THEN 'River North Brewing Company'
            WHEN "brewery_name" = 'Seven Brides Brewery' THEN 'Seven Brides Brewing Company'
            WHEN "brewery_name" = 'Seattle Cider Company' THEN 'Seattle Cider Brewing Company'
            WHEN "brewery_name" = 'Tommyknocker Brewery' THEN 'Tommyknocker Brewing Company'
            WHEN "brewery_name" = 'Uncle Billy''s Brewery and Smokeh...' THEN 'Uncle Billy''s Brewery and Smokehouse'
            WHEN "brewery_name" = 'Wingman Brewers' THEN 'Wingman Brewing Company'
            WHEN "brewery_name" = 'Woodstock Inn, Station & Brewery' THEN 'Woodstock Inn Station and Brewing Company'
            WHEN "brewery_name" = '7venth Sun' THEN '7venth Sun Brewing Company'
            WHEN "brewery_name" = 'Ale Asylum' THEN 'Ale Asylum Brewing Company'
            WHEN "brewery_name" = 'Angry Minnow' THEN 'Angry Minnow Brewing Company'
            WHEN "brewery_name" = 'Arctic Craft Brewery' THEN 'Arctic Craft Brewing Company'
            WHEN "brewery_name" = 'Bare Hands Brewery' THEN 'Bare Hands Brewing Company'
            WHEN "brewery_name" = 'Black Acre Brewing Co.' THEN 'Black Acre Brewing Company'
            WHEN "brewery_name" = 'Breakside Brewery' THEN 'Breakside Brewing Company'
            WHEN "brewery_name" = 'Brew Link Brewing' THEN 'Brew Link Brewing Company'
            WHEN "brewery_name" = 'Burnside Brewing Co.' THEN 'Burnside Brewing Company'
            WHEN "brewery_name" = 'College Street Brewhouse and Pub' THEN 'College Street Brewing Company'
            WHEN "brewery_name" = 'Cottrell Brewing' THEN 'Cottrell Brewing Company'
            WHEN "brewery_name" = 'Covington Brewhouse' THEN 'Covington Brewing Company'
            WHEN "brewery_name" = 'Dave''s Brewfarm' THEN 'Dave''s Brewing Company'
            WHEN "brewery_name" = 'Dead Armadillo Craft Brewing' THEN 'Dead Armadillo Brewing Company'
            WHEN "brewery_name" = 'Deschutes Brewery' THEN 'Deschutes Brewing Company'
            WHEN "brewery_name" = 'Dock Street Brewery' THEN 'Dock Street Brewing Company'
            WHEN "brewery_name" = 'Emerald City Beer Company' THEN 'Emerald City Brewing Company'
            WHEN "brewery_name" = 'Engine 15 Brewing' THEN 'Engine 15 Brewing Company'
            WHEN "brewery_name" = 'Engine House 9' THEN 'Engine House 9 Brewing Company'
            WHEN "brewery_name" = 'Fullsteam Brewery' THEN 'Fullsteam Brewing Company'
            WHEN "brewery_name" = 'Gonzo''s BiggDogg Brewing' THEN 'Gonzo''s BiggDogg Brewing Company'
            WHEN "brewery_name" = 'Goodlife Brewing Co.' THEN 'Goodlife Brewing Company'
            WHEN "brewery_name" = 'Goose Island Brewery Company' THEN 'Goose Island Brewing Company'
            WHEN "brewery_name" = 'Gore Range Brewery' THEN 'Gore Range Brewing Company'
            WHEN "brewery_name" = 'Green Room Brewing' THEN 'Green Room Brewing Company'
            WHEN "brewery_name" = 'Grimm Brothers Brewhouse' THEN 'Grimm Brothers Brewing Company'
            WHEN "brewery_name" = 'Hinterland Brewery' THEN 'Hinterland Brewing Company'
            WHEN "brewery_name" = 'Indiana City Brewing' THEN 'Indiana City Brewing Company'
            WHEN "brewery_name" = 'Ipswich Ale Brewery' THEN 'Ipswich Brewing Company'
            WHEN "brewery_name" = 'Iron Hill Brewery & Restaurant' THEN 'Iron Hill Brewing Company'
            WHEN "brewery_name" = 'Krebs Brewing Company (Pete''s Pl...' THEN 'Krebs Brewing Company (Pete''s Place)'
            WHEN "brewery_name" = 'Kulshan Brewery' THEN 'Kulshan Brewing Company'
            WHEN "brewery_name" = 'Lazy Monk Brewing' THEN 'Lazy Monk Brewing Company'
            WHEN "brewery_name" = 'Mickey Finn''s Brewery' THEN 'Mickey Finn''s Brewing Company'
            WHEN "brewery_name" = 'Modern Monks Brewery' THEN 'Modern Monks Brewing Company'
            WHEN "brewery_name" = 'Mother Earth Brew Company' THEN 'Mother Earth Brewing Company'
            WHEN "brewery_name" = 'Night Shift Brewing' THEN 'Night Shift Brewing Company'
            WHEN "brewery_name" = 'Northampton Brewery' THEN 'Northampton Brewing Company'
            WHEN "brewery_name" = 'Phoenix Ale Brewery' THEN 'Phoenix Ale Brewing Company'
            WHEN "brewery_name" = 'Portside Brewery' THEN 'Portside Brewing Company'
            WHEN "brewery_name" = 'Refuge Brewery' THEN 'Refuge Brewing Company'
            WHEN "brewery_name" = 'Right Brain Brewery' THEN 'Right Brain Brewing Company'
            WHEN "brewery_name" = 'Roanoke Railhouse Brewery' THEN 'Roanoke Railhouse Brewing Company'
            WHEN "brewery_name" = 'Rogue Ales' THEN 'Rogue Brewing Company'
            WHEN "brewery_name" = 'Seabright Brewery' THEN 'Seabright Brewing Company'
            WHEN "brewery_name" = 'Sherwood Forest Brewers' THEN 'Sherwood Forest Brewing Company'
            WHEN "brewery_name" = 'Southampton Publick House' THEN 'Southampton Brewing Company'
            WHEN "brewery_name" = 'Speakasy Ales & Lagers' THEN 'Speakeasy Brewing Company'
            WHEN "brewery_name" = 'Spilker Ales' THEN 'Spilker Brewing Company'
            WHEN "brewery_name" = 'Stillmank Beer Company' THEN 'Stillmank Brewing Company'
            WHEN "brewery_name" = 'The Lion Brewery' THEN 'The Lion Brewing Company'
            WHEN "brewery_name" = 'The Manhattan Brewing Company' THEN 'Manhattan Brewing Company'
            WHEN "brewery_name" = 'The Traveler Beer Company' THEN 'Traveler Brewing Company'
            ELSE "brewery_name"
        END AS "brewery_name",
        CASE
            WHEN "brewery_city" = 'Portland OR' THEN 'Portland'
            WHEN "brewery_city" = 'Boise ID' THEN 'Boise'
            WHEN "brewery_city" = 'Chicago IL' THEN 'Chicago'
            WHEN "brewery_city" = 'Portland ME' THEN 'Portland'
            WHEN "brewery_city" = 'Saint Louis MO' THEN 'Saint Louis'
            WHEN "brewery_city" = 'Minneapolis MN' THEN 'Minneapolis'
            WHEN "brewery_city" = 'San Antonio TX' THEN 'San Antonio'
            WHEN "brewery_city" = 'Anchorage AK' THEN 'Anchorage'
            WHEN "brewery_city" = 'Lincoln NE' THEN 'Lincoln'
            WHEN "brewery_city" = 'Louisville KY' THEN 'Louisville'
            WHEN "brewery_city" = 'Birmingham AL' THEN 'Birmingham'
            WHEN "brewery_city" = 'Gary IN' THEN 'Gary'
            WHEN "brewery_city" = 'Conroe TX' THEN 'Conroe'
            WHEN "brewery_city" = 'Export PA' THEN 'Export'
            WHEN "brewery_city" = 'Los Angeles CA' THEN 'Los Angeles'
            WHEN "brewery_city" = 'Pottstown PA' THEN 'Pottstown'
            WHEN "brewery_city" = 'Brooklyn Center MN' THEN 'Brooklyn Center'
            WHEN "brewery_city" = 'Lahaina HI' THEN 'Lahaina'
            WHEN "brewery_city" = 'Lyons CO' THEN 'Lyons'
            WHEN "brewery_city" = 'Monroe WI' THEN 'Monroe'
            WHEN "brewery_city" = 'Bend OR' THEN 'Bend'
            WHEN "brewery_city" = 'Dallas TX' THEN 'Dallas'
            WHEN "brewery_city" = 'Hilo HI' THEN 'Hilo'
            WHEN "brewery_city" = 'Houston TX' THEN 'Houston'
            WHEN "brewery_city" = 'Bucryus' THEN 'Bucyrus'
            WHEN "brewery_city" = 'Brevard' THEN 'Brevard, NC'
            WHEN "brewery_city" = 'Charleston' THEN 'Charleston, SC'
            WHEN "brewery_city" = 'Comstock Park' THEN 'Comstock Park, MI'
            WHEN "brewery_city" = 'Dillon' THEN 'Dillon, CO'
            WHEN "brewery_city" = 'Dolores' THEN 'Dolores, CO'
            WHEN "brewery_city" = 'Estacada' THEN 'Estacada, OR'
            WHEN "brewery_city" = 'Eugene' THEN 'Eugene, OR'
            WHEN "brewery_city" = 'Fuquay-Varina' THEN 'Fuquay-Varina, NC'
            WHEN "brewery_city" = 'Lake Havasu City' THEN 'Lake Havasu City, AZ'
            WHEN "brewery_city" = 'Lansdale' THEN 'Lansdale, PA'
            WHEN "brewery_city" = 'Mishawaka' THEN 'Mishawaka, IN'
            WHEN "brewery_city" = 'New Orleans' THEN 'New Orleans, LA'
            WHEN "brewery_city" = 'Reno' THEN 'Reno, NV'
            WHEN "brewery_city" = 'Seven Points' THEN 'Seven Points, TX'
            WHEN "brewery_city" = 'Sheridan' THEN 'Sheridan, WY'
            WHEN "brewery_city" = 'Spirit Lake' THEN 'Spirit Lake, IA'
            WHEN "brewery_city" = 'Waterbury' THEN 'Waterbury, VT'
            WHEN "brewery_city" = 'Airway Heights' THEN 'Airway Heights, WA'
            WHEN "brewery_city" = 'Alpine' THEN 'Alpine, TX'
            WHEN "brewery_city" = 'Asheville' THEN 'Asheville, NC'
            WHEN "brewery_city" = 'Belfast' THEN 'Belfast, ME'
            WHEN "brewery_city" = 'Bozeman' THEN 'Bozeman, MT'
            WHEN "brewery_city" = 'Bridgewater Corners' THEN 'Bridgewater Corners, VT'
            WHEN "brewery_city" = 'Charlottesville' THEN 'Charlottesville, VA'
            WHEN "brewery_city" = 'Detroit' THEN 'Detroit, MI'
            WHEN "brewery_city" = 'Duluth' THEN 'Duluth, MN'
            WHEN "brewery_city" = 'Flagstaff' THEN 'Flagstaff, AZ'
            WHEN "brewery_city" = 'Gainesville' THEN 'Gainesville, FL'
            WHEN "brewery_city" = 'Meadville' THEN 'Meadville, PA'
            WHEN "brewery_city" = 'Midvale' THEN 'Midvale, UT'
            WHEN "brewery_city" = 'Mt. Airy' THEN 'Mt. Airy, MD'
            WHEN "brewery_city" = 'Mustang' THEN 'Mustang, OK'
            WHEN "brewery_city" = 'Newport' THEN 'Newport, OR'
            WHEN "brewery_city" = 'Papillion' THEN 'Papillion, NE'
            WHEN "brewery_city" = 'Raleigh' THEN 'Raleigh, NC'
            WHEN "brewery_city" = 'Sacramento' THEN 'Sacramento, CA'
            WHEN "brewery_city" = 'Santee' THEN 'Santee, CA'
            WHEN "brewery_city" = 'Spring Lake' THEN 'Spring Lake, MI'
            WHEN "brewery_city" = 'Stratford' THEN 'Stratford, CT'
            WHEN "brewery_city" = 'Temecula' THEN 'Temecula, CA'
            WHEN "brewery_city" = 'Torrance' THEN 'Torrance, CA'
            WHEN "brewery_city" = 'Traverse City' THEN 'Traverse City, MI'
            WHEN "brewery_city" = 'Vadnais Heights' THEN 'Vadnais Heights, MN'
            WHEN "brewery_city" = 'Avon' THEN 'Avon, CO'
            WHEN "brewery_city" = 'Bellingham' THEN 'Bellingham, WA'
            WHEN "brewery_city" = 'Brooklyn NY' THEN 'Brooklyn, NY'
            WHEN "brewery_city" = 'Broomfield' THEN 'Broomfield, CO'
            WHEN "brewery_city" = 'Carlsbad' THEN 'Carlsbad, CA'
            WHEN "brewery_city" = 'Cold Spring' THEN 'Cold Spring, MN'
            WHEN "brewery_city" = 'Indianapolis IN' THEN 'Indianapolis'
            WHEN "brewery_city" = 'Boulder CO' THEN 'Boulder'
            WHEN "brewery_city" = 'Denver CO' THEN 'Denver'
            WHEN "brewery_city" = 'South Austin' THEN 'Austin'
            WHEN "brewery_city" = 'Longmont CO' THEN 'Longmont, CO'
            WHEN "brewery_city" = 'San Diego CA' THEN 'San Diego, CA'
            WHEN "brewery_city" = 'St Petersburg' THEN 'St. Petersburg, FL'
            WHEN "brewery_city" = 'St. John''s' THEN 'St. John''s, NL'
            WHEN "brewery_city" = 'Menominie' THEN 'Menomonie, WI'
            WHEN "brewery_city" = 'O''Fallon' THEN 'O''Fallon, MO'
            WHEN "brewery_city" = 'Bloomington IL' THEN 'Bloomington, IL'
            WHEN "brewery_city" = 'Cincinnati OH' THEN 'Cincinnati, OH'
            WHEN "brewery_city" = 'Fort Worth TX' THEN 'Fort Worth, TX'
            WHEN "brewery_city" = 'Belt' THEN 'Belt, MT'
            WHEN "brewery_city" = 'Biglerville' THEN 'Biglerville, PA'
            WHEN "brewery_city" = 'Black Mountain' THEN 'Black Mountain, NC'
            WHEN "brewery_city" = 'Buellton' THEN 'Buellton, CA'
            WHEN "brewery_city" = 'Burlington' THEN 'Burlington, VT'
            WHEN "brewery_city" = 'Chatham' THEN 'Chatham, MA'
            WHEN "brewery_city" = 'Chattanooga' THEN 'Chattanooga, TN'
            WHEN "brewery_city" = 'Cherry Hill' THEN 'Cherry Hill, NJ'
            WHEN "brewery_city" = 'Croydon' THEN 'Croydon, PA'
            WHEN "brewery_city" = 'Des Moines' THEN 'Des Moines, IA'
            WHEN "brewery_city" = 'Diamond Springs' THEN 'Diamond Springs, CA'
            WHEN "brewery_city" = 'Elmira' THEN 'Elmira, NY'
            WHEN "brewery_city" = 'Erie' THEN 'Erie, PA'
            WHEN "brewery_city" = 'Evanston' THEN 'Evanston, IL'
            WHEN "brewery_city" = 'Frankenmuth' THEN 'Frankenmuth, MI'
            WHEN "brewery_city" = 'Frederick' THEN 'Frederick, MD'
            WHEN "brewery_city" = 'Fredericksburg' THEN 'Fredericksburg, VA'
            WHEN "brewery_city" = 'Gadsden' THEN 'Gadsden, AL'
            WHEN "brewery_city" = 'Glendale' THEN 'Glendale, CA'
            WHEN "brewery_city" = 'Golden' THEN 'Golden, CO'
            WHEN "brewery_city" = 'Green Bay' THEN 'Green Bay, WI'
            WHEN "brewery_city" = 'Hardy' THEN 'Hardy, VA'
            WHEN "brewery_city" = 'Hays' THEN 'Hays, KS'
            WHEN "brewery_city" = 'Hayward' THEN 'Hayward, CA'
            WHEN "brewery_city" = 'Holland' THEN 'Holland, MI'
            WHEN "brewery_city" = 'Hyannis' THEN 'Hyannis, MA'
            WHEN "brewery_city" = 'Juneau' THEN 'Juneau, AK'
            WHEN "brewery_city" = 'Kalona' THEN 'Kalona, IA'
            WHEN "brewery_city" = 'Kinston' THEN 'Kinston, NC'
            WHEN "brewery_city" = 'Kirkwood' THEN 'Kirkwood, MO'
            WHEN "brewery_city" = 'Lake Geneva' THEN 'Lake Geneva, WI'
            WHEN "brewery_city" = 'Lakeside' THEN 'Lakeside, CA'
            WHEN "brewery_city" = 'Lancaster' THEN 'Lancaster, PA'
            WHEN "brewery_city" = 'Lenoir' THEN 'Lenoir, NC'
            WHEN "brewery_city" = 'Leominster' THEN 'Leominster, MA'
            WHEN "brewery_city" = 'Lewisburg' THEN 'Lewisburg, PA'
            WHEN "brewery_city" = 'Lockland' THEN 'Lockland, OH'
            WHEN "brewery_city" = 'Macon' THEN 'Macon, GA'
            WHEN "brewery_city" = 'Marietta' THEN 'Marietta, GA'
            WHEN "brewery_city" = 'Medford' THEN 'Medford, OR'
            WHEN "brewery_city" = 'Meridian' THEN 'Meridian, ID'
            WHEN "brewery_city" = 'Middleburg Heights' THEN 'Middleburg Heights, OH'
            WHEN "brewery_city" = 'Mooresville NC' THEN 'Mooresville, NC'
            WHEN "brewery_city" = 'Utica NY' THEN 'Utica, NY'
            WHEN "brewery_city" = 'Afton VA' THEN 'Afton, VA'
            WHEN "brewery_city" = 'Albuquerque NM' THEN 'Albuquerque, NM'
            WHEN "brewery_city" = 'Angola IN' THEN 'Angola, IN'
            WHEN "brewery_city" = 'Asheville NC' THEN 'Asheville, NC'
            WHEN "brewery_city" = 'Ashland OR' THEN 'Ashland, OR'
            WHEN "brewery_city" = 'Athens GA' THEN 'Athens, GA'
            WHEN "brewery_city" = 'Atlantic Highlands NJ' THEN 'Atlantic Highlands, NJ'
            WHEN "brewery_city" = 'Aurora IN' THEN 'Aurora, IN'
            WHEN "brewery_city" = 'Baltimore MD' THEN 'Baltimore, MD'
            WHEN "brewery_city" = 'Belmont CA' THEN 'Belmont, CA'
            WHEN "brewery_city" = 'Boston MA' THEN 'Boston, MA'
            WHEN "brewery_city" = 'Buellton CA' THEN 'Buellton, CA'
            WHEN "brewery_city" = 'Middlebury' THEN 'Middlebury, VT'
            WHEN "brewery_city" = 'Mill Valley' THEN 'Mill Valley, CA'
            WHEN "brewery_city" = 'Minnetonka' THEN 'Minnetonka, MN'
            WHEN "brewery_city" = 'Montauk' THEN 'Montauk, NY'
            WHEN "brewery_city" = 'Murphysboro' THEN 'Murphysboro, IL'
            WHEN "brewery_city" = 'North Conway' THEN 'North Conway, NH'
            WHEN "brewery_city" = 'Odessa' THEN 'Odessa, TX'
            WHEN "brewery_city" = 'Pacific' THEN 'Pacific, MO'
            WHEN "brewery_city" = 'Palisade' THEN 'Palisade, CO'
            WHEN "brewery_city" = 'Pinedale' THEN 'Pinedale, WY'
            WHEN "brewery_city" = 'Pittsburgh' THEN 'Pittsburgh, PA'
            WHEN "brewery_city" = 'Port Clinton' THEN 'Port Clinton, OH'
            WHEN "brewery_city" = 'Prescott' THEN 'Prescott, AZ'
            WHEN "brewery_city" = 'Redlands' THEN 'Redlands, CA'
            WHEN "brewery_city" = 'Ridgefield Park' THEN 'Ridgefield Park, NJ'
            WHEN "brewery_city" = 'Savannah' THEN 'Savannah, GA'
            WHEN "brewery_city" = 'Shreveport' THEN 'Shreveport, LA'
            WHEN "brewery_city" = 'South Deerfield' THEN 'South Deerfield, MA'
            WHEN "brewery_city" = 'South Lyon' THEN 'South Lyon, MI'
            WHEN "brewery_city" = 'St. Paul' THEN 'St. Paul, MN'
            WHEN "brewery_city" = 'Stamford' THEN 'Stamford, CT'
            WHEN "brewery_city" = 'Stevensville' THEN 'Stevensville, MT'
            WHEN "brewery_city" = 'Stillwater' THEN 'Stillwater, MN'
            WHEN "brewery_city" = 'Troutville' THEN 'Troutville, VA'
            WHEN "brewery_city" = 'White Salmon' THEN 'White Salmon, WA'
            WHEN "brewery_city" = 'Whitefish' THEN 'Whitefish, MT'
            WHEN "brewery_city" = 'Windsor' THEN 'Windsor, CA'
            WHEN "brewery_city" = 'Yakima' THEN 'Yakima, WA'
            WHEN "brewery_city" = 'Abingdon' THEN 'Abingdon, VA'
            WHEN "brewery_city" = 'Ada' THEN 'Ada, MI'
            WHEN "brewery_city" = 'Ann Arbor' THEN 'Ann Arbor, MI'
            WHEN "brewery_city" = 'Arrington' THEN 'Arrington, VA'
            WHEN "brewery_city" = 'Bargersville' THEN 'Bargersville, IN'
            WHEN "brewery_city" = 'Boynton Beach' THEN 'Boynton Beach, FL'
            WHEN "brewery_city" = 'Cambridge' THEN 'Cambridge MA'
            WHEN "brewery_city" = 'Centralia' THEN 'Centralia WA'
            WHEN "brewery_city" = 'Claremont' THEN 'Claremont CA'
            WHEN "brewery_city" = 'Colorado Springs' THEN 'Colorado Springs CO'
            WHEN "brewery_city" = 'Conestoga' THEN 'Conestoga PA'
            WHEN "brewery_city" = 'Cortland' THEN 'Cortland NY'
            WHEN "brewery_city" = 'Covington' THEN 'Covington KY'
            WHEN "brewery_city" = 'Denton' THEN 'Denton TX'
            WHEN "brewery_city" = 'Douglas' THEN 'Douglas GA'
            WHEN "brewery_city" = 'Dunedin' THEN 'Dunedin FL'
            WHEN "brewery_city" = 'East Windsor' THEN 'East Windsor CT'
            WHEN "brewery_city" = 'Everett' THEN 'Everett WA'
            WHEN "brewery_city" = 'Fort Wayne' THEN 'Fort Wayne IN'
            WHEN "brewery_city" = 'Granger' THEN 'Granger IN'
            WHEN "brewery_city" = 'Hudsonville' THEN 'Hudsonville MI'
            WHEN "brewery_city" = 'Idaho Springs' THEN 'Idaho Springs CO'
            WHEN "brewery_city" = 'Jacksonville Beach' THEN 'Jacksonville Beach FL'
            WHEN "brewery_city" = 'Kansas City' THEN 'Kansas City MO'
            WHEN "brewery_city" = 'Knoxville' THEN 'Knoxville TN'
            WHEN "brewery_city" = 'Krebs' THEN 'Krebs OK'
            WHEN "brewery_city" = 'Madison WI' THEN 'Madison, WI'
            WHEN "brewery_city" = 'Manhattan KS' THEN 'Manhattan, KS'
            WHEN "brewery_city" = 'Marietta GA' THEN 'Marietta, GA'
            WHEN "brewery_city" = 'Meadville PA' THEN 'Meadville, PA'
            WHEN "brewery_city" = 'Mill Valley CA' THEN 'Mill Valley, CA'
            WHEN "brewery_city" = 'Myrtle Beach' THEN 'Myrtle Beach, SC'
            WHEN "brewery_city" = 'Myrtle Beach SC' THEN 'Myrtle Beach, SC'
            WHEN "brewery_city" = 'Nellysford VA' THEN 'Nellysford, VA'
            WHEN "brewery_city" = 'North Woodstock' THEN 'North Woodstock, NH'
            WHEN "brewery_city" = 'North Woodstock NH' THEN 'North Woodstock, NH'
            WHEN "brewery_city" = 'Northamtpon' THEN 'Northampton, MA'
            WHEN "brewery_city" = 'Oklahoma City OK' THEN 'Oklahoma City, OK'
            WHEN "brewery_city" = 'Paonia CO' THEN 'Paonia, CO'
            WHEN "brewery_city" = 'Paso Robles CA' THEN 'Paso Robles, CA'
            WHEN "brewery_city" = 'Petoskey MI' THEN 'Petoskey, MI'
            WHEN "brewery_city" = 'Pineland ME' THEN 'Pineland, ME'
            WHEN "brewery_city" = 'Pittsburgh PA' THEN 'Pittsburgh, PA'
            WHEN "brewery_city" = 'Plainfield IN' THEN 'Plainfield, IN'
            WHEN "brewery_city" = 'Reno NV' THEN 'Reno, NV'
            WHEN "brewery_city" = 'Rochester MI' THEN 'Rochester, MI'
            WHEN "brewery_city" = 'San Francisco CA' THEN 'San Francisco, CA'
            WHEN "brewery_city" = 'San Luis Obispo CA' THEN 'San Luis Obispo, CA'
            WHEN "brewery_city" = 'Santa Cruz CA' THEN 'Santa Cruz, CA'
            WHEN "brewery_city" = 'Silverton OR' THEN 'Silverton, OR'
            WHEN "brewery_city" = 'Soldotna AK' THEN 'Soldotna, AK'
            WHEN "brewery_city" = 'South Bend' THEN 'South Bend, IN'
            WHEN "brewery_city" = 'South San Francisco' THEN 'South San Francisco, CA'
            WHEN "brewery_city" = 'Southampton' THEN 'Southampton, NY'
            WHEN "brewery_city" = 'Springdale AR' THEN 'Springdale, AR'
            WHEN "brewery_city" = 'St Paul' THEN 'St. Paul, MN'
            WHEN "brewery_city" = 'St. Paul MN' THEN 'St. Paul, MN'
            WHEN "brewery_city" = 'Stevens Point WI' THEN 'Stevens Point, WI'
            WHEN "brewery_city" = 'Stevensville MT' THEN 'Stevensville, MT'
            WHEN "brewery_city" = 'Tampa Bay' THEN 'Tampa, FL'
            WHEN "brewery_city" = 'Tampa Bay FL' THEN 'Tampa, FL'
            WHEN "brewery_city" = 'Tampa FL' THEN 'Tampa, FL'
            WHEN "brewery_city" = 'Tulsa' THEN 'Tulsa, OK'
            WHEN "brewery_city" = 'Ukiah' THEN 'Ukiah, CA'
            WHEN "brewery_city" = 'Virginia Beach' THEN 'Virginia Beach, VA'
            WHEN "brewery_city" = 'Vista' THEN 'Vista, CA'
            WHEN "brewery_city" = 'Waterbury VT' THEN 'Waterbury, VT'
            WHEN "brewery_city" = 'Waynesville' THEN 'Waynesville, NC'
            WHEN "brewery_city" = 'Westminster MA' THEN 'Westminster, MA'
            WHEN "brewery_city" = 'Wilkes-Barre' THEN 'Wilkes-Barre, PA'
            WHEN "brewery_city" = 'Wilmington' THEN 'Wilmington, DE'
            WHEN "brewery_city" = 'Wilson' THEN 'Wilson, NC'
            WHEN "brewery_city" = 'Wolcott' THEN 'Wolcott, VT'
            WHEN "brewery_city" = 'Worcester' THEN 'Worcester, MA'
            WHEN "brewery_city" = 'Yardley' THEN 'Yardley, PA'
            WHEN "brewery_city" = 'York PA' THEN 'York, PA'
            ELSE "brewery_city"
        END AS "brewery_city",
        "brewery_state"
    FROM "beers_renamed"
),

"beers_renamed_cleaned_casted" AS (
    -- Column Type Casting: 
    -- volume_oz: from VARCHAR to DECIMAL
    -- alcohol_content: from VARCHAR to DECIMAL
    SELECT
        "row_number",
        "beer_id",
        "beer_name",
        "beer_style",
        "bitterness",
        "brewery_id",
        "brewery_name",
        "brewery_city",
        "brewery_state",
        CAST(REGEXP_EXTRACT("volume_oz", '(\d+(\.\d+)?)') AS DECIMAL) AS "volume_oz",
        CASE
            WHEN regexp_full_match("alcohol_content", '0\.\d{2,3}%') THEN CAST(REGEXP_EXTRACT("alcohol_content", '(0\.\d{2,3})') AS DECIMAL)
            WHEN regexp_full_match("alcohol_content", '0\.\d{2,3}') THEN CAST("alcohol_content" AS DECIMAL)
            WHEN regexp_full_match("alcohol_content", '0\.\d') THEN CAST("alcohol_content" AS DECIMAL)
        END AS "alcohol_content"
    FROM "beers_renamed_cleaned"
)

-- COCOON BLOCK END
SELECT * FROM "beers_renamed_cleaned_casted"