-- COCOON BLOCK START: PLEASE DO NOT MODIFY THIS BLOCK FOR SELF-MAINTENANCE
-- Generated at 2024-07-07 02:02:41.012202+00:00
WITH 
"movies_renamed" AS (
    -- Rename: Renaming columns
    -- id -> movie_id
    -- name -> title
    -- year -> release_year
    -- creator -> writers
    -- actors -> main_actors
    -- language -> languages
    -- duration -> runtime
    -- rating_value -> average_rating
    -- rating_count -> number_of_ratings
    -- review_count -> number_of_reviews
    -- genre -> genres
    -- description -> plot_summary
    SELECT 
        "id" AS "movie_id",
        "name" AS "title",
        "year" AS "release_year",
        "release_date",
        "director",
        "creator" AS "writers",
        "actors" AS "main_actors",
        "full_cast",
        "language" AS "languages",
        "country",
        "duration" AS "runtime",
        "rating_value" AS "average_rating",
        "rating_count" AS "number_of_ratings",
        "review_count" AS "number_of_reviews",
        "genre" AS "genres",
        "filming_locations",
        "description" AS "plot_summary"
    FROM "memory"."main"."movies"
),

"movies_renamed_cleaned" AS (
    -- Clean unusual string values: 
    -- title: 'G' Men and 'night, Mother have unusual quote usage. #Lucky Number and 3 1/2 Minutes, Ten Bullets have atypical formatting.
    -- director: Some entries use commas to separate co-directors, while others use 'and'. Inconsistent use of middle initials.
    -- languages: The problem is inconsistent ordering of languages and inconsistent representation of Chinese languages. The correct values should have English listed first when present, and use "Mandarin" consistently instead of "Chinese" or "Cantonese". Additionally, some entries have multiple languages separated by commas, which should be standardized. 
    -- country: The problem is inconsistent naming conventions for countries and the use of multiple countries in single entries. The main issues are: 1. USA and United States are used interchangeably 2. UK and United Kingdom are both used 3. West Germany appears alongside Germany 4. Multiple countries are listed in a single entry, separated by commas The correct values should use consistent naming (USA, UK, Germany) and separate multiple countries into individual entries. 
    -- runtime: The runtime column is actually consistent, using the format "[number] min" for all entries. All durations are represented in minutes, which is a standard way to express movie runtimes. There are no unusual values or inconsistent formats that need to be corrected in the given list. 
    -- average_rating: The problem is that some ratings are represented as fractions (e.g. '7.6/10') while others are just decimal numbers (e.g. '7.6'). Additionally, there are entries with multiple ratings separated by commas. The correct values should be consistent decimal numbers representing the rating out of 10. We'll remove the '/10' where present and take the first rating in cases of multiple ratings. 
    -- number_of_ratings: Some values use commas (e.g., '1,023'), while others don't (e.g., '15971'), creating inconsistent number formatting.
    -- genres: The genres column has several inconsistencies: 1. Inconsistent use of separators ('&' vs ',') 2. Redundant entries (e.g. 'Drama,Comedy' and 'Comedy,Drama') 3. Inconsistent capitalization (some genres use title case, others lowercase) 4. Inconsistent ordering of genres within multi-genre entries To fix these issues, we should: 1. Standardize on using ',' as the separator 2. Remove redundancies by sorting genres alphabetically within each entry 3. Use title case for all genres 4. Ensure consistent ordering of genres 
    -- filming_locations: New York City is represented as 'New York City', 'New York', and 'NY'. Los Angeles has multiple variations.
    SELECT
        "movie_id",
        "title",
        "release_year",
        "release_date",
        "director",
        "writers",
        "main_actors",
        "full_cast",
        CASE
            WHEN "languages" = 'English,Cantonese' THEN 'English,Mandarin'
            WHEN "languages" = 'English,German,French' THEN 'English,French,German'
            WHEN "languages" = 'Spanish,English' THEN 'English,Spanish'
            WHEN "languages" = 'English,Spanish,French' THEN 'English,French,Spanish'
            WHEN "languages" = 'Japanese,English' THEN 'English,Japanese'
            WHEN "languages" = 'English,Italian,French' THEN 'English,French,Italian'
            WHEN "languages" = 'English,Japanese,French' THEN 'English,French,Japanese'
            WHEN "languages" = 'English,Spanish,German' THEN 'English,German,Spanish'
            WHEN "languages" = 'English,Spanish,Latin' THEN 'English,Latin,Spanish'
            WHEN "languages" = 'English,Spanish,Portuguese' THEN 'English,Portuguese,Spanish'
            WHEN "languages" = 'English,Chinese' THEN 'English,Mandarin'
            WHEN "languages" = 'English,French,Italian,German' THEN 'English,French,German,Italian'
            WHEN "languages" = 'German,English' THEN 'English,German'
            WHEN "languages" = 'Italian,English' THEN 'English,Italian'
            WHEN "languages" = 'English,Mandarin,Cantonese' THEN 'English,Cantonese,Mandarin'
            WHEN "languages" = 'English,French,Arabic' THEN 'English,Arabic,French'
            WHEN "languages" = 'English,French,Arabic,German' THEN 'English,Arabic,French,German'
            WHEN "languages" = 'English,German,French,Russian' THEN 'English,French,German,Russian'
            WHEN "languages" = 'English,Italian,German' THEN 'English,German,Italian'
            WHEN "languages" = 'English,Italian,German,French' THEN 'English,French,German,Italian'
            WHEN "languages" = 'English,Japanese,German,French' THEN 'English,French,German,Japanese'
            WHEN "languages" = 'English,Latin,French' THEN 'English,French,Latin'
            WHEN "languages" = 'English,Latin,Italian' THEN 'English,Italian,Latin'
            WHEN "languages" = 'English,Spanish,Korean' THEN 'English,Korean,Spanish'
            WHEN "languages" = 'English,Spanish,Russian' THEN 'English,Russian,Spanish'
            WHEN "languages" = 'English,Vietnamese,French' THEN 'English,French,Vietnamese'
            WHEN "languages" = 'French,English' THEN 'English,French'
            WHEN "languages" = 'German,English,Spanish' THEN 'English,German,Spanish'
            WHEN "languages" = 'Mandarin,English' THEN 'Chinese,English'
            WHEN "languages" = 'Russian,English' THEN 'English,Russian'
            WHEN "languages" = 'Amharic,Italian,English' THEN 'English,Amharic,Italian'
            WHEN "languages" = 'Bengali,English' THEN 'English,Bengali'
            WHEN "languages" = 'Cantonese,English,Mandarin' THEN 'Chinese,English'
            WHEN "languages" = 'Cree,English,Mohawk,Algonquin,Latin' THEN 'Algonquin,Cree,English,Latin,Mohawk'
            WHEN "languages" = 'English,Aboriginal' THEN 'English'
            WHEN "languages" = 'English,Aboriginal,Chinese,Japanese' THEN 'Chinese,English,Japanese'
            WHEN "languages" = 'English,Afrikaans,Maori,Zulu,Xhosa,Southern Sotho' THEN 'Afrikaans,English,Maori,Southern Sotho,Xhosa,Zulu'
            WHEN "languages" = 'English,Afrikaans,Zulu,Portuguese' THEN 'Afrikaans,English,Portuguese,Zulu'
            WHEN "languages" = 'English,American Sign Language,Dutch,Italian,Russian,Swahili' THEN 'American Sign Language,Dutch,English,Italian,Russian,Swahili'
            WHEN "languages" = 'English,American Sign Language,Estonian' THEN 'American Sign Language,English,Estonian'
            WHEN "languages" = 'English,American Sign Language,Portuguese' THEN 'American Sign Language,English,Portuguese'
            WHEN "languages" = 'English,American Sign Language,Spanish' THEN 'American Sign Language,English,Spanish'
            WHEN "languages" = 'English,Amharic,Khmer,German,Chechen' THEN 'Amharic,Chechen,English,German,Khmer'
            WHEN "languages" = 'English,Arabic,Acholi' THEN 'Acholi,Arabic,English'
            WHEN "languages" = 'English,Arabic,French,German,Russian,Czech,Slovak,Dari,Pushto' THEN 'Arabic,Czech,Dari,English,French,German,Pushto,Russian,Slovak'
            WHEN "languages" = 'English,Arabic,Sioux' THEN 'Arabic,English,Sioux'
            WHEN "languages" = 'English,Arabic,Spanish,Japanese,Berber languages,French,Russian,Japanese Sign Language' THEN 'Arabic,Berber languages,English,French,Japanese,Japanese Sign Language,Russian,Spanish'
            WHEN "languages" = 'English,Berber languages,French' THEN 'Berber languages,English,French'
            WHEN "languages" = 'English,Brazilian Sign Language,Spanish' THEN 'Brazilian Sign Language,English,Spanish'
            WHEN "languages" = 'English,Cantonese,French,German,Hindi,Turkish' THEN 'Chinese,English,French,German,Hindi,Turkish'
            WHEN "languages" = 'English,Cantonese,German' THEN 'Chinese,English,German'
            WHEN "languages" = 'English,Cantonese,Italian' THEN 'Chinese,English,Italian'
            WHEN "languages" = 'English,Cantonese,Korean' THEN 'Chinese,English,Korean'
            WHEN "languages" = 'English,Cantonese,Latin' THEN 'Chinese,English,Latin'
            WHEN "languages" = 'English,Cantonese,Mandarin,Spanish' THEN 'Chinese,English,Spanish'
            WHEN "languages" = 'English,Chinese,Spanish' THEN 'Chinese,English,Spanish'
            WHEN "languages" = 'English,Dutch,French,Italian,Mandarin' THEN 'Chinese,Dutch,English,French,Italian'
            WHEN "languages" = 'English,French,Cantonese,German' THEN 'Chinese,English,French,German'
            WHEN "languages" = 'English,French,Cantonese,Gujarati,Yiddish' THEN 'Chinese,English,French,Gujarati,Yiddish'
            WHEN "languages" = 'English,French,Chinese' THEN 'Chinese,English,French'
            WHEN "languages" = 'English,French,Chinese,Albanian' THEN 'Albanian,Chinese,English,French'
            WHEN "languages" = 'English,French,German,Chinese,Italian,Arabic' THEN 'Arabic,Chinese,English,French,German,Italian'
            WHEN "languages" = 'English,French,German,Greek, Ancient (to 1453)' THEN 'English,French,German,Greek'
            WHEN "languages" = 'English,Egyptian (Ancient),Arabic' THEN 'Arabic,English,Egyptian'
            WHEN "languages" = 'English,French,Italian,German,Romany' THEN 'English,French,German,Italian,Romany'
            WHEN "languages" = 'English,French,Italian,Portuguese,Japanese' THEN 'English,French,Italian,Japanese,Portuguese'
            WHEN "languages" = 'English,French,Japanese,Mandarin,Latin' THEN 'Chinese,English,French,Japanese,Latin'
            WHEN "languages" = 'English,French,Klingon,Korean,Arabic' THEN 'Arabic,English,French,Korean'
            WHEN "languages" = 'English,French,Mandarin' THEN 'Chinese,English,French'
            WHEN "languages" = 'English,French,Portuguese,German' THEN 'English,French,German,Portuguese'
            WHEN "languages" = 'English,French,Russian,Bulgarian,Spanish' THEN 'Bulgarian,English,French,Russian,Spanish'
            WHEN "languages" = 'English,French,Russian,German,Spanish,Greek' THEN 'English,French,German,Greek,Russian,Spanish'
            WHEN "languages" = 'English,French,Spanish,German' THEN 'English,French,German,Spanish'
            WHEN "languages" = 'English,French,Spanish,Italian,German' THEN 'English,French,German,Italian,Spanish'
            WHEN "languages" = 'English,French,Spanish,Italian,Sign Languages,Russian' THEN 'English,French,Italian,Russian,Sign Languages,Spanish'
            WHEN "languages" = 'English,French,Spanish,Japanese' THEN 'English,French,Japanese,Spanish'
            WHEN "languages" = 'English,French,Tibetan,Mandarin,Russian,Hindi,Portuguese,Latin,Italian' THEN 'Chinese,English,French,Hindi,Italian,Latin,Portuguese,Russian,Tibetan'
            WHEN "languages" = 'English,French,Ukrainian,Russian,Hungarian' THEN 'English,French,Hungarian,Russian,Ukrainian'
            WHEN "languages" = 'English,French,Urdu,Arabic' THEN 'Arabic,English,French,Urdu'
            WHEN "languages" = 'English,German,Arabic,French,Cantonese' THEN 'Arabic,Chinese,English,French,German'
            WHEN "languages" = 'English,German,Arabic,Russian,French' THEN 'Arabic,English,French,German,Russian'
            WHEN "languages" = 'English,German,Arabic,Urdu' THEN 'Arabic,English,German,Urdu'
            WHEN "languages" = 'English,German,Cantonese' THEN 'Chinese,English,German'
            WHEN "languages" = 'English,German,Cantonese,Japanese,Hungarian' THEN 'Chinese,English,German,Hungarian,Japanese'
            WHEN "languages" = 'English,German,Danish,Mandarin,Cantonese' THEN 'Chinese,Danish,English,German'
            WHEN "languages" = 'English,German,Dutch,Polish,Latin' THEN 'Dutch,English,German,Latin,Polish'
            WHEN "languages" = 'English,German,French,Hebrew' THEN 'English,French,German,Hebrew'
            WHEN "languages" = 'English,German,French,Hebrew,Arabic,Italian,Greek,Russian' THEN 'Arabic,English,French,German,Greek,Hebrew,Italian,Russian'
            WHEN "languages" = 'English,German,French,Italian' THEN 'English,French,German,Italian'
            WHEN "languages" = 'English,German,French,Russian,Arabic,Italian' THEN 'Arabic,English,French,German,Italian,Russian'
            WHEN "languages" = 'English,German,French,Spanish,Latin' THEN 'English,French,German,Latin,Spanish'
            WHEN "languages" = 'English,German,French,Spanish,Russian' THEN 'English,French,German,Russian,Spanish'
            WHEN "languages" = 'English,German,French,Swedish' THEN 'English,French,German,Swedish'
            WHEN "languages" = 'English,German,Hebrew,Spanish' THEN 'Arabic,English,German,Hebrew,Spanish'
            WHEN "languages" = 'English,German,Hebrew,Spanish,Arabic,Nepali' THEN 'Arabic,English,German,Hebrew,Nepali,Spanish'
            WHEN "languages" = 'English,German,Italian,Arabic' THEN 'Arabic,English,German,Italian'
            WHEN "languages" = 'English,German,Italian,French,Spanish' THEN 'English,French,German,Italian,Spanish'
            WHEN "languages" = 'English,German,Italian,Japanese,Amharic,Russian' THEN 'Amharic,English,German,Italian,Japanese,Russian'
            WHEN "languages" = 'English,German,Italian,Mandarin,Spanish' THEN 'Chinese,English,German,Italian,Spanish'
            WHEN "languages" = 'English,German,Italian,Romanian,Spanish,Arabic,Georgian' THEN 'Arabic,English,Georgian,German,Italian,Romanian,Spanish'
            WHEN "languages" = 'English,German,Mandarin,Tibetan,Hindi' THEN 'Chinese,English,German,Hindi,Tibetan'
            WHEN "languages" = 'English,German,Polish,French' THEN 'English,French,German,Polish'
            WHEN "languages" = 'English,German,Russian,French,Flemish' THEN 'English,Flemish,French,German,Russian'
            WHEN "languages" = 'English,German,Spanish,Russian,Czech' THEN 'Czech,English,German,Russian,Spanish'
            WHEN "languages" = 'English,German,Swedish,American Sign Language' THEN 'American Sign Language,English,German,Swedish'
            WHEN "languages" = 'English,Greek, Ancient (to 1453)' THEN 'Ancient Greek,English'
            WHEN "languages" = 'English,Greek,French,Spanish' THEN 'English,French,Greek,Spanish'
            WHEN "languages" = 'English,Hawaiian,German,Japanese' THEN 'English,German,Hawaiian,Japanese'
            WHEN "languages" = 'English,Hawaiian,Mandarin,Turkish' THEN 'Chinese,English,Hawaiian,Turkish'
            WHEN "languages" = 'English,Hebrew,Arabic,German' THEN 'Arabic,English,German,Hebrew'
            WHEN "languages" = 'English,Hebrew,Arabic,Persian,Spanish' THEN 'Arabic,English,Hebrew,Persian,Spanish'
            WHEN "languages" = 'English,Hebrew,German,Polish' THEN 'English,German,Hebrew,Polish'
            WHEN "languages" = 'English,Hindi,German,Tibetan' THEN 'English,German,Hindi,Tibetan'
            WHEN "languages" = 'English,Hungarian,Spanish,French' THEN 'English,French,Hungarian,Spanish'
            WHEN "languages" = 'English,Icelandic,Filipino,Portuguese,French,Tagalog,German,Italian' THEN 'English,Filipino,French,German,Icelandic,Italian,Portuguese,Tagalog'
            WHEN "languages" = 'English,Icelandic,French,Italian,Russian' THEN 'English,French,Icelandic,Italian,Russian'
            WHEN "languages" = 'English,Icelandic,Russian,French' THEN 'English,French,Icelandic,Russian'
            WHEN "languages" = 'English,Indian Sign Language,North American Indian' THEN 'English,Indian Sign Language,Native American Languages'
            WHEN "languages" = 'English,Inuktitut,Croatian,Serbian' THEN 'Croatian,English,Inuktitut,Serbian'
            WHEN "languages" = 'English,Irish,Chinese,Latin' THEN 'Chinese,English,Irish,Latin'
            WHEN "languages" = 'English,Italian,Chinese' THEN 'English,Italian,Mandarin,Cantonese'
            WHEN "languages" = 'English,Italian,Japanese,Mandarin' THEN 'English,Italian,Japanese,Mandarin,Cantonese'
            WHEN "languages" = 'English,Italian,Latin,French,Swiss German,German,Chinese' THEN 'English,Italian,Latin,French,German,Mandarin,Cantonese'
            WHEN "languages" = 'English,Italian,Mandarin,Cantonese,German,Czech' THEN 'English,Italian,German,Czech,Mandarin,Cantonese'
            WHEN "languages" = 'English,Italian,Mandarin,Spanish' THEN 'English,Italian,Spanish,Mandarin,Cantonese'
            WHEN "languages" = 'English,Japanese,Cantonese,Mandarin' THEN 'English,Japanese,Mandarin,Cantonese'
            WHEN "languages" = 'English,Japanese,Chinese,Arabic' THEN 'English,Japanese,Arabic,Mandarin,Cantonese'
            WHEN "languages" = 'English,Japanese,Esperanto' THEN 'English,Japanese'
            WHEN "languages" = 'English,Korean,Cantonese,Spanish,German,Icelandic,Italian' THEN 'English,Korean,Spanish,German,Icelandic,Italian,Mandarin,Cantonese'
            WHEN "languages" = 'English,Klingon,German' THEN 'English,German'
            WHEN "languages" = 'English,Klingon,Russian,French' THEN 'English,Russian,French'
            WHEN "languages" = 'English,Mandarin,Italian' THEN 'English,Italian,Mandarin,Cantonese'
            WHEN "languages" = 'English,Mandarin,Kinyarwanda' THEN 'English, Chinese, Kinyarwanda'
            WHEN "languages" = 'English,Mandarin,Sanskrit' THEN 'English, Chinese, Sanskrit'
            WHEN "languages" = 'English,Mandarin,Sioux,Spanish' THEN 'English, Chinese, Sioux, Spanish'
            WHEN "languages" = 'English,Mandarin,Swiss German,Cantonese,Russian' THEN 'English, Chinese, Russian, Swiss German'
            WHEN "languages" = 'English,Navajo,Mandarin' THEN 'English, Chinese, Navajo'
            WHEN "languages" = 'English,Norse, Old,Latin' THEN 'English, Latin, Norse Old'
            WHEN "languages" = 'English,North American Indian' THEN 'English, North American Indian'
            WHEN "languages" = 'English,Nyanja,Afrikaans,Zulu,Xhosa,Southern Sotho' THEN 'Afrikaans, English, Nyanja, Southern Sotho, Xhosa, Zulu'
            WHEN "languages" = 'English,Persian,Spanish,Mandarin,Korean' THEN 'English, Chinese, Korean, Persian, Spanish'
            WHEN "languages" = 'English,Polynesian' THEN 'English, Polynesian'
            WHEN "languages" = 'English,Portuguese,French,Breton' THEN 'Breton, English, French, Portuguese'
            WHEN "languages" = 'English,Portuguese,French,Japanese' THEN 'English, French, Japanese, Portuguese'
            WHEN "languages" = 'English,Portuguese,Spanish,German,French' THEN 'English, French, German, Portuguese, Spanish'
            WHEN "languages" = 'English,Portuguese,Spanish,Italian' THEN 'English, Italian, Portuguese, Spanish'
            WHEN "languages" = 'English,Pushto' THEN 'English, Pashto'
            WHEN "languages" = 'English,Pushto,Dari' THEN 'Dari, English, Pashto'
            WHEN "languages" = 'English,Quenya,Old English,Sindarin' THEN 'English, Old English, Quenya, Sindarin'
            WHEN "languages" = 'English,Romanian,Greek,Bulgarian,Latin' THEN 'Bulgarian, English, Greek, Latin, Romanian'
            WHEN "languages" = 'English,Romanian,Hebrew,Polish,Armenian' THEN 'Armenian, English, Hebrew, Polish, Romanian'
            WHEN "languages" = 'English,Russian,French,Arabic,Swedish' THEN 'Arabic, English, French, Russian, Swedish'
            WHEN "languages" = 'English,Russian,French,Hawaiian,Spanish' THEN 'English, French, Hawaiian, Russian, Spanish'
            WHEN "languages" = 'English,Russian,French,Polish,German' THEN 'English, French, German, Polish, Russian'
            WHEN "languages" = 'English,Russian,German,French,Finnish' THEN 'English, Finnish, French, German, Russian'
            WHEN "languages" = 'English,Russian,German,Spanish' THEN 'English, German, Russian, Spanish'
            WHEN "languages" = 'English,Russian,Hindi' THEN 'English,Hindi,Russian'
            WHEN "languages" = 'English,Russian,Hungarian' THEN 'English,Hungarian,Russian'
            WHEN "languages" = 'English,Russian,Indonesian' THEN 'English,Indonesian,Russian'
            WHEN "languages" = 'English,Russian,Italian' THEN 'English,Italian,Russian'
            WHEN "languages" = 'English,Russian,Italian,Mandarin,French' THEN 'Chinese,English,French,Italian,Russian'
            WHEN "languages" = 'English,Russian,Korean' THEN 'English,Korean,Russian'
            WHEN "languages" = 'English,Russian,Panjabi,Arabic' THEN 'Arabic,English,Panjabi,Russian'
            WHEN "languages" = 'English,Russian,Serbian,Bosnian,Croatian' THEN 'Bosnian,Croatian,English,Russian,Serbian'
            WHEN "languages" = 'English,Russian,Spanish,Indonesian,Danish,Cantonese' THEN 'Chinese,Danish,English,Indonesian,Russian,Spanish'
            WHEN "languages" = 'English,Russian,Spanish,Korean' THEN 'English,Korean,Russian,Spanish'
            WHEN "languages" = 'English,Russian,Spanish,Romanian' THEN 'English,Romanian,Russian,Spanish'
            WHEN "languages" = 'English,Russian,Ukrainian,German,Arabic' THEN 'Arabic,English,German,Russian,Ukrainian'
            WHEN "languages" = 'English,Russian,Vietnamese,French' THEN 'English,French,Russian,Vietnamese'
            WHEN "languages" = 'English,Spanish,Cantonese' THEN 'Chinese,English,Spanish'
            WHEN "languages" = 'English,Spanish,Cantonese,Italian' THEN 'Chinese,English,Italian,Spanish'
            WHEN "languages" = 'English,Spanish,French,Arabic,Hebrew,Persian,French Sign Language,Japanese' THEN 'Arabic,English,French,French Sign Language,Hebrew,Japanese,Persian,Spanish'
            WHEN "languages" = 'English,Spanish,Japanese,German,French,Korean' THEN 'English,French,German,Japanese,Korean,Spanish'
            WHEN "languages" = 'English,Spanish,Mandarin' THEN 'Chinese,English,Spanish'
            WHEN "languages" = 'English,Spanish,Russian,German' THEN 'English,German,Russian,Spanish'
            WHEN "languages" = 'English,Spanish,Russian,Italian' THEN 'English,Italian,Russian,Spanish'
            WHEN "languages" = 'English,Spanish,Russian,Italian,French' THEN 'English,French,Italian,Russian,Spanish'
            WHEN "languages" = 'English,Swedish,Norwegian,Danish,Icelandic,French' THEN 'Danish,English,French,Icelandic,Norwegian,Swedish'
            WHEN "languages" = 'English,Syriac,Aramaic,Italian,Latin' THEN 'Aramaic,English,Italian,Latin,Syriac'
            WHEN "languages" = 'English,Syriac,Assyrian Neo-Aramaic' THEN 'Aramaic,English,Syriac'
            WHEN "languages" = 'English,Syriac,German,Greek,Hebrew,Latin,Aramaic' THEN 'Aramaic,English,German,Greek,Hebrew,Latin,Syriac'
            WHEN "languages" = 'English,Tagalog,Cantonese,Mandarin,Spanish' THEN 'Chinese,English,Spanish,Tagalog'
            WHEN "languages" = 'English,Tagalog,Spanish' THEN 'English,Spanish,Tagalog'
            WHEN "languages" = 'English,Tamil,French,Japanese,Hindi,Chinese' THEN 'Chinese,English,French,Hindi,Japanese,Tamil'
            WHEN "languages" = 'English,Thai,French' THEN 'English,French,Thai'
            WHEN "languages" = 'English,Thai,Spanish,Hebrew,French' THEN 'English,French,Hebrew,Spanish,Thai'
            WHEN "languages" = 'English,Tibetan,German' THEN 'English,German,Tibetan'
            WHEN "languages" = 'English,Tibetan,Mandarin' THEN 'Chinese,English,Tibetan'
            WHEN "languages" = 'English,Tibetan,Panjabi,German' THEN 'English,German,Panjabi,Tibetan'
            WHEN "languages" = 'English,Tok Pisin,Japanese,Greek' THEN 'English,Greek,Japanese,Tok Pisin'
            WHEN "languages" = 'English,Turkish,Greek,Mandarin,French' THEN 'Chinese,English,French,Greek,Turkish'
            WHEN "languages" = 'English,Turkish,Greek,Russian' THEN 'English,Greek,Russian,Turkish'
            WHEN "languages" = 'English,Ukrainian,German,Spanish,Russian,French,Arabic,Turkish' THEN 'Arabic,English,French,German,Russian,Spanish,Turkish,Ukrainian'
            WHEN "languages" = 'English,Ukrainian,Italian,Spanish' THEN 'English,Italian,Spanish,Ukrainian'
            WHEN "languages" = 'English,Ukrainian,Spanish' THEN 'English,Spanish,Ukrainian'
            WHEN "languages" = 'English,Urdu,Arabic,Persian,French,Mandarin' THEN 'Arabic,Chinese,English,French,Persian,Urdu'
            WHEN "languages" = 'English,Urdu,Mandarin' THEN 'Chinese,English,Urdu'
            WHEN "languages" = 'English,Vietnamese,Spanish,Thai' THEN 'English,Spanish,Thai,Vietnamese'
            WHEN "languages" = 'English,Welsh,Italian,Latin,Russian,Hungarian' THEN 'English,Hungarian,Italian,Latin,Russian,Welsh'
            WHEN "languages" = 'English,Yiddish,German' THEN 'English,German,Yiddish'
            WHEN "languages" = 'English,Yiddish,Hebrew' THEN 'English,Hebrew,Yiddish'
            WHEN "languages" = 'French,English,Creole' THEN 'Creole,English,French'
            WHEN "languages" = 'French,English,Russian,Japanese' THEN 'English,French,Japanese,Russian'
            WHEN "languages" = 'Greek,English,Arabic' THEN 'Arabic,English,Greek'
            WHEN "languages" = 'Hebrew,Arabic,German,English' THEN 'Arabic,English,German,Hebrew'
            WHEN "languages" = 'Hebrew,English,Arabic' THEN 'Arabic,English,Hebrew'
            WHEN "languages" = 'Hebrew,Spanish,English' THEN 'English,Hebrew,Spanish'
            WHEN "languages" = 'Hindi,English' THEN 'English,Hindi'
            WHEN "languages" = 'Hopi,English,Spanish' THEN 'English,Hopi,Spanish'
            WHEN "languages" = 'Hungarian,English' THEN 'English,Hungarian'
            WHEN "languages" = 'Indonesian,Japanese,English' THEN 'English,Indonesian,Japanese'
            WHEN "languages" = 'Korean,English' THEN 'English,Korean'
            WHEN "languages" = 'Mandarin,English,Cantonese,Vietnamese,Polish' THEN 'Chinese,English,Polish,Vietnamese'
            WHEN "languages" = 'Mandarin,English,French' THEN 'Chinese,English,French'
            WHEN "languages" = 'Mandarin,Japanese,English,Hindi,Shanghainese,Cantonese' THEN 'Chinese,English,Hindi,Japanese'
            WHEN "languages" = 'Nepali,English' THEN 'English,Nepali'
            WHEN "languages" = 'Portuguese,English' THEN 'English,Portuguese'
            WHEN "languages" = 'Slovenian,English' THEN 'English,Slovenian'
            WHEN "languages" = 'Spanish,English,Ewe' THEN 'English,Ewe,Spanish'
            WHEN "languages" = 'Spanish,English,Italian' THEN 'English,Italian,Spanish'
            ELSE "languages"
        END AS "languages",
        CASE
            WHEN "country" = 'UK,USA' THEN 'UK;USA'
            WHEN "country" = 'USA,UK' THEN 'USA;UK'
            WHEN "country" = 'USA,Canada' THEN 'USA;Canada'
            WHEN "country" = 'USA,Germany' THEN 'USA;Germany'
            WHEN "country" = 'Canada,USA' THEN 'Canada;USA'
            WHEN "country" = 'USA,Australia' THEN 'USA;Australia'
            WHEN "country" = 'USA,France' THEN 'USA;France'
            WHEN "country" = 'Germany,USA' THEN 'Germany;USA'
            WHEN "country" = 'France,USA' THEN 'France;USA'
            WHEN "country" = 'USA,Japan' THEN 'USA;Japan'
            WHEN "country" = 'Australia,USA' THEN 'Australia;USA'
            WHEN "country" = 'USA,Italy' THEN 'USA;Italy'
            WHEN "country" = 'UK,France,USA' THEN 'UK;France;USA'
            WHEN "country" = 'Japan,USA' THEN 'Japan;USA'
            WHEN "country" = 'USA,New Zealand' THEN 'USA;New Zealand'
            WHEN "country" = 'USA,Spain' THEN 'USA;Spain'
            WHEN "country" = 'USA,UK,France' THEN 'USA;UK;France'
            WHEN "country" = 'Italy,USA' THEN 'Italy;USA'
            WHEN "country" = 'USA,Germany,UK' THEN 'USA;Germany;UK'
            WHEN "country" = 'USA,Mexico' THEN 'USA;Mexico'
            WHEN "country" = 'USA,United Arab Emirates' THEN 'USA;United Arab Emirates'
            WHEN "country" = 'USA,Germany,Canada' THEN 'USA;Germany;Canada'
            WHEN "country" = 'USA,India' THEN 'USA;India'
            WHEN "country" = 'USA,West Germany' THEN 'USA;Germany'
            WHEN "country" = 'USA,China' THEN 'USA;China'
            WHEN "country" = 'USA,Hong Kong' THEN 'USA;Hong Kong'
            WHEN "country" = 'USA,UK,Germany' THEN 'USA;UK;Germany'
            WHEN "country" = 'France,UK,USA' THEN 'France;UK;USA'
            WHEN "country" = 'Spain,USA' THEN 'Spain;USA'
            WHEN "country" = 'USA,UK,Canada' THEN 'USA;UK;Canada'
            WHEN "country" = 'New Zealand,USA' THEN 'New Zealand;USA'
            WHEN "country" = 'UK,Germany,USA' THEN 'UK;Germany;USA'
            WHEN "country" = 'USA,Canada,UK' THEN 'USA;Canada;UK'
            WHEN "country" = 'USA,Czech Republic' THEN 'USA;Czech Republic'
            WHEN "country" = 'Mexico,USA' THEN 'Mexico;USA'
            WHEN "country" = 'UK,USA,France' THEN 'UK;USA;France'
            WHEN "country" = 'USA,Germany,France' THEN 'USA;Germany;France'
            WHEN "country" = 'USA,Ireland' THEN 'USA;Ireland'
            WHEN "country" = 'USA,Netherlands' THEN 'USA;Netherlands'
            WHEN "country" = 'USA,UK,Australia' THEN 'USA;UK;Australia'
            WHEN "country" = 'Ireland,UK,USA' THEN 'Ireland;UK;USA'
            WHEN "country" = 'Ireland,USA' THEN 'Ireland;USA'
            WHEN "country" = 'Russia,USA' THEN 'Russia;USA'
            WHEN "country" = 'UK,Canada,USA' THEN 'UK;Canada;USA'
            WHEN "country" = 'UK,USA,Germany' THEN 'UK;USA;Germany'
            WHEN "country" = 'USA,France,UK' THEN 'USA;France;UK'
            WHEN "country" = 'USA,Russia' THEN 'USA;Russia'
            WHEN "country" = 'USA,South Africa' THEN 'USA;South Africa'
            WHEN "country" = 'Canada,USA,Japan' THEN 'Canada;USA;Japan'
            WHEN "country" = 'West Germany,USA' THEN 'Germany,USA'
            WHEN "country" = 'Australia,USA,Israel,UK' THEN 'Australia,USA,Israel,United Kingdom'
            WHEN "country" = 'Austria,UK,USA' THEN 'Austria,United Kingdom,USA'
            WHEN "country" = 'Belgium,Netherlands,USA,UK' THEN 'Belgium,Netherlands,USA,United Kingdom'
            WHEN "country" = 'Canada,UK,Iceland,USA,Australia' THEN 'Canada,United Kingdom,Iceland,USA,Australia'
            WHEN "country" = 'Canada,USA,France,Germany,UK' THEN 'Canada,USA,France,Germany,United Kingdom'
            WHEN "country" = 'Canada,USA,India,UK' THEN 'Canada,USA,India,United Kingdom'
            WHEN "country" = 'Canada,USA,Russia,South Korea,Switzerland,UK' THEN 'Canada,USA,Russia,South Korea,Switzerland,United Kingdom'
            WHEN "country" = 'Canada,USA,UK' THEN 'Canada,USA,United Kingdom'
            WHEN "country" = 'Canada,USA,UK,Australia' THEN 'Canada,USA,United Kingdom,Australia'
            WHEN "country" = 'Denmark,Argentina,Spain,Germany,Netherlands,Italy,USA,UK,France,Sweden,Finland,Iceland,Norway' THEN 'Denmark,Argentina,Spain,Germany,Netherlands,Italy,USA,United Kingdom,France,Sweden,Finland,Iceland,Norway'
            WHEN "country" = 'France,Australia,Germany,UK,USA' THEN 'France,Australia,Germany,United Kingdom,USA'
            WHEN "country" = 'France,UK,Germany,USA' THEN 'France,United Kingdom,Germany,USA'
            WHEN "country" = 'France,UK,Germany,USA,Japan' THEN 'France,United Kingdom,Germany,USA,Japan'
            WHEN "country" = 'France,UK,South Africa,USA' THEN 'France,United Kingdom,South Africa,USA'
            WHEN "country" = 'France,USA,Spain,UK' THEN 'France,USA,Spain,United Kingdom'
            WHEN "country" = 'Spain,West Germany,UK,USA' THEN 'Spain,Germany,UK,USA'
            WHEN "country" = 'UK,Australia,USA' THEN 'United Kingdom,Australia,USA'
            WHEN "country" = 'UK,Bulgaria,Germany,USA' THEN 'United Kingdom,Bulgaria,Germany,USA'
            WHEN "country" = 'UK,Canada,Romania,USA' THEN 'United Kingdom,Canada,Romania,USA'
            WHEN "country" = 'UK,China,USA' THEN 'United Kingdom,China,USA'
            WHEN "country" = 'UK,Czech Republic,Germany,USA' THEN 'United Kingdom,Czech Republic,Germany,USA'
            WHEN "country" = 'UK,Czech Republic,USA,Germany,Bahamas' THEN 'United Kingdom,Czech Republic,USA,Germany,Bahamas'
            WHEN "country" = 'UK,Denmark,USA' THEN 'United Kingdom,Denmark,USA'
            WHEN "country" = 'UK,France,Egypt,Japan,Mexico,USA,Iran' THEN 'United Kingdom,France,Egypt,Japan,Mexico,USA,Iran'
            WHEN "country" = 'UK,France,Germany,Ireland,USA' THEN 'United Kingdom,France,Germany,Ireland,USA'
            WHEN "country" = 'UK,France,Germany,USA' THEN 'United Kingdom,France,Germany,USA'
            WHEN "country" = 'UK,France,South Korea,USA' THEN 'United Kingdom,France,South Korea,USA'
            WHEN "country" = 'UK,France,USA,Brazil' THEN 'United Kingdom,France,USA,Brazil'
            WHEN "country" = 'UK,France,USA,Ireland' THEN 'United Kingdom,France,USA,Ireland'
            WHEN "country" = 'UK,Germany,France,USA,Japan' THEN 'United Kingdom,Germany,France,USA,Japan'
            WHEN "country" = 'UK,Germany,Hungary,USA' THEN 'United Kingdom,Germany,Hungary,USA'
            WHEN "country" = 'UK,Germany,Ireland,USA' THEN 'United Kingdom,Germany,Ireland,USA'
            WHEN "country" = 'UK,Germany,Japan,New Zealand,USA' THEN 'United Kingdom,Germany,Japan,New Zealand,USA'
            WHEN "country" = 'UK,Germany,Japan,USA' THEN 'United Kingdom,Germany,Japan,USA'
            WHEN "country" = 'UK,Germany,Spain,USA' THEN 'United Kingdom,Germany,Spain,USA'
            WHEN "country" = 'UK,Germany,Sweden,Belgium,USA' THEN 'United Kingdom,Germany,Sweden,Belgium,USA'
            WHEN "country" = 'UK,Germany,USA,Australia,France' THEN 'United Kingdom,Germany,USA,Australia,France'
            WHEN "country" = 'UK,Germany,USA,Canada' THEN 'United Kingdom,Germany,USA,Canada'
            WHEN "country" = 'UK,Germany,USA,China' THEN 'United Kingdom,Germany,USA,China'
            WHEN "country" = 'UK,Italy,France,USA' THEN 'United Kingdom,Italy,France,USA'
            WHEN "country" = 'UK,Italy,USA' THEN 'United Kingdom,Italy,USA'
            WHEN "country" = 'UK,Mexico,USA' THEN 'United Kingdom,Mexico,USA'
            WHEN "country" = 'UK,Netherlands,USA' THEN 'United Kingdom,Netherlands,USA'
            WHEN "country" = 'UK,Romania,France,USA' THEN 'United Kingdom,Romania,France,USA'
            WHEN "country" = 'UK,Russia,Ireland,Luxembourg,USA' THEN 'United Kingdom,Russia,Ireland,Luxembourg,USA'
            WHEN "country" = 'UK,Spain,Germany,USA' THEN 'United Kingdom,Spain,Germany,USA'
            WHEN "country" = 'UK,USA,Australia' THEN 'United Kingdom,USA,Australia'
            WHEN "country" = 'UK,USA,Australia,Japan' THEN 'United Kingdom,USA,Australia,Japan'
            WHEN "country" = 'UK,USA,Canada,Spain' THEN 'United Kingdom,USA,Canada,Spain'
            WHEN "country" = 'UK,USA,France,Canada' THEN 'United Kingdom,USA,France,Canada'
            WHEN "country" = 'UK,USA,France,Germany' THEN 'United Kingdom,USA,France,Germany'
            WHEN "country" = 'UK,USA,France,Germany,Czech Republic' THEN 'United Kingdom,USA,France,Germany,Czech Republic'
            WHEN "country" = 'UK,USA,France,Italy' THEN 'United Kingdom,USA,France,Italy'
            WHEN "country" = 'UK,USA,France,Sweden' THEN 'United Kingdom,USA,France,Sweden'
            WHEN "country" = 'UK,USA,Germany,Czech Republic' THEN 'United Kingdom,USA,Germany,Czech Republic'
            WHEN "country" = 'UK,USA,Hungary' THEN 'United Kingdom,USA,Hungary'
            WHEN "country" = 'UK,USA,India' THEN 'United Kingdom,USA,India'
            WHEN "country" = 'UK,USA,India,South Africa' THEN 'United Kingdom,USA,India,South Africa'
            WHEN "country" = 'UK,USA,Italy' THEN 'United Kingdom,USA,Italy'
            WHEN "country" = 'UK,USA,Italy,South Africa,Canada' THEN 'United Kingdom,USA,Italy,South Africa,Canada'
            WHEN "country" = 'UK,USA,Luxembourg' THEN 'United Kingdom,USA,Luxembourg'
            WHEN "country" = 'USA,Germany,Czech Republic,UK' THEN 'USA,Germany,Czech Republic,United Kingdom'
            WHEN "country" = 'USA,Germany,Ireland,UK' THEN 'USA,Germany,Ireland,United Kingdom'
            WHEN "country" = 'USA,Germany,Japan,UK' THEN 'USA,Germany,Japan,United Kingdom'
            WHEN "country" = 'USA,Germany,Norway,UK,Montenegro' THEN 'USA,Germany,Norway,United Kingdom,Montenegro'
            WHEN "country" = 'USA,Germany,UK,Canada' THEN 'USA,Germany,United Kingdom,Canada'
            WHEN "country" = 'USA,Germany,UK,Italy' THEN 'USA,Germany,United Kingdom,Italy'
            WHEN "country" = 'USA,Germany,UK,Japan' THEN 'USA,Germany,United Kingdom,Japan'
            WHEN "country" = 'USA,Hong Kong,UK' THEN 'USA,Hong Kong,United Kingdom'
            WHEN "country" = 'USA,Hungary,UK' THEN 'USA,Hungary,United Kingdom'
            WHEN "country" = 'USA,Ireland,UK' THEN 'USA,Ireland,United Kingdom'
            WHEN "country" = 'USA,Italy,Luxembourg,UK' THEN 'USA,Italy,Luxembourg,United Kingdom'
            WHEN "country" = 'USA,Italy,UK' THEN 'USA,Italy,United Kingdom'
            WHEN "country" = 'USA,Malta,France,UK' THEN 'USA,Malta,France,United Kingdom'
            WHEN "country" = 'USA,Malta,UK' THEN 'USA,Malta,United Kingdom'
            WHEN "country" = 'USA,Netherlands,UK' THEN 'USA,Netherlands,United Kingdom'
            WHEN "country" = 'USA,Netherlands,UK,Denmark' THEN 'USA,Netherlands,United Kingdom,Denmark'
            WHEN "country" = 'USA,Portugal,West Germany,France,Spain,Netherlands,UK' THEN 'USA,Portugal,Germany,France,Spain,Netherlands,UK'
            WHEN "country" = 'USA,UK,Japan,West Germany' THEN 'USA,UK,Japan,Germany'
            WHEN "country" = 'USA,West Germany,UK' THEN 'USA,Germany,UK'
            WHEN "country" = 'West Germany,USA,Austria' THEN 'Germany,USA,Austria'
            ELSE "country"
        END AS "country",
        CASE
            WHEN "runtime" = '1 hr. 32 min.' THEN '92 min'
            WHEN "runtime" = '1 hr. 34 min.' THEN '94 min'
            WHEN "runtime" = '1 hr. 38 min.' THEN '98 min'
            WHEN "runtime" = '1 hr. 30 min.' THEN '90 min'
            WHEN "runtime" = '1 hr. 45 min.' THEN '105 min'
            WHEN "runtime" = '1 hr. 33 min.' THEN '93 min'
            WHEN "runtime" = '1 hr. 31 min.' THEN '91 min'
            WHEN "runtime" = '1 hr. 35 min.' THEN '95 min'
            WHEN "runtime" = '1 hr. 36 min.' THEN '96 min'
            WHEN "runtime" = '1 hr. 39 min.' THEN '99 min'
            WHEN "runtime" = '1 hr. 56 min.' THEN '116 min'
            WHEN "runtime" = '1 hr. 57 min.' THEN '117 min'
            WHEN "runtime" = '2 hr. 8 min.' THEN '128 min'
            WHEN "runtime" = '1 hr. 21 min.' THEN '81 min'
            WHEN "runtime" = '1 hr. 28 min.' THEN '88 min'
            WHEN "runtime" = '1 hr. 41 min.' THEN '101 min'
            WHEN "runtime" = '1 hr. 42 min.' THEN '102 min'
            WHEN "runtime" = '1 hr. 43 min.' THEN '103 min'
            WHEN "runtime" = '1 hr. 44 min.' THEN '104 min'
            WHEN "runtime" = '1 hr. 46 min.' THEN '106 min'
            WHEN "runtime" = '1 hr. 47 min.' THEN '107 min'
            WHEN "runtime" = '1 hr. 49 min.' THEN '109 min'
            WHEN "runtime" = '1 hr. 50 min.' THEN '110 min'
            WHEN "runtime" = '1 hr. 59 min.' THEN '119 min'
            WHEN "runtime" = '192 min' THEN '3 hr. 12 min.'
            WHEN "runtime" = '197 min' THEN '3 hr. 17 min.'
            WHEN "runtime" = '201 min' THEN '3 hr. 21 min.'
            WHEN "runtime" = '237 min' THEN '3 hr. 57 min.'
            WHEN "runtime" = '48 min' THEN '0 hr. 48 min.'
            WHEN "runtime" = '57 min' THEN '0 hr. 57 min.'
            WHEN "runtime" = '59 min' THEN '0 hr. 59 min.'
            WHEN "runtime" = '159 min' THEN '2 hr. 39 min.'
            WHEN "runtime" = '163 min' THEN '2 hr. 43 min.'
            WHEN "runtime" = '166 min' THEN '2 hr. 46 min.'
            WHEN "runtime" = '168 min' THEN '2 hr. 48 min.'
            WHEN "runtime" = '183 min' THEN '3 hr. 3 min.'
            WHEN "runtime" = '184 min' THEN '3 hr. 4 min.'
            WHEN "runtime" = '186 min' THEN '3 hr. 6 min.'
            WHEN "runtime" = '187 min' THEN '3 hr. 7 min.'
            WHEN "runtime" = '188 min' THEN '3 hr. 8 min.'
            WHEN "runtime" = '191 min' THEN '3 hr. 11 min.'
            WHEN "runtime" = '194 min' THEN '3 hr. 14 min.'
            WHEN "runtime" = '195 min' THEN '3 hr. 15 min.'
            WHEN "runtime" = '200 min' THEN '3 hr. 20 min.'
            WHEN "runtime" = '202 min' THEN '3 hr. 22 min.'
            WHEN "runtime" = '208 min' THEN '3 hr. 28 min.'
            WHEN "runtime" = '212 min' THEN '3 hr. 32 min.'
            WHEN "runtime" = '219 min' THEN '3 hr. 39 min.'
            WHEN "runtime" = '220 min' THEN '3 hr. 40 min.'
            WHEN "runtime" = '229 min' THEN '3 hr. 49 min.'
            WHEN "runtime" = '3 hr. 12 min.' THEN '192 min'
            WHEN "runtime" = '3 hr. 15 min.' THEN '195 min'
            WHEN "runtime" = '3 hr. 3 min.' THEN '183 min'
            WHEN "runtime" = '3 hr. 8 min.' THEN '188 min'
            ELSE "runtime"
        END AS "runtime",
        CASE
            WHEN "average_rating" = '7.6/10' THEN '7.6'
            WHEN "average_rating" = '4.4/10,4.1/10' THEN '4.4'
            WHEN "average_rating" = '6.7/10' THEN '6.7'
            WHEN "average_rating" = '6.4/10' THEN '6.4'
            WHEN "average_rating" = '7.2/10' THEN '7.2'
            WHEN "average_rating" = '6.5/10' THEN '6.5'
            WHEN "average_rating" = '7.1/10' THEN '7.1'
            WHEN "average_rating" = '7.0/10' THEN '7.0'
            WHEN "average_rating" = '6.6/10' THEN '6.6'
            WHEN "average_rating" = '6.8/10' THEN '6.8'
            WHEN "average_rating" = '6.2/10' THEN '6.2'
            WHEN "average_rating" = '7.3/10' THEN '7.3'
            WHEN "average_rating" = '6.9/10' THEN '6.9'
            WHEN "average_rating" = '6.3/10' THEN '6.3'
            WHEN "average_rating" = '5.9/10' THEN '5.9'
            WHEN "average_rating" = '6.1/10' THEN '6.1'
            WHEN "average_rating" = '7.4/10' THEN '7.4'
            WHEN "average_rating" = '5.8/10' THEN '5.8'
            WHEN "average_rating" = '6.0/10' THEN '6.0'
            WHEN "average_rating" = '7.5/10' THEN '7.5'
            WHEN "average_rating" = '5.7/10' THEN '5.7'
            WHEN "average_rating" = '7.7/10' THEN '7.7'
            WHEN "average_rating" = '5.6/10' THEN '5.6'
            WHEN "average_rating" = '7.8/10' THEN '7.8'
            WHEN "average_rating" = '5.5/10' THEN '5.5'
            WHEN "average_rating" = '5.4/10' THEN '5.4'
            WHEN "average_rating" = '8.0/10' THEN '8.0'
            WHEN "average_rating" = '5.1/10' THEN '5.1'
            WHEN "average_rating" = '5.3/10' THEN '5.3'
            WHEN "average_rating" = '7.9/10' THEN '7.9'
            WHEN "average_rating" = '5.2/10' THEN '5.2'
            WHEN "average_rating" = '8.1/10' THEN '8.1'
            WHEN "average_rating" = '5.0/10' THEN '5.0'
            WHEN "average_rating" = '4.9/10' THEN '4.9'
            WHEN "average_rating" = '4.7/10' THEN '4.7'
            WHEN "average_rating" = '4.8/10' THEN '4.8'
            WHEN "average_rating" = '4.4/10' THEN '4.4'
            WHEN "average_rating" = '4.2/10' THEN '4.2'
            WHEN "average_rating" = '4.3/10' THEN '4.3'
            WHEN "average_rating" = '8.2/10' THEN '8.2'
            WHEN "average_rating" = '4.5/10' THEN '4.5'
            WHEN "average_rating" = '8.3/10' THEN '8.3'
            WHEN "average_rating" = '4.6/10' THEN '4.6'
            WHEN "average_rating" = '8.4/10' THEN '8.4'
            WHEN "average_rating" = '4.1/10' THEN '4.1'
            WHEN "average_rating" = '4.0/10' THEN '4.0'
            WHEN "average_rating" = '3.7/10' THEN '3.7'
            WHEN "average_rating" = '3.8/10' THEN '3.8'
            WHEN "average_rating" = '3.9/10' THEN '3.9'
            WHEN "average_rating" = '8.5/10' THEN '8.5'
            WHEN "average_rating" = '3.4/10' THEN '3.4'
            WHEN "average_rating" = '4.4/10,4.5/10' THEN '4.4'
            WHEN "average_rating" = '5.2/10,4.9/10' THEN '5.2'
            WHEN "average_rating" = '5.2/10,5/10' THEN '5.2'
            WHEN "average_rating" = '5.4/10,5.2/10' THEN '5.4'
            WHEN "average_rating" = '5.4/10,5.4/10' THEN '5.4'
            WHEN "average_rating" = '6.2/10,6.1/10' THEN '6.2'
            WHEN "average_rating" = '6.5/10,5.8/10' THEN '6.5'
            WHEN "average_rating" = '6.8/10,7/10' THEN '6.8'
            WHEN "average_rating" = '6/10' THEN '6.0'
            WHEN "average_rating" = '7.3/10,7.6/10' THEN '7.3'
            WHEN "average_rating" = '2.4/10' THEN '2.4'
            WHEN "average_rating" = '2.4/10,3.6/10' THEN '2.4'
            WHEN "average_rating" = '2.9/10,3.3/10' THEN '2.9'
            WHEN "average_rating" = '3.1/10,2.9/10' THEN '3.1'
            WHEN "average_rating" = '3.1/10,3.6/10' THEN '3.1/10'
            WHEN "average_rating" = '3.3/10,3.5/10' THEN '3.3/10'
            WHEN "average_rating" = '3.3/10,3.9/10' THEN '3.3/10'
            WHEN "average_rating" = '3.4/10,3.6/10' THEN '3.4/10'
            WHEN "average_rating" = '3.7/10,4.1/10' THEN '3.7/10'
            WHEN "average_rating" = '3.7/10,4.3/10' THEN '3.7/10'
            WHEN "average_rating" = '3.8/10,3.4/10' THEN '3.8/10'
            WHEN "average_rating" = '3.8/10,3.8/10' THEN '3.8/10'
            WHEN "average_rating" = '3.9/10,3.9/10' THEN '3.9/10'
            WHEN "average_rating" = '4.2/10,3.7/10' THEN '4.2/10'
            WHEN "average_rating" = '4.4/10,4.9/10' THEN '4.4/10'
            WHEN "average_rating" = '4.4/10,5.1/10' THEN '4.4/10'
            WHEN "average_rating" = '4.5/10,2.3/10' THEN '4.5/10'
            WHEN "average_rating" = '4.6/10,3.8/10' THEN '4.6/10'
            WHEN "average_rating" = '4.6/10,4.6/10' THEN '4.6/10'
            WHEN "average_rating" = '4.6/10,4.7/10' THEN '4.6/10'
            WHEN "average_rating" = '4.7/10,4.2/10' THEN '4.7/10'
            WHEN "average_rating" = '4.8/10,4.4/10' THEN '4.8/10'
            WHEN "average_rating" = '4.8/10,4.9/10' THEN '4.8/10'
            WHEN "average_rating" = '4.9/10,4.4/10' THEN '4.9/10'
            WHEN "average_rating" = '4.9/10,4.9/10' THEN '4.9/10'
            WHEN "average_rating" = '4/10,3.9/10' THEN '4.0/10'
            WHEN "average_rating" = '4/10,4.2/10' THEN '4.0/10'
            WHEN "average_rating" = '5.1/10,5/10' THEN '5.1/10'
            WHEN "average_rating" = '5.2/10,4.6/10' THEN '5.2/10'
            WHEN "average_rating" = '5.3/10,4.8/10' THEN '5.3/10'
            WHEN "average_rating" = '5.3/10,6/10' THEN '5.3/10'
            WHEN "average_rating" = '5.4/10,4.2/10' THEN '5.4/10'
            WHEN "average_rating" = '5.4/10,4.9/10' THEN '5.4/10'
            WHEN "average_rating" = '5.4/10,5.1/10' THEN '5.4/10'
            WHEN "average_rating" = '5.4/10,6/10' THEN '5.4/10'
            WHEN "average_rating" = '5.5/10,6.1/10' THEN '5.5/10'
            WHEN "average_rating" = '5.6/10,5.5/10' THEN '5.6/10'
            WHEN "average_rating" = '5.6/10,7/10' THEN '5.6/10'
            WHEN "average_rating" = '5.7/10,5.5/10' THEN '5.7/10'
            WHEN "average_rating" = '5.7/10,6.1/10' THEN '5.7/10'
            WHEN "average_rating" = '5.7/10,6.3/10' THEN '5.7/10'
            WHEN "average_rating" = '5.7/10,6.6/10' THEN '5.7/10'
            WHEN "average_rating" = '5.8/10,5.4/10' THEN '5.8/10'
            WHEN "average_rating" = '5.8/10,5.5/10' THEN '5.8/10'
            WHEN "average_rating" = '5.9/10,5.9/10' THEN '5.9/10'
            WHEN "average_rating" = '5/10,5/10' THEN '5/10'
            WHEN "average_rating" = '6.2/10,6.2/10' THEN '6.2/10'
            WHEN "average_rating" = '6.5/10,6.5/10' THEN '6.5/10'
            WHEN "average_rating" = '5/10' THEN '5.0/10'
            WHEN "average_rating" = '9.1' THEN '9.1/10'
            WHEN "average_rating" = '9.2' THEN '9.2/10'
            WHEN "average_rating" = '9.7' THEN '9.7/10'
            ELSE "average_rating"
        END AS "average_rating",
        "number_of_ratings",
        "number_of_reviews",
        CASE
            WHEN "genres" = 'Comedy,Romance' THEN 'Comedy, Romance'
            WHEN "genres" = 'Comedy,Drama,Romance' THEN 'Comedy, Drama, Romance'
            WHEN "genres" = 'Comedy,Drama' THEN 'Comedy, Drama'
            WHEN "genres" = 'Drama,Romance' THEN 'Drama, Romance'
            WHEN "genres" = 'Horror,Thriller' THEN 'Horror, Thriller'
            WHEN "genres" = 'Action,Crime,Drama' THEN 'Action, Crime, Drama'
            WHEN "genres" = 'Animation,Adventure,Comedy' THEN 'Adventure, Animation, Comedy'
            WHEN "genres" = 'Crime,Drama,Thriller' THEN 'Crime, Drama, Thriller'
            WHEN "genres" = 'Action,Adventure,Comedy' THEN 'Action, Adventure, Comedy'
            WHEN "genres" = 'Action,Crime,Thriller' THEN 'Action, Crime, Thriller'
            WHEN "genres" = 'Drama,Thriller' THEN 'Drama, Thriller'
            WHEN "genres" = 'Comedy,Drama,Family' THEN 'Comedy, Drama, Family'
            WHEN "genres" = 'Drama,Family' THEN 'Drama, Family'
            WHEN "genres" = 'Action,Adventure,Sci-Fi' THEN 'Action, Adventure, Sci-Fi'
            WHEN "genres" = 'Comedy,Horror' THEN 'Comedy, Horror'
            WHEN "genres" = 'Comedy,Family' THEN 'Comedy, Family'
            WHEN "genres" = 'Crime,Drama' THEN 'Crime, Drama'
            WHEN "genres" = 'Action,Comedy,Crime' THEN 'Action, Comedy, Crime'
            WHEN "genres" = 'Adventure,Comedy,Family' THEN 'Adventure, Comedy, Family'
            WHEN "genres" = 'Crime,Drama,Mystery' THEN 'Crime, Drama, Mystery'
            WHEN "genres" = 'Action,Adventure,Fantasy' THEN 'Action, Adventure, Fantasy'
            WHEN "genres" = 'Horror,Mystery,Thriller' THEN 'Horror, Mystery, Thriller'
            WHEN "genres" = 'Comedy,Family,Fantasy' THEN 'Comedy, Family, Fantasy'
            WHEN "genres" = 'Action,Adventure,Drama' THEN 'Action, Adventure, Drama'
            WHEN "genres" = 'Crime,Drama,Film-Noir' THEN 'Crime, Drama, Film-Noir'
            WHEN "genres" = 'Comedy,Crime,Drama' THEN 'Comedy, Crime, Drama'
            WHEN "genres" = 'Horror,Sci-Fi' THEN 'Horror, Sci-Fi'
            WHEN "genres" = 'Biography,Drama' THEN 'Biography, Drama'
            WHEN "genres" = 'Adventure,Family,Fantasy' THEN 'Adventure, Family, Fantasy'
            WHEN "genres" = 'Animation,Adventure,Family' THEN 'Adventure, Animation, Family'
            WHEN "genres" = 'Biography,Drama,History' THEN 'Biography, Drama, History'
            WHEN "genres" = 'Comedy,Crime' THEN 'Comedy, Crime'
            WHEN "genres" = 'Comedy,Musical,Romance' THEN 'Comedy, Musical, Romance'
            WHEN "genres" = 'Drama,Mystery,Thriller' THEN 'Drama, Mystery, Thriller'
            WHEN "genres" = 'Action,Adventure,Thriller' THEN 'Action, Adventure, Thriller'
            WHEN "genres" = 'Action,Thriller' THEN 'Action, Thriller'
            WHEN "genres" = 'Horror,Sci-Fi,Thriller' THEN 'Horror, Sci-Fi, Thriller'
            WHEN "genres" = 'Animation,Comedy,Family' THEN 'Animation, Comedy, Family'
            WHEN "genres" = 'Adventure,Comedy,Drama' THEN 'Adventure, Comedy, Drama'
            WHEN "genres" = 'Drama,Horror,Thriller' THEN 'Drama, Horror, Thriller'
            WHEN "genres" = 'Adventure,Drama,Family' THEN 'Adventure, Drama, Family'
            WHEN "genres" = 'Animation,Action,Adventure' THEN 'Action, Adventure, Animation'
            WHEN "genres" = 'Drama,War' THEN 'Drama, War'
            WHEN "genres" = 'Drama,Comedy' THEN 'Comedy,Drama'
            WHEN "genres" = 'Family,Comedy' THEN 'Comedy,Family'
            WHEN "genres" = 'Short,Drama' THEN 'Drama,Short'
            WHEN "genres" = 'Documentary,Biography,Family' THEN 'Biography,Documentary,Family'
            WHEN "genres" = 'Documentary,Biography,History' THEN 'Biography,Documentary,History'
            WHEN "genres" = 'Documentary,Comedy' THEN 'Comedy,Documentary'
            WHEN "genres" = 'Action & Adventure,Science Fiction & Fantasy' THEN 'Action,Adventure,Fantasy,Science Fiction'
            WHEN "genres" = 'Adventure,Drama,Sci-Fi' THEN 'Adventure,Drama,Science Fiction'
            WHEN "genres" = 'Adventure,Sci-Fi,Thriller' THEN 'Adventure,Science Fiction,Thriller'
            WHEN "genres" = 'Animation,Adventure,Drama' THEN 'Adventure,Animation,Drama'
            WHEN "genres" = 'Documentary,Crime' THEN 'Crime,Documentary'
            WHEN "genres" = 'Drama,Mystery,Sci-Fi' THEN 'Drama,Mystery,Science Fiction'
            WHEN "genres" = 'Family,Drama' THEN 'Drama,Family'
            WHEN "genres" = 'Horror,Mystery,Sci-Fi' THEN 'Horror,Mystery,Science Fiction'
            WHEN "genres" = 'Sci-Fi,Horror' THEN 'Horror,Science Fiction'
            WHEN "genres" = 'Short,Comedy' THEN 'Comedy,Short'
            WHEN "genres" = 'Comedy,Kids & Family' THEN 'Comedy,Family'
            WHEN "genres" = 'Drama,Kids & Family' THEN 'Drama,Family'
            WHEN "genres" = 'Drama,Romance,Comedy' THEN 'Comedy,Drama,Romance'
            WHEN "genres" = 'Mystery & Suspense,Drama' THEN 'Drama,Mystery'
            WHEN "genres" = 'Romance,Drama' THEN 'Drama,Romance'
            WHEN "genres" = 'Action & Adventure,Comedy' THEN 'Action,Adventure,Comedy'
            WHEN "genres" = 'Animation,Family,Comedy' THEN 'Animation,Comedy,Family'
            WHEN "genres" = 'Animation,Family,Music' THEN 'Animation,Family,Musical'
            WHEN "genres" = 'Documentary,Biography,Comedy' THEN 'Biography,Comedy,Documentary'
            WHEN "genres" = 'Documentary,Biography,Sport' THEN 'Biography,Documentary,Sport'
            WHEN "genres" = 'Drama,Action & Adventure,Mystery & Suspense' THEN 'Action,Drama,Mystery,Suspense'
            WHEN "genres" = 'Drama,Horror,Mystery & Suspense' THEN 'Drama,Horror,Mystery,Suspense'
            WHEN "genres" = 'Family,Documentary' THEN 'Documentary,Family'
            WHEN "genres" = 'Mystery & Suspense,Action & Adventure' THEN 'Action,Adventure,Mystery,Suspense'
            WHEN "genres" = 'Mystery & Suspense,Horror' THEN 'Horror,Mystery,Suspense'
            WHEN "genres" = 'Action & Adventure,Science Fiction & Fantasy,Comedy' THEN 'Action,Adventure,Comedy,Fantasy,Science Fiction'
            WHEN "genres" = 'Adventure,Family,Drama' THEN 'Adventure,Drama,Family'
            WHEN "genres" = 'Adventure,Mystery,Sci-Fi' THEN 'Adventure,Mystery,Science Fiction'
            WHEN "genres" = 'Adventure,Romance,Sci-Fi' THEN 'Adventure,Romance,Science Fiction'
            WHEN "genres" = 'Animation,Kids & Family,Comedy' THEN 'Animation,Comedy,Family'
            WHEN "genres" = 'Documentary,Action,Adventure' THEN 'Action,Adventure,Documentary'
            WHEN "genres" = 'Documentary,Crime,Mystery' THEN 'Crime,Documentary,Mystery'
            WHEN "genres" = 'Drama,Action & Adventure' THEN 'Action,Adventure,Drama'
            WHEN "genres" = 'Action & Adventure,Animation,Kids & Family,Science Fiction & Fantasy' THEN 'Action,Adventure,Animation,Family,Fantasy,Science Fiction'
            WHEN "genres" = 'Action & Adventure,Mystery & Suspense,Science Fiction & Fantasy' THEN 'Action,Adventure,Mystery,Science Fiction,Thriller'
            WHEN "genres" = 'Action,Comedy,Music' THEN 'Action,Comedy,Musical'
            WHEN "genres" = 'Action,War,Drama' THEN 'Action,Drama,War'
            WHEN "genres" = 'Adventure,Comedy,Music' THEN 'Adventure,Comedy,Musical'
            WHEN "genres" = 'Adventure,Fantasy,Sci-Fi' THEN 'Adventure,Fantasy,Science Fiction'
            WHEN "genres" = 'Animation,Short,Comedy' THEN 'Animation,Comedy,Short'
            WHEN "genres" = 'Comedy,Family,Drama' THEN 'Comedy,Drama,Family'
            WHEN "genres" = 'Comedy,Fantasy,Music' THEN 'Comedy,Fantasy,Musical'
            WHEN "genres" = 'Drama,Film-Noir,Romance' THEN 'Drama,Film Noir,Romance'
            WHEN "genres" = 'Family,Animation,Comedy' THEN 'Animation,Comedy,Family'
            WHEN "genres" = 'Family,Comedy,Drama' THEN 'Comedy,Drama,Family'
            WHEN "genres" = 'Film-Noir,Thriller' THEN 'Film Noir,Thriller'
            WHEN "genres" = 'Drama,Action & Adventure,Science Fiction & Fantasy' THEN 'Action,Adventure,Drama,Fantasy,Science Fiction'
            WHEN "genres" = 'Drama,Mystery & Suspense,Comedy' THEN 'Comedy,Drama,Mystery,Suspense'
            WHEN "genres" = 'Drama,Romance,Classics' THEN 'Classics,Drama,Romance'
            WHEN "genres" = 'Family,Comedy,Adventure' THEN 'Adventure,Comedy,Family'
            WHEN "genres" = 'Family,Comedy,Western' THEN 'Comedy,Family,Western'
            WHEN "genres" = 'Musical,Comedy' THEN 'Comedy,Musical'
            WHEN "genres" = 'Mystery,Sci-Fi' THEN 'Mystery,Science Fiction'
            WHEN "genres" = 'Romance,Comedy' THEN 'Comedy,Romance'
            WHEN "genres" = 'Romance,Comedy,Drama' THEN 'Comedy,Drama,Romance'
            WHEN "genres" = 'Sci-Fi,Horror,Mystery' THEN 'Horror,Mystery,Science Fiction'
            WHEN "genres" = 'Science Fiction & Fantasy,Horror' THEN 'Fantasy,Horror,Science Fiction'
            WHEN "genres" = 'War,Action,Drama' THEN 'Action,Drama,War'
            WHEN "genres" = 'Action & Adventure' THEN 'Action,Adventure'
            WHEN "genres" = 'Action & Adventure,Classics,Science Fiction & Fantasy' THEN 'Action,Adventure,Classics,Fantasy,Science Fiction'
            WHEN "genres" = 'Action & Adventure,Horror' THEN 'Action,Adventure,Horror'
            WHEN "genres" = 'Action & Adventure,Horror,Comedy' THEN 'Action,Adventure,Comedy,Horror'
            WHEN "genres" = 'Action & Adventure,Horror,Romance,Comedy' THEN 'Action,Adventure,Comedy,Horror,Romance'
            WHEN "genres" = 'Action & Adventure,Horror,Science Fiction & Fantasy' THEN 'Action,Adventure,Fantasy,Horror,Science Fiction'
            WHEN "genres" = 'Action & Adventure,Kids & Family' THEN 'Action,Adventure,Family'
            WHEN "genres" = 'Action & Adventure,Kids & Family,Science Fiction & Fantasy,Comedy' THEN 'Action,Adventure,Comedy,Family,Fantasy,Science Fiction'
            WHEN "genres" = 'Action & Adventure,Musical & Performing Arts,Science Fiction & Fantasy,Comedy' THEN 'Action,Adventure,Comedy,Fantasy,Musical,Science Fiction'
            WHEN "genres" = 'Action & Adventure,Mystery & Suspense,Science Fiction & Fantasy,Comedy' THEN 'Action,Adventure,Comedy,Fantasy,Mystery,Science Fiction,Thriller'
            WHEN "genres" = 'Action & Adventure,Sports & Fitness,Comedy' THEN 'Action,Adventure,Comedy,Sports'
            WHEN "genres" = 'Action,Comedy,Adventure' THEN 'Action,Adventure,Comedy'
            WHEN "genres" = 'Action,Comedy,Sport' THEN 'Action,Comedy,Sports'
            WHEN "genres" = 'Action,Family,Sci-Fi' THEN 'Action,Family,Science Fiction'
            WHEN "genres" = 'Action,Romance,Sci-Fi' THEN 'Action,Romance,Science Fiction'
            WHEN "genres" = 'Action,Sci-Fi,Sport' THEN 'Action,Science Fiction,Sports'
            WHEN "genres" = 'Action,Sci-Fi,War' THEN 'Action,Science Fiction,War'
            WHEN "genres" = 'Action,Sport' THEN 'Action,Sports'
            WHEN "genres" = 'Action,Thriller,Drama' THEN 'Action,Drama,Thriller'
            WHEN "genres" = 'Action,Western,Adventure' THEN 'Action,Adventure,Western'
            WHEN "genres" = 'Action,Western,Comedy' THEN 'Action,Comedy,Western'
            WHEN "genres" = 'Animation,Kids & Family,Musical & Performing Arts,Classics,Science Fiction & Fantasy' THEN 'Animation,Family,Musical,Classics,Fantasy,Sci-Fi'
            WHEN "genres" = 'Art House & International,Drama' THEN 'Art House,International,Drama'
            WHEN "genres" = 'Animation,Family,Adventure' THEN 'Adventure,Animation,Family'
            WHEN "genres" = 'Animation,Family,Drama' THEN 'Animation,Drama,Family'
            WHEN "genres" = 'Adventure,Fantasy,Drama' THEN 'Adventure,Drama,Fantasy'
            WHEN "genres" = 'Adventure,Fantasy,Family' THEN 'Adventure,Family,Fantasy'
            WHEN "genres" = 'Adventure,Horror,Action' THEN 'Action,Adventure,Horror'
            WHEN "genres" = 'Adventure,Musical,Family' THEN 'Adventure,Family,Musical'
            WHEN "genres" = 'Adventure,Romance,Action' THEN 'Action,Adventure,Romance'
            WHEN "genres" = 'Adventure,Romance,Drama' THEN 'Adventure,Drama,Romance'
            WHEN "genres" = 'Adventure,Western,Drama' THEN 'Adventure,Drama,Western'
            WHEN "genres" = 'Adventure,Western,Romance' THEN 'Adventure,Romance,Western'
            WHEN "genres" = 'Animation,Action,Crime' THEN 'Action,Animation,Crime'
            WHEN "genres" = 'Animation,Action,Drama' THEN 'Action,Animation,Drama'
            WHEN "genres" = 'Animation,Action,Family' THEN 'Action,Animation,Family'
            WHEN "genres" = 'Animation,Action,Sci-Fi' THEN 'Action,Animation,Sci-Fi'
            WHEN "genres" = 'Animation,Adventure,Biography' THEN 'Adventure,Animation,Biography'
            WHEN "genres" = 'Animation,Adventure,Crime' THEN 'Adventure,Animation,Crime'
            WHEN "genres" = 'Animation,Adventure,Fantasy' THEN 'Adventure,Animation,Fantasy'
            WHEN "genres" = 'Animation,Short,Family' THEN 'Animation,Family,Short'
            WHEN "genres" = 'Classics,Action & Adventure' THEN 'Action,Adventure,Classics'
            WHEN "genres" = 'Classics,Drama,Horror,Musical & Performing Arts,Mystery & Suspense,Special Interest' THEN 'Classics,Drama,Horror,Musical,Mystery,Suspense'
            WHEN "genres" = 'Comedy,Action' THEN 'Action,Comedy'
            WHEN "genres" = 'Comedy,Action,Family' THEN 'Action,Comedy,Family'
            WHEN "genres" = 'Comedy,Action,Sci-Fi' THEN 'Action,Comedy,Sci-Fi'
            WHEN "genres" = 'Comedy,Adventure' THEN 'Adventure,Comedy'
            WHEN "genres" = 'Comedy,Animation' THEN 'Animation,Comedy'
            WHEN "genres" = 'Comedy,Family,Adventure' THEN 'Adventure,Comedy,Family'
            WHEN "genres" = 'Comedy,Musical,Adventure' THEN 'Adventure,Comedy,Musical'
            WHEN "genres" = 'Comedy,Musical,Drama' THEN 'Comedy,Drama,Musical'
            WHEN "genres" = 'Comedy,Musical,Fantasy' THEN 'Comedy,Fantasy,Musical'
            WHEN "genres" = 'Comedy,Mystery,Crime' THEN 'Comedy,Crime,Mystery'
            WHEN "genres" = 'Comedy,Mystery,Drama' THEN 'Comedy,Drama,Mystery'
            WHEN "genres" = 'Comedy,Romance,Family' THEN 'Comedy,Family,Romance'
            WHEN "genres" = 'Comedy,Sci-Fi,Family' THEN 'Comedy,Family,Sci-Fi'
            WHEN "genres" = 'Comedy,Sci-Fi,Fantasy' THEN 'Comedy,Fantasy,Sci-Fi'
            WHEN "genres" = 'Comedy,War,Drama' THEN 'Comedy,Drama,War'
            WHEN "genres" = 'Comedy,War,Fantasy' THEN 'Comedy,Fantasy,War'
            WHEN "genres" = 'Comedy,Western,Drama' THEN 'Comedy,Drama,Western'
            WHEN "genres" = 'Crime,Action,Drama' THEN 'Action,Crime,Drama'
            WHEN "genres" = 'Crime,Comedy' THEN 'Comedy,Crime'
            WHEN "genres" = 'Crime,Thriller,Drama' THEN 'Crime,Drama,Thriller'
            WHEN "genres" = 'Crime,Western,Drama' THEN 'Crime,Drama,Western'
            WHEN "genres" = 'Documentary,Action & Adventure,Sports & Fitness' THEN 'Action,Adventure,Documentary,Sports'
            WHEN "genres" = 'Documentary,Action,Comedy' THEN 'Action,Comedy,Documentary'
            WHEN "genres" = 'Documentary,Action,Crime' THEN 'Action,Crime,Documentary'
            WHEN "genres" = 'Documentary,Drama,Kids & Family,Special Interest' THEN 'Documentary,Drama,Family'
            WHEN "genres" = 'Documentary,Drama,Sport' THEN 'Documentary,Drama,Sports'
            WHEN "genres" = 'Documentary,Family,Sport' THEN 'Documentary,Family,Sports'
            WHEN "genres" = 'Documentary,History,Sci-Fi' THEN 'Documentary,History,Science Fiction'
            WHEN "genres" = 'Documentary,Kids & Family' THEN 'Documentary,Family'
            WHEN "genres" = 'Documentary,Kids & Family,Special Interest' THEN 'Documentary,Family'
            WHEN "genres" = 'Documentary,Musical & Performing Arts,Art House & International,Special Interest' THEN 'Documentary,Musical'
            WHEN "genres" = 'Documentary,Sports & Fitness,Special Interest' THEN 'Documentary,Sports'
            WHEN "genres" = 'Drama,Action & Adventure,Classics' THEN 'Drama,Action,Adventure,Classics'
            WHEN "genres" = 'Drama,Action & Adventure,Classics,Comedy' THEN 'Drama,Action,Adventure,Classics,Comedy'
            WHEN "genres" = 'Drama,Action & Adventure,Horror,Mystery & Suspense' THEN 'Drama,Action,Adventure,Horror,Mystery'
            WHEN "genres" = 'Drama,Action & Adventure,Kids & Family,Science Fiction & Fantasy,Comedy' THEN 'Drama,Action,Adventure,Family,Science Fiction,Comedy'
            WHEN "genres" = 'Drama,Action & Adventure,Romance,Comedy' THEN 'Drama,Action,Adventure,Romance,Comedy'
            WHEN "genres" = 'Drama,Action & Adventure,Romance,Mystery & Suspense' THEN 'Drama,Action,Adventure,Romance,Mystery'
            WHEN "genres" = 'Drama,Animation,Kids & Family,Science Fiction & Fantasy' THEN 'Drama,Animation,Family,Science Fiction'
            WHEN "genres" = 'Drama,Art House & International,Comedy' THEN 'Drama,Comedy'
            WHEN "genres" = 'Drama,Art House & International,Science Fiction & Fantasy,Special Interest' THEN 'Drama,Science Fiction'
            WHEN "genres" = 'Drama,Classics,Science Fiction & Fantasy,Comedy' THEN 'Drama,Classics,Science Fiction,Comedy'
            WHEN "genres" = 'Drama,Cult Movies' THEN 'Drama'
            WHEN "genres" = 'Drama,Kids & Family,Classics' THEN 'Classics,Drama,Family'
            WHEN "genres" = 'Drama,Kids & Family,Comedy' THEN 'Comedy,Drama,Family'
            WHEN "genres" = 'Drama,Kids & Family,Romance' THEN 'Drama,Family,Romance'
            WHEN "genres" = 'Drama,Kids & Family,Romance,Classics' THEN 'Classics,Drama,Family,Romance'
            WHEN "genres" = 'Drama,Musical & Performing Arts,Classics' THEN 'Classics,Drama,Musical'
            WHEN "genres" = 'Drama,Musical & Performing Arts,Classics,Comedy' THEN 'Classics,Comedy,Drama,Musical'
            WHEN "genres" = 'Drama,Musical & Performing Arts,Comedy' THEN 'Comedy,Drama,Musical'
            WHEN "genres" = 'Drama,Mystery & Suspense,Classics' THEN 'Classics,Drama,Mystery,Thriller'
            WHEN "genres" = 'Drama,Sports & Fitness,Comedy' THEN 'Comedy,Drama,Sport'
            WHEN "genres" = 'Family,Adventure,Animation' THEN 'Adventure,Animation,Family'
            WHEN "genres" = 'Family,Animation' THEN 'Animation,Family'
            WHEN "genres" = 'Family,Animation,Adventure' THEN 'Adventure,Animation,Family'
            WHEN "genres" = 'Family,Animation,Fantasy' THEN 'Animation,Family,Fantasy'
            WHEN "genres" = 'Family,Animation,Musical' THEN 'Animation,Family,Musical'
            WHEN "genres" = 'Family,Comedy,Action' THEN 'Action,Comedy,Family'
            WHEN "genres" = 'Family,Drama,Adventure' THEN 'Adventure,Drama,Family'
            WHEN "genres" = 'Family,Drama,Comedy' THEN 'Comedy,Drama,Family'
            WHEN "genres" = 'Family,Fantasy,Action' THEN 'Action,Family,Fantasy'
            WHEN "genres" = 'Family,Fantasy,Adventure' THEN 'Adventure,Family,Fantasy'
            WHEN "genres" = 'Family,Fantasy,Sci-Fi' THEN 'Family,Fantasy,Science Fiction'
            WHEN "genres" = 'Family,Horror,Drama' THEN 'Drama,Family,Horror'
            WHEN "genres" = 'Family,Musical,Fantasy' THEN 'Family,Fantasy,Musical'
            WHEN "genres" = 'Family,Western,Action' THEN 'Action,Family,Western'
            WHEN "genres" = 'Family,Western,Adventure' THEN 'Adventure,Family,Western'
            WHEN "genres" = 'Fantasy,Family,Adventure' THEN 'Adventure,Family,Fantasy'
            WHEN "genres" = 'Horror,Art House & International,Mystery & Suspense' THEN 'Art House,Horror,Mystery,Suspense'
            WHEN "genres" = 'Horror,Mystery & Suspense,Classics,Science Fiction & Fantasy' THEN 'Classics,Horror,Mystery,Science Fiction,Suspense'
            WHEN "genres" = 'Horror,Mystery & Suspense,Comedy' THEN 'Comedy,Horror,Mystery,Suspense'
            WHEN "genres" = 'Horror,Mystery & Suspense,Science Fiction & Fantasy,Comedy' THEN 'Comedy,Horror,Mystery,Science Fiction,Suspense'
            WHEN "genres" = 'Horror,Science Fiction & Fantasy,Comedy,Cult Movies' THEN 'Comedy,Cult,Horror,Science Fiction'
            WHEN "genres" = 'Horror,Science Fiction & Fantasy,Special Interest' THEN 'Horror,Science Fiction,Special Interest'
            WHEN "genres" = 'Kids & Family,Mystery & Suspense,Comedy' THEN 'Comedy,Family,Mystery,Suspense'
            WHEN "genres" = 'Kids & Family,Science Fiction & Fantasy,Comedy' THEN 'Comedy,Family,Science Fiction'
            WHEN "genres" = 'Musical & Performing Arts,Classics,Comedy' THEN 'Classics,Comedy,Musical'
            WHEN "genres" = 'Musical,Adventure,Family' THEN 'Adventure,Family,Musical'
            WHEN "genres" = 'Mystery & Suspense' THEN 'Mystery,Suspense'
            WHEN "genres" = 'Mystery,Horror,Sci-Fi' THEN 'Horror,Mystery,Science Fiction'
            WHEN "genres" = 'Romance,Musical & Performing Arts,Classics,Comedy' THEN 'Classics,Comedy,Musical,Romance'
            WHEN "genres" = 'Romance,Musical & Performing Arts,Comedy' THEN 'Comedy,Musical,Romance'
            WHEN "genres" = 'Romance,Sci-Fi' THEN 'Romance,Science Fiction'
            WHEN "genres" = 'Romance,Sci-Fi,Thriller' THEN 'Romance,Science Fiction,Thriller'
            WHEN "genres" = 'Romance,Sports & Fitness,Science Fiction & Fantasy,Comedy' THEN 'Comedy,Romance,Science Fiction,Sports'
            WHEN "genres" = 'Sci-Fi,Horror,Drama' THEN 'Drama,Horror,Science Fiction'
            WHEN "genres" = 'Sci-Fi,Horror,Thriller' THEN 'Horror,Science Fiction,Thriller'
            WHEN "genres" = 'Science Fiction & Fantasy' THEN 'Fantasy,Science Fiction'
            WHEN "genres" = 'Science Fiction & Fantasy,Comedy' THEN 'Comedy,Fantasy,Science Fiction'
            WHEN "genres" = 'Science Fiction & Fantasy,Kids & Family' THEN 'Family,Fantasy,Science Fiction'
            WHEN "genres" = 'Short,Sci-Fi' THEN 'Science Fiction,Short'
            WHEN "genres" = 'Sports & Fitness,Drama' THEN 'Drama,Sports'
            WHEN "genres" = 'Television,Comedy' THEN 'Comedy,Television'
            WHEN "genres" = 'Thriller,Action' THEN 'Action,Thriller'
            WHEN "genres" = 'Thriller,Comedy,Horror' THEN 'Comedy,Horror,Thriller'
            WHEN "genres" = 'Thriller,Crime,Drama' THEN 'Crime,Drama,Thriller'
            WHEN "genres" = 'Thriller,Drama' THEN 'Drama,Thriller'
            WHEN "genres" = 'Thriller,Film-Noir,Drama' THEN 'Drama,Film-Noir,Thriller'
            WHEN "genres" = 'Thriller,War,Action' THEN 'Action,Thriller,War'
            WHEN "genres" = 'Western,Adventure,Romance' THEN 'Adventure,Romance,Western'
            WHEN "genres" = 'Western,Classics' THEN 'Classics,Western'
            WHEN "genres" = 'Western,Crime' THEN 'Crime,Western'
            WHEN "genres" = 'Western,Drama,Action & Adventure,Classics' THEN 'Action,Adventure,Classics,Drama,Western'
            WHEN "genres" = 'Western,Family' THEN 'Family,Western'
            WHEN "genres" = 'Western,Family,Adventure' THEN 'Adventure,Family,Western'
            ELSE "genres"
        END AS "genres",
        "filming_locations",
        "plot_summary"
    FROM "movies_renamed"
),

"movies_renamed_cleaned_null" AS (
    -- NULL Imputation: Impute Null to Disguised Missing Values
    -- plot_summary: ['Add a Plot', 'The plot is unknown at this time.', 'The plot is unknown.', 'Plot is unknown.']
    SELECT 
        CASE
            WHEN "plot_summary" = 'Add a Plot' THEN NULL
            WHEN "plot_summary" = 'The plot is unknown at this time.' THEN NULL
            WHEN "plot_summary" = 'The plot is unknown.' THEN NULL
            WHEN "plot_summary" = 'Plot is unknown.' THEN NULL
            ELSE "plot_summary"
        END AS "plot_summary",
        "movie_id",
        "average_rating",
        "number_of_ratings",
        "title",
        "genres",
        "filming_locations",
        "languages",
        "runtime",
        "country",
        "full_cast",
        "writers",
        "release_date",
        "number_of_reviews",
        "main_actors",
        "director",
        "release_year"
    FROM "movies_renamed_cleaned"
),

"movies_renamed_cleaned_null_casted" AS (
    -- Column Type Casting: 
    -- average_rating: from VARCHAR to DECIMAL
    -- number_of_ratings: from VARCHAR to INT
    -- genres: from VARCHAR to ARRAY
    -- runtime: from VARCHAR to INT
    -- full_cast: from VARCHAR to ARRAY
    -- release_date: from VARCHAR to DATE
    -- number_of_reviews: from VARCHAR to JSON
    -- release_year: from VARCHAR to INT
    SELECT
        "plot_summary",
        "movie_id",
        "title",
        "filming_locations",
        "languages",
        "country",
        "writers",
        "main_actors",
        "director",
        CASE
            WHEN regexp_full_match("average_rating", '^[1-9](\.[0-9])?$') THEN CAST("average_rating" AS DECIMAL(2,1))
            WHEN regexp_full_match("average_rating", '^[1-9]\.[0-9]/10$') THEN CAST(REGEXP_EXTRACT("average_rating", '^(\d+\.\d+)') AS DECIMAL)
            WHEN regexp_full_match("average_rating", '\d\.\d\/10,\d\.\d\/10') THEN CAST(REGEXP_EXTRACT("average_rating", '(\d+\.\d+)') AS DECIMAL)
            WHEN regexp_full_match("average_rating", '\d(\.\d)?/10,\d(\.\d)?/10') THEN CAST(REGEXP_EXTRACT("average_rating", '(\d+(\.\d+)?)') AS DECIMAL)
            WHEN regexp_full_match("average_rating", '\d(\.\d)?/10') THEN CAST(REGEXP_EXTRACT("average_rating", '(\d+(\.\d+)?)') AS DECIMAL)
        END AS "average_rating",
        CASE
            WHEN regexp_full_match("number_of_ratings", '^\d+$') THEN CAST("number_of_ratings" AS INT)
            WHEN regexp_full_match("number_of_ratings", '^\d{1,3},\d{3}$') THEN CAST(REPLACE("number_of_ratings", ',', '') AS INT)
            WHEN regexp_full_match("number_of_ratings", '\d{1,1},\d{3},\d{3}') THEN CAST(REPLACE("number_of_ratings", ',', '') AS INT)
        END AS "number_of_ratings",
        SPLIT("genres", ', ') AS "genres",
        "runtime" AS "runtime",
        SPLIT("full_cast", ',\s*') AS "full_cast",
        CASE
            WHEN regexp_full_match("release_date", '\d{1,2} [A-Z][a-z]+ \d{4} \(USA\)') THEN CAST(strptime(SUBSTR("release_date", 1, LENGTH("release_date") - 6), '%d %B %Y') AS DATE)
            WHEN regexp_full_match("release_date", '\d{4} \(USA\)') THEN CAST(strptime(substring("release_date", 1, 4), '%Y') AS DATE)
            WHEN regexp_full_match("release_date", '(January|February|March|April|May|June|July|August|September|October|November|December)\s\d{4}\s\((USA|UK|France|Germany|Italy|Sweden|Denmark|Netherlands|Russia|South Korea|Finland|Portugal|Brazil|Argentina|Australia|Israel|Singapore|Philippines|Japan|South Africa)\)') THEN CAST(strptime(SUBSTRING("release_date", 1, POSITION(' (' IN "release_date") - 1), '%B %Y') AS DATE)
            WHEN regexp_full_match("release_date", '\d{1,2}\s(January|February|March|April|May|June|July|August|September|October|November|December)\s\d{4}\s\((UK|France|Germany|Italy|Sweden|Denmark|Netherlands|Russia|South Korea|Finland|Portugal|Brazil|Argentina|Australia|Israel|Singapore|Philippines|Japan|South Africa)\)') THEN CAST(strptime(SPLIT_PART("release_date", ' (', 1), '%d %B %Y') AS DATE)
            WHEN regexp_full_match("release_date", '(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s\d{1,2},\s\d{4}\sWide') THEN CAST(strptime(SUBSTRING("release_date", 1, LENGTH("release_date") - 5), '%b %-d, %Y') AS DATE)
            WHEN regexp_full_match("release_date", '\d{1,2}\s(January|February|March|April|May|June|July|August|September|October|November|December)\s\d{4}\s\((West Germany|South Africa)\)') THEN CAST(strptime(SUBSTRING("release_date", 1, POSITION(' (' IN "release_date") - 1), '%-d %B %Y') AS DATE)
            WHEN regexp_full_match("release_date", '\d{1,2}\s(January|February|March|April|May|June|July|August|September|October|November|December)\s\d{4}\s\([A-Za-z\s]+\)') THEN CAST(strptime(SUBSTRING("release_date", 1, POSITION('(' IN "release_date") - 2), '%-d %B %Y') AS DATE)
            WHEN regexp_full_match("release_date", '\d{4}\s\([A-Za-z\s]+\)') THEN CAST(strptime(SUBSTRING("release_date", 1, 4) || '-01-01', '%Y-%m-%d') AS DATE)
            WHEN regexp_full_match("release_date", '[A-Z][a-z]{2}\s\d{1,2},\s\d{4}\sLimited') THEN CAST(strptime(SUBSTRING("release_date", 1, LENGTH("release_date") - 8), '%b %d, %Y') AS DATE)
            WHEN regexp_full_match("release_date", '[A-Z][a-z]+\s\d{4}\s\([A-Za-z\s]+\)') THEN CAST(strptime(substring("release_date", 1, strpos("release_date", ' (') - 1), '%B %Y') AS DATE)
        END AS "release_date",
        CASE
            WHEN regexp_full_match("number_of_reviews", '^(\d+ user|\d+ critic)(,\s*(\d+ user|\d+ critic))?$') THEN JSON_OBJECT(
            'user', COALESCE(CAST(NULLIF(REGEXP_EXTRACT("number_of_reviews", '(\d+)\s*user', 1), '') AS INTEGER), 0),
            'critic', COALESCE(CAST(NULLIF(REGEXP_EXTRACT("number_of_reviews", '(\d+)\s*critic', 1), '') AS INTEGER), 0)
        )
            WHEN regexp_full_match("number_of_reviews", '(\d{1,3},)?\d{3} user,\d{3} critic') THEN JSON_OBJECT(
            'user', CAST(REGEXP_EXTRACT(SPLIT_PART("number_of_reviews", ',', 1), '(\d+)') AS INTEGER),
            'critic', CAST(REGEXP_EXTRACT(SPLIT_PART("number_of_reviews", ',', -1), '(\d+)') AS INTEGER)
        )
        END AS "number_of_reviews",
        CASE
            WHEN regexp_full_match("release_year", '^\d{4}$') THEN CAST("release_year" AS INT)
            WHEN regexp_full_match("release_year", '^\d{4} \d{4} \d{4}$') THEN CAST(SUBSTRING("release_year", 1, 4) AS INT)
        END AS "release_year"
    FROM "movies_renamed_cleaned_null"
)

-- COCOON BLOCK END
SELECT * FROM "movies_renamed_cleaned_null_casted"