version: 2
sources:
- name: cocoon
  database: memory
  schema: main
  tables:
  - name: allergies
  - name: careplans
  - name: claims
  - name: claims_transactions
  - name: conditions
  - name: devices
  - name: encounters
  - name: imaging_studies
  - name: immunizations
  - name: medications
  - name: observations
  - name: organizations
  - name: patients
  - name: payers
  - name: payer_transitions
  - name: procedures
  - name: providers
  - name: supplies
