version: 2
sources:
- name: cocoon
  tables:
  - allergies
  - careplans
  - claims
  - claims_transactions
  - conditions
  - devices
  - encounters
  - imaging_studies
  - immunizations
  - medications
  - observations
  - organizations
  - patients
  - payer_transitions
  - payers
  - procedures
  - providers
  - supplies
