version: 2
sources:
- name: cocoon
  tables:
  - pinterest_ad_group_history_data
  - pinterest_ad_group_report_data
  - pinterest_advertiser_history_data
  - pinterest_advertiser_report_data
  - pinterest_campaign_history_data
  - pinterest_campaign_report_data
  - pinterest_keyword_history_data
  - pinterest_keyword_report_data
  - pinterest_pin_promotion_history_data
  - pinterest_pin_promotion_report_data
