version: 2
models:
- name: stg_DATA_KIT_DEPLOYMENT_LOG
  description: The table is about data kit deployment logs. It contains information
    on each deployment, including the owner, creation and modification details, component
    information, and deployment job. The table tracks various dates, IDs, and names
    related to the deployment process. It also includes fields for template versions,
    data space names, and bundle names, suggesting it's used to manage and monitor
    the deployment of data kits or components across different environments or organizations.
  columns:
  - name: ID
    description: Unique identifier for the deployment log entry
    tests:
    - not_null
  - name: OWNER_ID
    description: ID of the user who owns this deployment
    tests:
    - not_null
  - name: IS_DELETED
    description: Flag indicating if the record is deleted
    tests:
    - not_null
  - name: NAME
    description: Name of the deployment log entry
    tests:
    - not_null
  - name: CREATED_DATE
    description: Date and time when the record was created
    tests:
    - not_null
  - name: CREATED_BY_ID
    description: ID of the user who created the record
    tests:
    - not_null
  - name: LAST_MODIFIED_DATE
    description: Date and time of the last modification
    tests:
    - not_null
  - name: LAST_MODIFIED_BY_ID
    description: ID of the user who last modified the record
    tests:
    - not_null
  - name: SYSTEM_MODSTAMP
    description: System timestamp of the last modification
    tests:
    - not_null
  - name: LAST_VIEWED_DATE
    description: Date and time when the record was last viewed
    tests:
    - not_null
  - name: LAST_REFERENCED_DATE
    description: Date and time when the record was last referenced
    tests:
    - not_null
  - name: COMPONENT_TEMPLATE_ID
    description: ID of the component template used
    tests:
    - not_null
  - name: PUBLISHER_ORG_COMPONENT_ID
    description: ID of the component in the publisher organization
    tests:
    - not_null
  - name: SUBSCRIBER_ORG_COMPONENT_ID
    description: ID of the component in the subscriber organization
    tests:
    - not_null
  - name: COMPONENT_TYPE
    description: Type of the component being deployed
    tests:
    - not_null
  - name: DEPLOY_JOB
    description: Identifier for the deployment job
    tests:
    - not_null
  - name: TEMPLATE_VERSION
    description: Version of the template used in the deployment
    tests:
    - not_null
  - name: _FIVETRAN_DELETED
    description: Fivetran-specific deletion flag
    tests:
    - not_null
  - name: _FIVETRAN_SYNCED
    description: Timestamp of last Fivetran synchronization
    tests:
    - not_null
  - name: DATA_SPACE_NAME
    description: Name of the data space for the deployment
    tests:
    - not_null
  - name: COMPONENT_NAME
    description: Name of the component being deployed
    tests:
    - not_null
  - name: BUNDLE_NAME
    description: Name of the bundle containing the component
    tests:
    - not_null
  tests: []
