version: 2
models:
- name: stg_USER_PROVISIONING_CONFIG
  description: The table is about user provisioning configuration settings. It includes
    details like ID, developer name, language, master label, and creation/modification
    timestamps. It also contains flags for deletion status, approval requirements,
    and enabled operations. The table links to connected apps and named credentials.
    It stores configuration for user account mapping, update attributes, and reconciliation
    settings.
  columns:
  - name: ID
    description: Unique identifier for the configuration
    tests:
    - not_null
  - name: IS_DELETED
    description: Flag indicating if the record is deleted
    tests:
    - not_null
  - name: DEVELOPER_NAME
    description: Unique name used in API and metadata
    tests:
    - not_null
  - name: LANGUAGE_
    description: Language code for the configuration
    tests:
    - not_null
  - name: MASTER_LABEL
    description: Display name for the configuration
    tests:
    - not_null
  - name: NAMESPACE_PREFIX
    description: Namespace prefix for managed packages
    tests:
    - not_null
  - name: CREATED_DATE
    description: Date and time when the record was created
    tests:
    - not_null
  - name: CREATED_BY_ID
    description: ID of the user who created the record
    tests:
    - not_null
  - name: LAST_MODIFIED_DATE
    description: Date and time of last modification
    tests:
    - not_null
  - name: LAST_MODIFIED_BY_ID
    description: ID of the user who last modified the record
    tests:
    - not_null
  - name: SYSTEM_MODSTAMP
    description: System field for tracking modifications
    tests:
    - not_null
  - name: CONNECTED_APP_ID
    description: ID of the associated connected app
    tests:
    - not_null
  - name: NOTES
    description: Additional notes or comments
    tests:
    - not_null
  - name: ENABLED
    description: Flag indicating if the configuration is active
    tests:
    - not_null
  - name: APPROVAL_REQUIRED
    description: Flag indicating if approval is required
    tests:
    - not_null
  - name: USER_ACCOUNT_MAPPING
    description: Configuration for user account mapping
    tests:
    - not_null
  - name: ENABLED_OPERATIONS
    description: List of enabled operations
    tests:
    - not_null
  - name: ON_UPDATE_ATTRIBUTES
    description: Attributes to update on changes
    tests:
    - not_null
  - name: LAST_RECON_DATE_TIME
    description: Date and time of last reconciliation
    tests:
    - not_null
  - name: NAMED_CREDENTIAL_ID
    description: ID of the associated named credential
    tests:
    - not_null
  - name: RECON_FILTER
    description: Filter criteria for reconciliation
    tests:
    - not_null
  - name: _FIVETRAN_DELETED
    description: Fivetran's deletion tracking field
    tests:
    - not_null
  - name: _FIVETRAN_SYNCED
    description: Fivetran's synchronization timestamp
    tests:
    - not_null
  tests: []
