version: 2
models:
- name: stg_LIGHTNING_ONBOARDING_CONFIG
  description: The table is about Lightning onboarding configuration settings. It
    contains details like developer name, language, master label, custom questions,
    and feedback settings. The table tracks creation and modification dates, user
    IDs, and system timestamps. It includes flags for deletion, customization, and
    Salesforce feedback. The table also stores configuration for prompt delay time
    and feedback form frequency.
  columns:
  - name: ID
    description: Unique identifier for the onboarding configuration
    tests:
    - not_null
  - name: IS_DELETED
    description: Flag indicating if the record is deleted
    tests:
    - not_null
  - name: DEVELOPER_NAME
    description: Unique name for the configuration in the system
    tests:
    - not_null
  - name: LANGUAGE_
    description: Language of the onboarding configuration
    tests:
    - not_null
  - name: MASTER_LABEL
    description: Display name for the configuration
    tests:
    - not_null
  - name: CREATED_DATE
    description: Date and time when the record was created
    tests:
    - not_null
  - name: CREATED_BY_ID
    description: ID of the user who created the record
    tests:
    - not_null
  - name: LAST_MODIFIED_DATE
    description: Date and time of the last modification
    tests:
    - not_null
  - name: LAST_MODIFIED_BY_ID
    description: ID of the user who last modified the record
    tests:
    - not_null
  - name: SYSTEM_MODSTAMP
    description: System timestamp for record modification
    tests:
    - not_null
  - name: CUSTOM_QUESTION
    description: Custom questions for the onboarding process
    tests:
    - not_null
  - name: FEEDBACK_FORM_DAYS_FREQUENCY
    description: Frequency of feedback form in days
    tests:
    - not_null
  - name: SEND_FEEDBACK_TO_SALESFORCE
    description: Flag to send feedback to Salesforce
    tests:
    - not_null
  - name: IS_CUSTOM
    description: Flag indicating if the configuration is custom
    tests:
    - not_null
  - name: PROMPT_DELAY_TIME
    description: Delay time for prompts in the onboarding process
    tests:
    - not_null
  - name: _FIVETRAN_DELETED
    description: Fivetran's deletion flag
    tests:
    - not_null
  - name: _FIVETRAN_SYNCED
    description: Timestamp of last Fivetran synchronization
    tests:
    - not_null
  tests: []
