version: 2
models:
- name: stg_EVENT_RELAY_CONFIG
  description: The table is about event relay configurations. It contains details
    such as the event channel, destination resource, state, and relay options. The
    table tracks creation and modification dates, as well as the users who created
    or modified the configuration. It also includes fields for developer name, language,
    and namespace prefix, suggesting it's part of a larger development ecosystem.
  columns:
  - name: ID
    description: Unique identifier for the event relay configuration
    tests:
    - not_null
  - name: IS_DELETED
    description: Flag indicating if the configuration is deleted
    tests:
    - not_null
  - name: DEVELOPER_NAME
    description: Name of the configuration used by developers
    tests:
    - not_null
  - name: LANGUAGE_
    description: Language setting for the configuration
    tests:
    - not_null
  - name: MASTER_LABEL
    description: User-friendly label for the configuration
    tests:
    - not_null
  - name: NAMESPACE_PREFIX
    description: Namespace prefix for the configuration
    tests:
    - not_null
  - name: CREATED_DATE
    description: Date and time when the configuration was created
    tests:
    - not_null
  - name: CREATED_BY_ID
    description: ID of the user who created the configuration
    tests:
    - not_null
  - name: LAST_MODIFIED_DATE
    description: Date and time of the last modification
    tests:
    - not_null
  - name: LAST_MODIFIED_BY_ID
    description: ID of the user who last modified the configuration
    tests:
    - not_null
  - name: SYSTEM_MODSTAMP
    description: System timestamp for tracking modifications
    tests:
    - not_null
  - name: EVENT_CHANNEL
    description: Channel or type of event being relayed
    tests:
    - not_null
  - name: DESTINATION_RESOURCE_NAME
    description: Name of the resource receiving the relayed events
    tests:
    - not_null
  - name: STATE
    description: Current state of the event relay configuration
    tests:
    - not_null
  - name: RELAY_OPTION
    description: Option specifying how events are relayed
    tests:
    - not_null
  - name: USAGE_TYPE
    description: Type of usage for the event relay
    tests:
    - not_null
  - name: _FIVETRAN_DELETED
    description: Fivetran-specific deletion flag
    tests:
    - not_null
  - name: _FIVETRAN_SYNCED
    description: Fivetran-specific synchronization timestamp
    tests:
    - not_null
  tests: []
