version: 2
models:
- name: stg_FISCAL_YEAR_SETTINGS
  description: The table is about fiscal year settings. It contains details for different
    years, including start and end dates, year type, and labeling schemes for quarters,
    periods, and weeks. Each row represents a fiscal year, with a unique ID and period
    ID. The table includes standard years from 2023 to 2028. It also has system timestamps
    and Fivetran sync information.
  columns:
  - name: ID
    description: Unique identifier for the fiscal year record
    tests:
    - not_null
  - name: PERIOD_ID
    description: Unique identifier for the fiscal period
    tests:
    - not_null
  - name: START_DATE
    description: Beginning date of the fiscal year
    tests:
    - not_null
  - name: END_DATE
    description: Ending date of the fiscal year
    tests:
    - not_null
  - name: NAME
    description: Name or label of the fiscal year
    tests:
    - not_null
  - name: IS_STANDARD_YEAR
    description: Indicates if it's a standard fiscal year
    tests:
    - not_null
  - name: YEAR_TYPE
    description: Type of fiscal year (e.g., Standard)
    tests:
    - not_null
  - name: QUARTER_LABEL_SCHEME
    description: Labeling scheme for quarters
    tests:
    - not_null
  - name: PERIOD_LABEL_SCHEME
    description: Labeling scheme for periods
    tests:
    - not_null
  - name: WEEK_LABEL_SCHEME
    description: Labeling scheme for weeks
    tests:
    - not_null
  - name: QUARTER_PREFIX
    description: Prefix used for quarter labels
    tests:
    - not_null
  - name: PERIOD_PREFIX
    description: Prefix used for period labels
    tests:
    - not_null
  - name: WEEK_START_DAY
    description: Day of the week when the fiscal week starts
    cocoon_meta:
      missing_reason: Unknown
  - name: DESCRIPTION
    description: Additional description of the fiscal year
    cocoon_meta:
      missing_reason: Optional field for additional information, not always needed.
  - name: SYSTEM_MODSTAMP
    description: Timestamp of last system modification
    tests:
    - not_null
  - name: _FIVETRAN_DELETED
    description: Indicates if the record was deleted in Fivetran
    tests:
    - not_null
  - name: _FIVETRAN_SYNCED
    description: Timestamp of last Fivetran synchronization
    tests:
    - not_null
  tests: []
