version: 2
models:
- name: stg_AUTH_CONFIG
  description: The table is about authentication configuration settings. It contains
    details like developer name, language, master label, and namespace prefix. The
    table tracks creation and modification dates, and user IDs. It stores URL and
    various authentication options such as username/password, SAML, auth provider,
    and certificate. The table also includes flags for deletion status and active
    status. The type field likely indicates the authentication method type.
  columns:
  - name: ID
    description: Unique identifier for the authentication configuration
    tests:
    - not_null
  - name: IS_DELETED
    description: Flag indicating if the record is deleted
    tests:
    - not_null
  - name: DEVELOPER_NAME
    description: Name of the configuration used by developers
    tests:
    - not_null
  - name: LANGUAGE_
    description: Language of the configuration
    tests:
    - not_null
  - name: MASTER_LABEL
    description: User-friendly label for the configuration
    tests:
    - not_null
  - name: NAMESPACE_PREFIX
    description: Prefix for the configuration's namespace
    tests:
    - not_null
  - name: CREATED_DATE
    description: Date and time when the record was created
    tests:
    - not_null
  - name: CREATED_BY_ID
    description: ID of the user who created the record
    tests:
    - not_null
  - name: LAST_MODIFIED_DATE
    description: Date and time of the last modification
    tests:
    - not_null
  - name: LAST_MODIFIED_BY_ID
    description: ID of the user who last modified the record
    tests:
    - not_null
  - name: SYSTEM_MODSTAMP
    description: System modification timestamp
    tests:
    - not_null
  - name: URL
    description: URL associated with the authentication configuration
    tests:
    - not_null
  - name: AUTH_OPTIONS_USERNAME_PASSWORD
    description: Indicates if username/password authentication is enabled
    tests:
    - not_null
  - name: AUTH_OPTIONS_SAML
    description: Indicates if SAML authentication is enabled
    tests:
    - not_null
  - name: AUTH_OPTIONS_AUTH_PROVIDER
    description: Indicates if auth provider authentication is enabled
    tests:
    - not_null
  - name: AUTH_OPTIONS_CERTIFICATE
    description: Indicates if certificate-based authentication is enabled
    tests:
    - not_null
  - name: IS_ACTIVE
    description: Flag indicating if the configuration is active
    tests:
    - not_null
  - name: TYPE
    description: Type of authentication method
    tests:
    - not_null
  - name: _FIVETRAN_DELETED
    description: Fivetran-specific deletion flag
    tests:
    - not_null
  - name: _FIVETRAN_SYNCED
    description: Fivetran synchronization timestamp
    tests:
    - not_null
  tests: []
