version: 2
models:
- name: stg_SALES_WORK_QUEUE_SETTINGS
  description: The table is about sales work queue settings. It contains configuration
    details for a feature related to sales workflows. The table includes fields for
    the feature name, target entity, and target field. It also tracks creation and
    modification dates, user IDs for creators and modifiers, and system timestamps.
    The table allows for soft deletion and includes Fivetran sync information.
  columns:
  - name: ID
    description: Unique identifier for each record
    tests:
    - not_null
  - name: IS_DELETED
    description: Flag indicating if the record is deleted
    tests:
    - not_null
  - name: CREATED_DATE
    description: Date and time when the record was created
    tests:
    - not_null
  - name: CREATED_BY_ID
    description: ID of the user who created the record
    tests:
    - not_null
  - name: LAST_MODIFIED_DATE
    description: Date and time of last modification
    tests:
    - not_null
  - name: LAST_MODIFIED_BY_ID
    description: ID of the user who last modified the record
    tests:
    - not_null
  - name: SYSTEM_MODSTAMP
    description: System timestamp for last modification
    tests:
    - not_null
  - name: FEATURE_NAME
    description: Name of the sales workflow feature
    tests:
    - not_null
  - name: TARGET_ENTITY
    description: Entity targeted by the feature
    tests:
    - not_null
  - name: TARGET_FIELD
    description: Specific field targeted by the feature
    tests:
    - not_null
  - name: _FIVETRAN_DELETED
    description: Fivetran flag for deleted records
    tests:
    - not_null
  - name: _FIVETRAN_SYNCED
    description: Timestamp of last Fivetran sync
    tests:
    - not_null
  tests: []
