version: 2
models:
- name: stg_MOBILE_APPLICATION_DETAIL
  description: The table is about mobile applications. It includes details such as
    developer name, language, label, namespace, creation date, modification dates,
    version, device platform, OS version, and device type. It also contains information
    about the application file, icon, installation URL, bundle identifier, and binary
    file name. The table tracks if the app is enterprise and if it's deleted.
  columns:
  - name: ID
    description: Unique identifier for the mobile application
    tests:
    - not_null
  - name: IS_DELETED
    description: Flag indicating if the app is deleted
    tests:
    - not_null
  - name: DEVELOPER_NAME
    description: Name of the app developer
    tests:
    - not_null
  - name: LANGUAGE_
    description: Language of the application
    tests:
    - not_null
  - name: MASTER_LABEL
    description: Primary label or name of the app
    tests:
    - not_null
  - name: NAMESPACE_PREFIX
    description: Namespace prefix for the app
    tests:
    - not_null
  - name: CREATED_DATE
    description: Date when the app was created
    tests:
    - not_null
  - name: CREATED_BY_ID
    description: ID of the user who created the app
    tests:
    - not_null
  - name: LAST_MODIFIED_DATE
    description: Date of last modification
    tests:
    - not_null
  - name: LAST_MODIFIED_BY_ID
    description: ID of user who last modified the app
    tests:
    - not_null
  - name: SYSTEM_MODSTAMP
    description: System modification timestamp
    tests:
    - not_null
  - name: VERSION
    description: Version number of the application
    tests:
    - not_null
  - name: DEVICE_PLATFORM
    description: Platform the app is designed for
    tests:
    - not_null
  - name: MINIMUM_OS_VERSION
    description: Minimum required OS version for the app
    tests:
    - not_null
  - name: DEVICE_TYPE
    description: Type of device the app is for
    tests:
    - not_null
  - name: APPLICATION_FILE_LENGTH
    description: Size of the application file
    tests:
    - not_null
  - name: APPLICATION_ICON
    description: Icon of the application
    tests:
    - not_null
  - name: IS_ENTERPRISE_APP
    description: Flag indicating if it's an enterprise app
    tests:
    - not_null
  - name: APP_INSTALL_URL
    description: URL for installing the application
    tests:
    - not_null
  - name: APPLICATION_BUNDLE_IDENTIFIER
    description: Unique identifier for the app bundle
    tests:
    - not_null
  - name: APPLICATION_BINARY_FILE_NAME
    description: Name of the application's binary file
    tests:
    - not_null
  - name: APPLICATION_ICON_FILE_NAME
    description: Filename of the application's icon
    tests:
    - not_null
  - name: _FIVETRAN_DELETED
    description: Fivetran deletion status
    tests:
    - not_null
  - name: _FIVETRAN_SYNCED
    description: Fivetran synchronization timestamp
    tests:
    - not_null
  tests: []
