version: 2
models:
- name: stg_SAML_SSO_CONFIG
  description: The table is about SAML Single Sign-On (SSO) configuration. It contains
    details such as issuer, audience, login URL, logout URL, and identity mapping.
    The table also includes options for user provisioning, MFA requirements, and signature
    methods. It stores metadata like creation date, last modified date, and version.
    This configuration likely manages SSO settings for an application or service.
  columns:
  - name: ID
    description: Unique identifier for the SSO configuration
    tests:
    - not_null
  - name: IS_DELETED
    description: Flag indicating if the record is deleted
    tests:
    - not_null
  - name: DEVELOPER_NAME
    description: Developer-friendly name for the configuration
    tests:
    - not_null
  - name: LANGUAGE_
    description: Language of the configuration
    tests:
    - not_null
  - name: MASTER_LABEL
    description: User-friendly label for the configuration
    tests:
    - not_null
  - name: NAMESPACE_PREFIX
    description: Namespace prefix for the configuration
    tests:
    - not_null
  - name: CREATED_DATE
    description: Date when the configuration was created
    tests:
    - not_null
  - name: CREATED_BY_ID
    description: ID of the user who created the configuration
    tests:
    - not_null
  - name: LAST_MODIFIED_DATE
    description: Date of last modification
    tests:
    - not_null
  - name: LAST_MODIFIED_BY_ID
    description: ID of the user who last modified the configuration
    tests:
    - not_null
  - name: SYSTEM_MODSTAMP
    description: System modification timestamp
    tests:
    - not_null
  - name: VERSION
    description: Version number of the configuration
    tests:
    - not_null
  - name: ISSUER
    description: Entity issuing the SAML assertion
    tests:
    - not_null
  - name: OPTIONS_SP_INIT_BINDING
    description: Service Provider initiated binding options
    tests:
    - not_null
  - name: OPTIONS_USER_PROVISIONING
    description: User provisioning options
    tests:
    - not_null
  - name: OPTIONS_USE_CONFIG_REQUEST_METHOD
    description: Use configured request method option
    tests:
    - not_null
  - name: OPTIONS_USE_SAME_DIGEST_ALGO_FOR_SIGNING
    description: Use same digest algorithm for signing option
    tests:
    - not_null
  - name: OPTIONS_REQUIRE_MFA_SAML
    description: Require MFA for SAML option
    tests:
    - not_null
  - name: ATTRIBUTE_FORMAT
    description: Format of the SAML attribute
    tests:
    - not_null
  - name: ATTRIBUTE_NAME
    description: Name of the SAML attribute
    tests:
    - not_null
  - name: AUDIENCE
    description: Intended audience for the SAML assertion
    tests:
    - not_null
  - name: IDENTITY_MAPPING
    description: Method for mapping user identities
    tests:
    - not_null
  - name: IDENTITY_LOCATION
    description: Location of the identity information
    tests:
    - not_null
  - name: EXECUTION_USER_ID
    description: ID of the user executing the SSO
    tests:
    - not_null
  - name: LOGIN_URL
    description: URL for SSO login
    tests:
    - not_null
  - name: LOGOUT_URL
    description: URL for SSO logout
    tests:
    - not_null
  - name: ERROR_URL
    description: URL to redirect on SSO error
    tests:
    - not_null
  - name: VALIDATION_CERT
    description: Certificate for validating SAML responses
    tests:
    - not_null
  - name: REQUEST_SIGNATURE_METHOD
    description: Method for signing SAML requests
    tests:
    - not_null
  - name: SINGLE_LOGOUT_URL
    description: URL for single logout
    tests:
    - not_null
  - name: SINGLE_LOGOUT_BINDING
    description: Specifies the binding method for SAML Single Logout
    tests:
    - not_null
  - name: _FIVETRAN_DELETED
    description: Indicates if the record has been deleted
    tests:
    - not_null
  - name: _FIVETRAN_SYNCED
    description: Timestamp of last synchronization by Fivetran
    tests:
    - not_null
  tests: []
