version: 2
models:
- name: stg_CONNECTED_APPLICATION
  description: The table is about connected applications in a system. It contains
    details like application name, creation and modification dates, and various configuration
    options. The options include settings for user approval, token validity, session
    policies, and push notifications. The table also stores timeout values and URLs
    related to the application. This likely represents external applications integrated
    with a main system, tracking their settings and access configurations.
  columns:
  - name: ID
    description: Unique identifier for the connected application
    tests:
    - not_null
  - name: NAME
    description: Name of the connected application
    tests:
    - not_null
  - name: CREATED_DATE
    description: Date when the application was created
    tests:
    - not_null
  - name: CREATED_BY_ID
    description: ID of the user who created the application
    tests:
    - not_null
  - name: LAST_MODIFIED_DATE
    description: Date of last modification
    tests:
    - not_null
  - name: LAST_MODIFIED_BY_ID
    description: ID of the user who last modified the application
    tests:
    - not_null
  - name: SYSTEM_MODSTAMP
    description: System modification timestamp
    tests:
    - not_null
  - name: OPTIONS_ALLOW_ADMIN_APPROVED_USERS_ONLY
    description: Flag for admin-approved users only
    tests:
    - not_null
  - name: OPTIONS_REFRESH_TOKEN_VALIDITY_METRIC
    description: Metric for refresh token validity
    tests:
    - not_null
  - name: OPTIONS_HAS_SESSION_LEVEL_POLICY
    description: Flag for session-level policy
    tests:
    - not_null
  - name: OPTIONS_IS_INTERNAL
    description: Flag indicating if the application is internal
    tests:
    - not_null
  - name: OPTIONS_FULL_CONTENT_PUSH_NOTIFICATIONS
    description: Flag for full content push notifications
    tests:
    - not_null
  - name: OPTIONS_CODE_CREDENTIAL_GUEST_ENABLED
    description: Flag for code credential guest access
    tests:
    - not_null
  - name: OPTIONS_APP_ISSUE_JWT_TOKEN_ENABLED
    description: Flag for JWT token issuance
    tests:
    - not_null
  - name: OPTIONS_TOKEN_EXCHANGE_MANAGE_BIT_ENABLED
    description: Flag for token exchange manage bit
    tests:
    - not_null
  - name: MOBILE_SESSION_TIMEOUT
    description: Timeout duration for mobile sessions
    tests:
    - not_null
  - name: PIN_LENGTH
    description: Length of PIN required
    tests:
    - not_null
  - name: START_URL
    description: Starting URL for the application
    tests:
    - not_null
  - name: MOBILE_START_URL
    description: Starting URL for mobile application
    tests:
    - not_null
  - name: REFRESH_TOKEN_VALIDITY_PERIOD
    description: Validity period for refresh tokens
    tests:
    - not_null
  - name: UVID_TIMEOUT
    description: Timeout for User Verification ID
    tests:
    - not_null
  - name: NAMED_USER_UVID_TIMEOUT
    description: Timeout for named user UVID
    tests:
    - not_null
  - name: _FIVETRAN_DELETED
    description: Fivetran deletion flag
    tests:
    - not_null
  - name: _FIVETRAN_SYNCED
    description: Fivetran synchronization timestamp
    tests:
    - not_null
  tests: []
