version: 2
models:
- name: stg_ORG_EMAIL_ADDRESS_SECURITY
  description: The table represents email address security settings for an organization.
    It links organizational entities (PARENT_ID) with specific email addresses (ORG_WIDE_EMAIL_ADDRESS_ID).
    The table tracks modifications (SYSTEM_MODSTAMP) and synchronization status (_FIVETRAN_SYNCED).
    It also indicates whether records have been deleted (_FIVETRAN_DELETED). This
    structure allows for managing email security across different levels of an organization.
  columns:
  - name: ID
    description: Unique identifier for each email security setting
    tests:
    - not_null
  - name: PARENT_ID
    description: ID of the parent organizational entity
    tests:
    - not_null
  - name: ORG_WIDE_EMAIL_ADDRESS_ID
    description: ID of the associated organization-wide email address
    tests:
    - not_null
  - name: SYSTEM_MODSTAMP
    description: Timestamp of last modification to the record
    tests:
    - not_null
  - name: _FIVETRAN_DELETED
    description: Flag indicating if the record was deleted
    tests:
    - not_null
  - name: _FIVETRAN_SYNCED
    description: Timestamp of last synchronization by Fivetran
    tests:
    - not_null
  tests: []
