version: 2
sources:
- name: cocoon
  tables:
  - shopify_abandoned_checkout_data
  - shopify_abandoned_checkout_discount_code_data
  - shopify_abandoned_checkout_shipping_line_data
  - shopify_collection_data
  - shopify_collection_product_data
  - shopify_customer_data
  - shopify_customer_tag_data
  - shopify_discount_code_data
  - shopify_fulfillment_data
  - shopify_fulfillment_event_data
  - shopify_inventory_item_data
  - shopify_inventory_level_data
  - shopify_location_data
  - shopify_metafield_data
  - shopify_order_adjustment_data
  - shopify_order_data
  - shopify_order_discount_code_data
  - shopify_order_line_data
  - shopify_order_line_refund_data
  - shopify_order_note_attribute_data
  - shopify_order_shipping_line_data
  - shopify_order_shipping_tax_line_data
  - shopify_order_tag_data
  - shopify_order_url_tag_data
  - shopify_price_rule_data
  - shopify_product_data
  - shopify_product_image_data
  - shopify_product_tag_data
  - shopify_product_variant_data
  - shopify_refund_data
  - shopify_shop_data
  - shopify_tax_line_data
  - shopify_tender_transaction_data
  - shopify_transaction_data
