version: 2
sources:
- name: cocoon
  database: memory
  schema: main
  tables:
  - name: balance_transaction_data
  - name: card_data
  - name: charge_data
  - name: customer_data
  - name: dispute_data
  - name: fee_data
  - name: invoice_data
  - name: invoice_line_item_data
  - name: payment_intent_data
  - name: payment_method_card_data
  - name: payment_method_data
  - name: payout_data
  - name: plan_data
  - name: price_data
  - name: refund_data
  - name: sf_account_history_data
  - name: sf_contact_history_data
  - name: sf_event_data
  - name: sf_lead_data
  - name: sf_opportunity_history_data
  - name: sf_task_data
  - name: sf_user_data
  - name: sf_user_role_data
  - name: subscription_data
  - name: transfer_data
