name: 'linkedin'
version: '0.8.0'
config-version: 2
profile: 'integration_tests' 
require-dbt-version: [">=1.3.0", "<2.0.0"]
vars:
  linkedin:
    ad_analytics_by_creative: "{{ ref('stg_linkedin_ads__ad_analytics_by_creative') }}"
    creative_history: "{{ ref('stg_linkedin_ads__creative_history') }}"
    campaign_history: "{{ ref('stg_linkedin_ads__campaign_history') }}"
    campaign_group_history: "{{ ref('stg_linkedin_ads__campaign_group_history') }}"
    account_history: "{{ ref('stg_linkedin_ads__account_history') }}"
    ad_analytics_by_campaign: "{{ ref('stg_linkedin_ads__ad_analytics_by_campaign') }}"
  linkedin_ads__creative_passthrough_metrics: []
  linkedin_ads__campaign_passthrough_metrics: []
models:
  linkedin:
    +materialized: table
    +schema: linkedin_ads
