version: 2
sources:
- name: cocoon
  tables:
  - linkedin_account_history_data
  - linkedin_ad_analytics_by_campaign_data
  - linkedin_ad_analytics_by_creative_data
  - linkedin_campaign_group_history_data
  - linkedin_campaign_history_data
  - linkedin_creative_history_data
