name: 'facebook_ads'
version: '0.7.2'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
profile: 'integration_tests' 
models:
  facebook_ads:
    +schema: facebook_ads
    +materialized: table
    intermediate:
      +materialized: view
vars:
  facebook_ads:
    account_history: "{{ ref('stg_facebook_ads__account_history') }}"
    ad_history: "{{ ref('stg_facebook_ads__ad_history') }}"
    ad_set_history: "{{ ref('stg_facebook_ads__ad_set_history') }}"
    basic_ad: "{{ ref('stg_facebook_ads__basic_ad') }}"
    campaign_history: "{{ ref('stg_facebook_ads__campaign_history') }}"
    creative_history: "{{ ref('stg_facebook_ads__creative_history') }}"
    url_tag: "{{ ref('stg_facebook_ads__url_tag') }}"
