version: 2
sources:
- name: cocoon
  database: memory
  schema: main
  tables:
  - name: customer
  - name: lineitem
  - name: nation
  - name: order
  - name: part
  - name: partsupp
  - name: region
  - name: supplier
