version: 2
sources:
- name: cocoon
  tables:
  - company_data
  - company_property_history_data
  - contact_data
  - contact_list_data
  - contact_list_member_data
  - contact_property_history_data
  - deal_company_data
  - deal_contact_data
  - deal_data
  - deal_pipeline_data
  - deal_pipeline_stage_data
  - deal_property_history_data
  - deal_stage_data
  - email_campaign_data
  - email_event_bounce_data
  - email_event_click_data
  - email_event_data
  - email_event_deferred_data
  - email_event_delivered_data
  - email_event_dropped_data
  - email_event_forward_data
  - email_event_open_data
  - email_event_print_data
  - email_event_sent_data
  - email_event_spam_report_data
  - email_event_status_change_data
  - engagement_call_data
  - engagement_company_data
  - engagement_contact_data
  - engagement_data
  - engagement_deal_data
  - engagement_email_data
  - engagement_meeting_data
  - engagement_note_data
  - engagement_task_data
  - merged_deal_data
  - owner_data
  - property_data
  - property_option_data
  - ticket_company_data
  - ticket_contact_data
  - ticket_data
  - ticket_deal_data
  - ticket_engagement_data
  - ticket_pipeline_data
  - ticket_pipeline_stage_data
  - ticket_property_history_data
