version: 2
sources:
- name: cocoon
  database: memory
  schema: main
  tables:
  - name: ASSOCIATION_TYPE
  - name: COMPANY
  - name: CONTACT
  - name: DEAL
  - name: DEAL_PIPELINE
  - name: DEAL_PIPELINE_STAGE
  - name: DEAL_STAGE
  - name: EMAIL_SUBSCRIPTION
  - name: ENGAGEMENT
  - name: ENGAGEMENT_CONTACT
  - name: ENGAGEMENT_TASK
  - name: FORM
  - name: OWNER
  - name: TICKET_PIPELINE
  - name: TICKET_PIPELINE_STAGE
  - name: USERS
