version: 2
sources:
- name: cocoon
  database: memory
  schema: main
  tables:
  - name: A1_totalInventory_All
  - name: A3_medianAskingPrice_All
  - name: A5_recordedSalesVolume_All
  - name: A6_medianSalePrice_All
  - name: A7_saleListRatio_All
  - name: A8_priceCutShare_All
  - name: A9_daysOnMarket_All
  - name: B1_totalInventory_Condo
  - name: B3_medianAskingPrice_Condo
  - name: B5_recordedSalesVolume_Condo
  - name: B6_medianSalePrice_Condo
  - name: B7_saleListRatio_Condo
  - name: B8_priceCutShare_Condo
  - name: B9_daysOnMarket_Condo
  - name: C1_totalInventory_Coop
  - name: C3_medianAskingPrice_Coop
  - name: C5_recordedSalesVolume_Coop
  - name: C6_medianSalePrice_Coop
  - name: C7_saleListRatio_Coop
  - name: C8_priceCutShare_Coop
  - name: C9_daysOnMarket_Coop
  - name: D1_totalInventory_Sfr
  - name: D3_medianAskingPrice_Sfr
  - name: D5_recordedSalesVolume_Sfr
  - name: D6_medianSalePrice_Sfr
  - name: D7_saleListRatio_Sfr
  - name: D8_priceCutShare_Sfr
  - name: D9_daysOnMarket_Sfr
  - name: E1_rentalInventory_All
  - name: E2_medianAskingRent_All
  - name: E3_discountShare_All
  - name: F1_rentalInventory_Studio
  - name: F2_medianAskingRent_Studio
  - name: F3_discountShare_Studio
  - name: G1_rentalInventory_OneBd
  - name: G2_medianAskingRent_OneBd
  - name: G3_discountShare_OneBd
  - name: H1_rentalInventory_TwoBd
  - name: H2_medianAskingRent_TwoBd
  - name: H3_discountShare_TwoBd
  - name: I1_rentalInventory_ThreePlusBd
  - name: I2_medianAskingRent_ThreePlusBd
  - name: I3_discountShare_ThreePlusBd
  - name: priceIndex_condos_co_ops_homes_All_Downtown_2018_09
  - name: priceIndex_condos_co_ops_homes_All_Midtown_2018_09
  - name: priceIndex_condos_co_ops_homes_All_Upper_East_Side_2018_09
  - name: priceIndex_condos_co_ops_homes_All_Upper_Manhattan_2018_09
  - name: priceIndex_condos_co_ops_homes_All_Upper_West_Side_2018_09
  - name: priceIndex_condos_co_ops_homes_Brooklyn_2018_09
  - name: priceIndex_condos_co_ops_homes_Central_Queens_2018_09
  - name: priceIndex_condos_co_ops_homes_East_Brooklyn_2018_09
  - name: priceIndex_condos_co_ops_homes_Manhattan_2018_09
  - name: priceIndex_condos_co_ops_homes_Northeast_Queens_2018_09
  - name: priceIndex_condos_co_ops_homes_Northwest_Brooklyn_2018_09
  - name: priceIndex_condos_co_ops_homes_Northwest_Queens_2018_09
  - name: priceIndex_condos_co_ops_homes_North_Brooklyn_2018_09
  - name: priceIndex_condos_co_ops_homes_NYC_2018_09
  - name: priceIndex_condos_co_ops_homes_Prospect_Park_2018_09
  - name: priceIndex_condos_co_ops_homes_Queens_2018_09
  - name: priceIndex_condos_co_ops_homes_South_Brooklyn_2018_09
  - name: priceIndex_condos_co_ops_homes_South_Queens_2018_09
  - name: priceIndex_condos_co_ops_homes_The_Rockaways_2018_09
  - name: rentIndex_condos_co_ops_homes_All_Downtown_2018_09
  - name: rentIndex_condos_co_ops_homes_All_Midtown_2018_09
  - name: rentIndex_condos_co_ops_homes_All_Upper_East_Side_2018_09
  - name: rentIndex_condos_co_ops_homes_All_Upper_Manhattan_2018_09
  - name: rentIndex_condos_co_ops_homes_All_Upper_West_Side_2018_09
  - name: rentIndex_condos_co_ops_homes_Brooklyn_2018_09
  - name: rentIndex_condos_co_ops_homes_Central_Queens_2018_09
  - name: rentIndex_condos_co_ops_homes_East_Brooklyn_2018_09
  - name: rentIndex_condos_co_ops_homes_Manhattan_2018_09
  - name: rentIndex_condos_co_ops_homes_Northeast_Queens_2018_09
  - name: rentIndex_condos_co_ops_homes_Northwest_Brooklyn_2018_09
  - name: rentIndex_condos_co_ops_homes_Northwest_Queens_2018_09
  - name: rentIndex_condos_co_ops_homes_North_Brooklyn_2018_09
  - name: rentIndex_condos_co_ops_homes_NYC_2018_09
  - name: rentIndex_condos_co_ops_homes_Prospect_Park_2018_09
  - name: rentIndex_condos_co_ops_homes_Queens_2018_09
  - name: rentIndex_condos_co_ops_homes_South_Brooklyn_2018_09
